version: 2

builds:
  - binary: five9
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/Cloverhound/five9-cli/cmd.Version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: Cloverhound
    name: five9-cli
  draft: false
  prerelease: auto
