// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var AgentGroupsCmd = &cobra.Command{
	Use:   "agent-groups",
	Short: "Manage agent groups",
}

var AgentGroupsCreateSample = `{
  "agents": [
    "example"
  ],
  "description": "example",
  "id": 0,
  "name": "example"
}`

var AgentGroupsModifySample = `{
  "agents": [
    "example"
  ],
  "description": "example",
  "id": 0,
  "name": "example"
}`

var AgentGroupsCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Use this method to create an agent group. The group can be empty or contain agents.",
	Long:  `Use this method to create an agent group. The group can be empty or contain agents.

Body file schema (agentGroup):
agents (string[]): List of agents in the group.
description (string): Description of the agent group.
id (long): ID of the group.
name (string): Name of the group.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(AgentGroupsCreateSample)
			return nil
		}
		req := soap.NewRequest("createAgentGroup")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("group", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var AgentGroupsDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Deletes an agent group. Agents in the group are not deleted.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteAgentGroup")
		flagGroupName, _ := cmd.Flags().GetString("group-name")
		req.SetParam("groupName", flagGroupName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var AgentGroupsGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Returns an agent group.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getAgentGroup")
		flagGroupName, _ := cmd.Flags().GetString("group-name")
		req.SetParam("groupName", flagGroupName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var AgentGroupsListCmd = &cobra.Command{
	Use:   "list",
	Short: "Returns a list of agent groups whose names match a string pattern.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getAgentGroups")
		flagGroupNamePattern, _ := cmd.Flags().GetString("group-name-pattern")
		req.SetParam("groupNamePattern", flagGroupNamePattern)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var AgentGroupsModifyCmd = &cobra.Command{
	Use:   "modify",
	Short: "Updates an agent group.",
	Long:  `Updates an agent group.

Body file schema (agentGroup):
agents (string[]): List of agents in the group.
description (string): Description of the agent group.
id (long): ID of the group.
name (string): Name of the group.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(AgentGroupsModifySample)
			return nil
		}
		req := soap.NewRequest("modifyAgentGroup")
		flagAddAgents, _ := cmd.Flags().GetStringSlice("add-agents")
		for _, v := range flagAddAgents {
			req.SetParam("addAgents", v)
		}
		flagRemoveAgents, _ := cmd.Flags().GetStringSlice("remove-agents")
		for _, v := range flagRemoveAgents {
			req.SetParam("removeAgents", v)
		}
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("group", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(AgentGroupsCmd)
	AgentGroupsCmd.AddCommand(AgentGroupsCreateCmd)
	AgentGroupsCreateCmd.Flags().String("body-file", "", "JSON file for group parameter")
	AgentGroupsCreateCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	AgentGroupsCmd.AddCommand(AgentGroupsDeleteCmd)
	AgentGroupsDeleteCmd.Flags().String("group-name", "", "Name of the group.")
	AgentGroupsCmd.AddCommand(AgentGroupsGetCmd)
	AgentGroupsGetCmd.Flags().String("group-name", "", "Name of the group.")
	AgentGroupsCmd.AddCommand(AgentGroupsListCmd)
	AgentGroupsListCmd.Flags().String("group-name-pattern", ".*", "Name of the group or regular expression. For all agent groups, use this pattern: .*.")
	AgentGroupsCmd.AddCommand(AgentGroupsModifyCmd)
	AgentGroupsModifyCmd.Flags().StringSlice("add-agents", nil, "List of agent names to be added to the group.")
	AgentGroupsModifyCmd.Flags().StringSlice("remove-agents", nil, "List of agent names to be removed from the group.")
	AgentGroupsModifyCmd.Flags().String("body-file", "", "JSON file for group parameter")
	AgentGroupsModifyCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
}
