// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var CallVariablesCmd = &cobra.Command{
	Use:   "call-variables",
	Short: "Manage call variables and variable groups",
}

var CallVariablesCreateSample = `{
  "applyToAllDispositions": false,
  "defaultValue": "example",
  "description": "example",
  "dispositions": [
    "example"
  ],
  "group": "example",
  "name": "example",
  "reporting": false,
  "restrictions": [
    {
      "type": "MinValue",
      "value": "example"
    }
  ],
  "sensitiveData": false,
  "type": "STRING"
}`

var CallVariablesModifySample = `{
  "applyToAllDispositions": false,
  "defaultValue": "example",
  "description": "example",
  "dispositions": [
    "example"
  ],
  "group": "example",
  "name": "example",
  "reporting": false,
  "restrictions": [
    {
      "type": "MinValue",
      "value": "example"
    }
  ],
  "sensitiveData": false,
  "type": "STRING"
}`

var CallVariablesCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Creates a call variable.",
	Long:  `Creates a call variable.

Body file schema (callVariable):
applyToAllDispositions (boolean): Whether to use the variable for all dispositions. True: Use the variable for all dispositions. False: Do not use the variable for all dispositions.
defaultValue (string): Optional value that may be assigned to a call variable. Some data types (callVariableType) can have a default value.
description (string): Description of the variable.
dispositions (string[]): If applyToAllDispositions is False, this parameter lists the names of the dispositions for which to set this variable.
group (string): Group name of the call variable.
name (string): Name of the call variable.
reporting (boolean): Whether to add the values to reports: True: Variables are added to reports. False: Default. Variables are not added to reports.
restrictions (callVariableRestriction[]): Possible values of the variable.
  type (cavRestrictionType): One of the available restrictions.
  value (string): Value by which to limit the variable.
sensitiveData (boolean): Whether the variable contains personal data that identifies the customer.
type (callVariableType): One of the available types of call variables.
  Enum: STRING, NUMBER, DATE, TIME, DATE_TIME, CURRENCY, BOOLEAN, PERCENT, EMAIL, URL, PHONE, TIME_PERIOD`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CallVariablesCreateSample)
			return nil
		}
		req := soap.NewRequest("createCallVariable")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("variable", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CallVariablesCreateGroupCmd = &cobra.Command{
	Use:   "create-group",
	Short: "Creates a call variables group.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("createCallVariablesGroup")
		flagName, _ := cmd.Flags().GetString("name")
		req.SetParam("name", flagName)
		flagDescription, _ := cmd.Flags().GetString("description")
		req.SetParam("description", flagDescription)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CallVariablesDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Deletes a call variable.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteCallVariable")
		flagName, _ := cmd.Flags().GetString("name")
		req.SetParam("name", flagName)
		flagGroupName, _ := cmd.Flags().GetString("group-name")
		req.SetParam("groupName", flagGroupName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CallVariablesDeleteGroupCmd = &cobra.Command{
	Use:   "delete-group",
	Short: "Deletes a group of call variables.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteCallVariablesGroup")
		flagName, _ := cmd.Flags().GetString("name")
		req.SetParam("name", flagName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CallVariablesListGroupsCmd = &cobra.Command{
	Use:   "list-groups",
	Short: "Returns information about a group of call variables that match a pattern.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getCallVariableGroups")
		flagNamePattern, _ := cmd.Flags().GetString("name-pattern")
		req.SetParam("namePattern", flagNamePattern)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CallVariablesListCmd = &cobra.Command{
	Use:   "list",
	Short: "Returns information about a group of call variables.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getCallVariables")
		flagNamePattern, _ := cmd.Flags().GetString("name-pattern")
		req.SetParam("namePattern", flagNamePattern)
		flagGroupName, _ := cmd.Flags().GetString("group-name")
		req.SetParam("groupName", flagGroupName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CallVariablesModifyCmd = &cobra.Command{
	Use:   "modify",
	Short: "Replaces a call variable with another of the same name.",
	Long:  `Replaces a call variable with another of the same name.

Body file schema (callVariable):
applyToAllDispositions (boolean): Whether to use the variable for all dispositions. True: Use the variable for all dispositions. False: Do not use the variable for all dispositions.
defaultValue (string): Optional value that may be assigned to a call variable. Some data types (callVariableType) can have a default value.
description (string): Description of the variable.
dispositions (string[]): If applyToAllDispositions is False, this parameter lists the names of the dispositions for which to set this variable.
group (string): Group name of the call variable.
name (string): Name of the call variable.
reporting (boolean): Whether to add the values to reports: True: Variables are added to reports. False: Default. Variables are not added to reports.
restrictions (callVariableRestriction[]): Possible values of the variable.
  type (cavRestrictionType): One of the available restrictions.
  value (string): Value by which to limit the variable.
sensitiveData (boolean): Whether the variable contains personal data that identifies the customer.
type (callVariableType): One of the available types of call variables.
  Enum: STRING, NUMBER, DATE, TIME, DATE_TIME, CURRENCY, BOOLEAN, PERCENT, EMAIL, URL, PHONE, TIME_PERIOD`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CallVariablesModifySample)
			return nil
		}
		req := soap.NewRequest("modifyCallVariable")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("variable", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CallVariablesModifyGroupCmd = &cobra.Command{
	Use:   "modify-group",
	Short: "Updates the description of a call variables group.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("modifyCallVariablesGroup")
		flagName, _ := cmd.Flags().GetString("name")
		req.SetParam("name", flagName)
		flagDescription, _ := cmd.Flags().GetString("description")
		req.SetParam("description", flagDescription)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(CallVariablesCmd)
	CallVariablesCmd.AddCommand(CallVariablesCreateCmd)
	CallVariablesCreateCmd.Flags().String("body-file", "", "JSON file for variable parameter")
	CallVariablesCreateCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CallVariablesCmd.AddCommand(CallVariablesCreateGroupCmd)
	CallVariablesCreateGroupCmd.Flags().String("name", "", "Name of call variables group.")
	CallVariablesCreateGroupCmd.Flags().String("description", "", "Comment about the group.")
	CallVariablesCmd.AddCommand(CallVariablesDeleteCmd)
	CallVariablesDeleteCmd.Flags().String("name", "", "Name of call variables group.")
	CallVariablesDeleteCmd.Flags().String("group-name", "", "Group name of call variable.")
	CallVariablesCmd.AddCommand(CallVariablesDeleteGroupCmd)
	CallVariablesDeleteGroupCmd.Flags().String("name", "", "Name of call variables group.")
	CallVariablesCmd.AddCommand(CallVariablesListGroupsCmd)
	CallVariablesListGroupsCmd.Flags().String("name-pattern", ".*", "Name of call variables group or regular expression. If omitted, all call variables are returned.")
	CallVariablesCmd.AddCommand(CallVariablesListCmd)
	CallVariablesListCmd.Flags().String("name-pattern", ".*", "Name of call variables group or regular expression. If omitted, all call variables are returned.")
	CallVariablesListCmd.Flags().String("group-name", "", "Group name of call variables.")
	CallVariablesCmd.AddCommand(CallVariablesModifyCmd)
	CallVariablesModifyCmd.Flags().String("body-file", "", "JSON file for variable parameter")
	CallVariablesModifyCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CallVariablesCmd.AddCommand(CallVariablesModifyGroupCmd)
	CallVariablesModifyGroupCmd.Flags().String("name", "", "Name of group.")
	CallVariablesModifyGroupCmd.Flags().String("description", "", "New description of the group.")
}
