// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var CampaignsCmd = &cobra.Command{
	Use:   "campaigns",
	Short: "Manage campaigns (inbound, outbound, autodial)",
}

var CampaignsAddListsSample = `{
  "campaignName": "example",
  "dialingPriority": 0,
  "dialingRatio": 0,
  "listName": "example",
  "priority": 0
}`

var CampaignsCreateAutodialSample = `{
  "agentAvailability": "ReadyToReceiveCalls",
  "agentSkillName": "example",
  "defaultIvrSchedule": {
    "name": "example",
    "scriptName": "example",
    "scriptParameters": [
      {
        "name": "example",
        "value": "example"
      }
    ]
  },
  "dialIfAgentsAvailable": false,
  "maxNumOfLines": 0
}`

var CampaignsCreateInboundSample = `{
  "inboundCampaign": {
    "defaultIvrSchedule": {
      "name": "example",
      "scriptName": "example",
      "scriptParameters": [
        {
          "name": "example",
          "value": "example"
        }
      ]
    },
    "maxNumOfLines": 0
  }
}`

var CampaignsCreateOutboundSample = `{
  "actionOnAnswerMachine": {
    "actionArgument": "example",
    "actionType": "DROP_CALL",
    "maxWaitTime": "00:00:00"
  },
  "actionOnQueueExpiration": {
    "actionArgument": "example",
    "actionType": "DROP_CALL",
    "maxWaitTime": "00:00:00"
  },
  "callAnalysisMode": "NO_ANALYSIS",
  "callsAgentRatio": 0.0,
  "dialNumberOnTimeout": false,
  "dialingMode": "PREDICTIVE",
  "dialingPriority": 0,
  "dialingRatio": 0,
  "distributionAlgorithm": "LongestReadyTime",
  "distributionTimeFrame": {},
  "limitPreviewTime": false,
  "maxDroppedCallsPercentage": 0.0,
  "maxPreviewTime": "00:00:00",
  "maxQueueTime": "00:00:00",
  "monitorDroppedCalls": false,
  "previewDialImmediately": false,
  "useTelemarketingMaxQueTimeEq1": false,
  "analyzeLevel": 0,
  "CRMRedialTimeout": "00:00:00",
  "dnisAsAni": false,
  "enableListDialingRatios": false,
  "listDialingMode": "VERTICAL_DIALING",
  "noOutOfNumbersAlert": false,
  "stateDialingRule": {},
  "timeZoneAssignment": {},
  "autoRecord": false,
  "callWrapup": {
    "agentNotReady": false,
    "dispostionName": "example",
    "enabled": false,
    "reasonCodeName": "example",
    "timeout": "00:00:00"
  },
  "ftpHost": "example",
  "ftpPassword": "example",
  "ftpUser": "example",
  "recordingNameAsSid": false,
  "useFtp": false
}`

var CampaignsListSample = `"OUTBOUND"`

var CampaignsModifyAutodialSample = `{
  "agentAvailability": "ReadyToReceiveCalls",
  "agentSkillName": "example",
  "defaultIvrSchedule": {
    "name": "example",
    "scriptName": "example",
    "scriptParameters": [
      {
        "name": "example",
        "value": "example"
      }
    ]
  },
  "dialIfAgentsAvailable": false,
  "maxNumOfLines": 0
}`

var CampaignsModifyListsSample = `{
  "campaignName": "example",
  "dialingPriority": 0,
  "dialingRatio": 0,
  "listName": "example",
  "priority": 0
}`

var CampaignsModifyInboundSample = `{
  "inboundCampaign": {
    "defaultIvrSchedule": {
      "name": "example",
      "scriptName": "example",
      "scriptParameters": [
        {
          "name": "example",
          "value": "example"
        }
      ]
    },
    "maxNumOfLines": 0
  }
}`

var CampaignsModifyOutboundSample = `{
  "actionOnAnswerMachine": {
    "actionArgument": "example",
    "actionType": "DROP_CALL",
    "maxWaitTime": "00:00:00"
  },
  "actionOnQueueExpiration": {
    "actionArgument": "example",
    "actionType": "DROP_CALL",
    "maxWaitTime": "00:00:00"
  },
  "callAnalysisMode": "NO_ANALYSIS",
  "callsAgentRatio": 0.0,
  "dialNumberOnTimeout": false,
  "dialingMode": "PREDICTIVE",
  "dialingPriority": 0,
  "dialingRatio": 0,
  "distributionAlgorithm": "LongestReadyTime",
  "distributionTimeFrame": {},
  "limitPreviewTime": false,
  "maxDroppedCallsPercentage": 0.0,
  "maxPreviewTime": "00:00:00",
  "maxQueueTime": "00:00:00",
  "monitorDroppedCalls": false,
  "previewDialImmediately": false,
  "useTelemarketingMaxQueTimeEq1": false,
  "analyzeLevel": 0,
  "CRMRedialTimeout": "00:00:00",
  "dnisAsAni": false,
  "enableListDialingRatios": false,
  "listDialingMode": "VERTICAL_DIALING",
  "noOutOfNumbersAlert": false,
  "stateDialingRule": {},
  "timeZoneAssignment": {},
  "autoRecord": false,
  "callWrapup": {
    "agentNotReady": false,
    "dispostionName": "example",
    "enabled": false,
    "reasonCodeName": "example",
    "timeout": "00:00:00"
  },
  "ftpHost": "example",
  "ftpPassword": "example",
  "ftpUser": "example",
  "recordingNameAsSid": false,
  "useFtp": false
}`

var CampaignsAsyncUpdateDispositionsSample = `{
  "commonDispositionValue": "example",
  "dispositionColumnNumber": 0,
  "dispositionsUpdateMode": {
    "UPDATE_ALL": "example",
    "UPDATE_IF_SOLE_CRM_MATCH": "example"
  },
  "updateToCommonDisposition": false,
  "warnIfNoCrmMatchFound": false
}`

var CampaignsGetDispositionsImportResultSample = `{
  "identifier": "example"
}`

var CampaignsSetStrategiesSample = `{
  "strategies": [
    {
      "description": "example",
      "enabled": false,
      "filter": {
        "conditionGroupingType": "All",
        "conditions": {
          "compareOperator": {},
          "leftValue": "example",
          "rightValue": "example"
        },
        "customGrouping": "example"
      },
      "name": "example",
      "schedule": {
        "redialAfterMins": 0,
        "startFromDay": 0
      },
      "startAfterTimeMins": {}
    }
  ]
}`

var CampaignsUpdateDispositionsSample = `{
  "commonDispositionValue": "example",
  "dispositionColumnNumber": 0,
  "dispositionsUpdateMode": {
    "UPDATE_ALL": "example",
    "UPDATE_IF_SOLE_CRM_MATCH": "example"
  },
  "updateToCommonDisposition": false,
  "warnIfNoCrmMatchFound": false
}`

var CampaignsUpdateDispositionsCsvSample = `{
  "commonDispositionValue": "example",
  "dispositionColumnNumber": 0,
  "dispositionsUpdateMode": {
    "UPDATE_ALL": "example",
    "UPDATE_IF_SOLE_CRM_MATCH": "example"
  },
  "updateToCommonDisposition": false,
  "warnIfNoCrmMatchFound": false
}`

var CampaignsAddDnisCmd = &cobra.Command{
	Use:   "add-dnis",
	Short: "Adds DNIS (Dialed Number Identification Service) numbers to an inbound campaign. A DNIS is a phone number that can be...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("addDNISToCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		flagDNISList, _ := cmd.Flags().GetStringSlice("dnislist")
		for _, v := range flagDNISList {
			req.SetParam("DNISList", v)
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsAddDispositionsCmd = &cobra.Command{
	Use:   "add-dispositions",
	Short: "Adds a list of dispositions to a campaign. The dispositions must already be configured.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("addDispositionsToCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		flagIsSkipPreviewDisposition, _ := cmd.Flags().GetBool("is-skip-preview-disposition")
		if flagIsSkipPreviewDisposition {
			req.SetParam("isSkipPreviewDisposition", "true")
		}
		flagDispositions, _ := cmd.Flags().GetStringSlice("dispositions")
		for _, v := range flagDispositions {
			req.SetParam("dispositions", v)
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsAddListsCmd = &cobra.Command{
	Use:   "add-lists",
	Short: "Adds dialing lists to an outbound campaign. The dialing lists must already be configured.",
	Long:  `Adds dialing lists to an outbound campaign. The dialing lists must already be configured.

Body file schema (listState):
campaignName (string): Name of campaign to which the list is associated.
dialingPriority (int): Dialing priority for the list In the campaign.
dialingRatio (int): Dialing ratio for this list compared to other lists associated with the same campaign.
listName (string): Name of list.
priority (int): Dialing priority of a list in a campaign. A list with a lower priority number is dialed first.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignsAddListsSample)
			return nil
		}
		req := soap.NewRequest("addListsToCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("lists", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsAddSkillsCmd = &cobra.Command{
	Use:   "add-skills",
	Short: "Adds skills to the specified campaign. The skills must already be configured.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("addSkillsToCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		flagSkills, _ := cmd.Flags().GetStringSlice("skills")
		for _, v := range flagSkills {
			req.SetParam("skills", v)
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsCreateAutodialCmd = &cobra.Command{
	Use:   "create-autodial",
	Short: "Creates an autodial campaign.",
	Long:  `Creates an autodial campaign.

Body file schema (autodialCampaign):
agentAvailability (agentAvailability): Types of agent states considered available. Autodial campaigns dial only agents that are available to process calls. If omitted, the list is dialed continuously regardless of agent availability.
  Enum: ReadyToReceiveCalls, ReadyToReceiveCallsOrBusy, LoggedIn
agentSkillName (string): Numbers dialed only if agents with the specified skill are available. If empty when dialIfAgentsAvailable=True, agent availability is for any skill. When modifyAutodialCampaign specifies agentSkillName=null, the value remains.
defaultIvrSchedule (ivrScriptSchedule): Schedule of the IVR script that processes call flow. Required for inbound and autodial calls.
  name (string): Name of the IVR schedule.
  scriptName (string): Name of the IVR script.
  scriptParameters (scriptParameterValue[]): Parameters of a foreign script module used in the IVR script.
dialIfAgentsAvailable (boolean): Whether to dial numbers only if agents with agentSkillName are available. True: Dial only if agents are available in the skill group. False: Dial regardless of agent availability in the skill group.
maxNumOfLines (int): Maximum number of outbound phone lines dedicated to the campaign.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignsCreateAutodialSample)
			return nil
		}
		req := soap.NewRequest("createAutodialCampaign")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("campaign", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsCreateInboundCmd = &cobra.Command{
	Use:   "create-inbound",
	Short: "Creates an inbound campaign. When using the ivrScriptSchedule in this method, only the default IVR schedule can be se...",
	Long:  `Creates an inbound campaign. When using the ivrScriptSchedule in this method, only the default IVR schedule can be set or modified via the API. Additionally, the name parameter of the IVR script schedule object must be excluded.

Body file schema (inboundCampaign):
inboundCampaign (generalCampaign): Attributes of an inbound campaign.
  defaultIvrSchedule (ivrScriptSchedule): Configuration of an IVR script.
  maxNumOfLines (int): Maximum number of simultaneous calls.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignsCreateInboundSample)
			return nil
		}
		req := soap.NewRequest("createInboundCampaign")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("campaign", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsCreateOutboundCmd = &cobra.Command{
	Use:   "create-outbound",
	Short: "Creates an outbound campaign.",
	Long:  `Creates an outbound campaign.

Body file schema (outboundCampaign):
actionOnAnswerMachine (campaignDialingAction): Action to take when the answering machine is detected.
  actionArgument (string): Name of prompt or IVR script to execute when a campaign-related event occurs. It is ignored when action type is DROP_CALL.
  actionType (campaignDialingActionType): Action to take when a specific event occurs.
  maxWaitTime (timer): Maximum waiting time for action on answering machine.
actionOnQueueExpiration (campaignDialingAction): Action to take when the maximum queue time expires, which occurs when no agent is available to take a call.
  actionArgument (string): Name of prompt or IVR script to execute when a campaign-related event occurs. It is ignored when action type is DROP_CALL.
  actionType (campaignDialingActionType): Action to take when a specific event occurs.
  maxWaitTime (timer): Maximum waiting time for action on answering machine.
callAnalysisMode (callAnalysisMode): Types of attempts when a call is answered.
  Enum: NO_ANALYSIS, FAX_ONLY, FAX_AND_ANSWERING_MACHINE
callsAgentRatio (double): For campaigns in the power mode, count of phone numbers dialed for an agent ready for a new call.
dialNumberOnTimeout (boolean): For campaigns in the preview mode, use as follows: True: Dial number when preview time expires. False: Set agent to Not Ready state.
dialingMode (campaignDialingMode): Types of dialing modes.
  Enum: PREDICTIVE, PROGRESSIVE, TCPA, POWER
dialingPriority (int): Method to set the dialing priority of the running outbound campaign by assigning a priority to each campaign. The default for all campaigns is 3; the range is 1 to 99. To enable this feature, see campaignsSettings.
dialingRatio (int): Method to set the dialing priority of the running outbound campaign by using a ratio (1 to 99). The default is 50. To enable this feature, see campaignsSettings.
distributionAlgorithm (distributionAlgorithm): Method used by the ACD to transfer calls to agents.
  Enum: LongestReadyTime, LongestReadyTimeExcludeMC, RoundRobin, MinCallsHandled, MinHandleTime
distributionTimeFrame (distributionTimeFrame): Time intervals used by distributionAlgorithm.
limitPreviewTime (boolean): For campaigns in the preview mode, use as follows: True: Dial contact number after maxPreviewTime. False: Allow agents to preview the contact number for an unlimited time.
maxDroppedCallsPercentage (float): Maximum allowed percentage of dropped calls. Use when monitorDroppedCalls is set to true.
maxPreviewTime (timer): Duration until expiration of the preview time.
maxQueueTime (timer): Maximum time allowed for calls in a queue.
monitorDroppedCalls (boolean): Whether to keep track of the dropped call percentage of the campaign. True: Keep track of the dropped calls for the last 30 days or since the last reset. False: Do not keep track of the dropped calls.
previewDialImmediately (boolean): For outbound campaigns in preview mode, use as follows: True: Automatically dial the number without waiting for an action from the agent. False: Do not dial the number automatically.
useTelemarketingMaxQueTimeEq1 (boolean): Whether to enable maximum queue time for telemarketing in campaigns to one second.
analyzeLevel (int): Voice detection level for an answering machine. The values range from 0 (fast detection) to 11 (accurate detection).
CRMRedialTimeout (timer): Minimum time before redialing a contact record after all numbers for the contact record have been dialed or skipped. The default is 10 minutes.
dnisAsAni (boolean): When transferring calls to third parties, whether to override the default DNIS of the domain by using the contact’s phone number (ANI) as the DNIS (caller ID). True: Override the default DNIS. False: Do not override the default DNIS.
enableListDialingRatios (boolean): Whether to use list dialing ratios, which enable multiple lists to be dialed at specified frequencies. True: Enable dialing ratios. False: Do not enable dialing ratios.
listDialingMode (listDialingMode): Describes the list dialing mode.
  Enum: VERTICAL_DIALING, LIST_PENETRATION, EXTENDED_STRATEGY
noOutOfNumbersAlert (boolean): When an outbound campaign runs out of numbers to dial, whether to turn off notification messages to administrators and supervisors that the campaign is no longer dialing because the lists are complete. True: Turn off notification messages. False: Do not turn off notification messages.
stateDialingRule (campaignStateDialingRule): How dialing rule options are used in the campaign.
timeZoneAssignment (campaignTimeZoneAssignment): How time zone are assigned the campaign.
autoRecord (boolean): Whether to record all calls of the campaign. True: Record all calls. False: Do not record all calls.
callWrapup (campaignCallWrapup): Details for the work time after the call.
  agentNotReady (boolean): Whether to automatically place agents who reach a call timeout in a Not Ready state. True: Set agents to Not Ready state. False: Do not set agents to Not Ready state.
  dispostionName (string): Name of disposition automatically set for the call if the timeout is reached.
  enabled (boolean): Whether to limit the wrap-up time of agents. True: Limit the wrap-up time. False: Do not limit the wrap-up time.
  reasonCodeName (string): Not Ready reason code for agents who are automatically placed in Not Ready state after reaching the timeout.
  timeout (timer): Time limit for agents in wrap-up mode.
ftpHost (string): Host name of the FTP server.
ftpPassword (string): Password of the FTP server.
ftpUser (string): User name for the FTP server.
recordingNameAsSid (boolean): For FTP transfer, whether to use the session ID as the recording name. True: Use the session ID as recording name. False: Do not use the session ID as recording name.
useFtp (boolean): Whether to use FTP to transfer recordings. True: Use FTP to transfer recordings False: Do not use FTP to transfer recordings.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignsCreateOutboundSample)
			return nil
		}
		req := soap.NewRequest("createOutboundCampaign")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("campaign", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Deletes a campaign.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsGetAutodialCmd = &cobra.Command{
	Use:   "get-autodial",
	Short: "Returns the attributes of an autodial campaign.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getAutodialCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsGetDnisListCmd = &cobra.Command{
	Use:   "get-dnis-list",
	Short: "Returns the list of DNIS associated with a campaign.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getCampaignDNISList")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsListCmd = &cobra.Command{
	Use:   "list",
	Short: "Returns a list of campaigns whose names match a string pattern. If no name is specified, all the existing campaigns i...",
	Long:  `Returns a list of campaigns whose names match a string pattern. If no name is specified, all the existing campaigns in the domain are returned.

Body file schema (campaignType):
Enum: OUTBOUND, AUTODIAL, INBOUND`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignsListSample)
			return nil
		}
		req := soap.NewRequest("getCampaigns")
		flagCampaignNamePattern, _ := cmd.Flags().GetString("campaign-name-pattern")
		req.SetParam("campaignNamePattern", flagCampaignNamePattern)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("campaignType", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsGetAllDnisCmd = &cobra.Command{
	Use:   "get-all-dnis",
	Short: "Returns the list of DNIS for the domain.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getDNISList")
		flagSelectUnassigned, _ := cmd.Flags().GetBool("select-unassigned")
		if flagSelectUnassigned {
			req.SetParam("selectUnassigned", "true")
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsGetInboundCmd = &cobra.Command{
	Use:   "get-inbound",
	Short: "Returns the attributes of an inbound campaign.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getInboundCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsGetListsCmd = &cobra.Command{
	Use:   "get-lists",
	Short: "Returns the attributes of the dialing lists associated with an outbound campaign.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getListsForCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsGetOutboundCmd = &cobra.Command{
	Use:   "get-outbound",
	Short: "Returns the attributes of an outbound campaign.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getOutboundCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsModifyAutodialCmd = &cobra.Command{
	Use:   "modify-autodial",
	Short: "Updates attributes of an autodial campaign.",
	Long:  `Updates attributes of an autodial campaign.

Body file schema (autodialCampaign):
agentAvailability (agentAvailability): Types of agent states considered available. Autodial campaigns dial only agents that are available to process calls. If omitted, the list is dialed continuously regardless of agent availability.
  Enum: ReadyToReceiveCalls, ReadyToReceiveCallsOrBusy, LoggedIn
agentSkillName (string): Numbers dialed only if agents with the specified skill are available. If empty when dialIfAgentsAvailable=True, agent availability is for any skill. When modifyAutodialCampaign specifies agentSkillName=null, the value remains.
defaultIvrSchedule (ivrScriptSchedule): Schedule of the IVR script that processes call flow. Required for inbound and autodial calls.
  name (string): Name of the IVR schedule.
  scriptName (string): Name of the IVR script.
  scriptParameters (scriptParameterValue[]): Parameters of a foreign script module used in the IVR script.
dialIfAgentsAvailable (boolean): Whether to dial numbers only if agents with agentSkillName are available. True: Dial only if agents are available in the skill group. False: Dial regardless of agent availability in the skill group.
maxNumOfLines (int): Maximum number of outbound phone lines dedicated to the campaign.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignsModifyAutodialSample)
			return nil
		}
		req := soap.NewRequest("modifyAutodialCampaign")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("campaign", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsModifyListsCmd = &cobra.Command{
	Use:   "modify-lists",
	Short: "Updates the lists and attributes of dialing lists associated with an outbound campaign.",
	Long:  `Updates the lists and attributes of dialing lists associated with an outbound campaign.

Body file schema (listState):
campaignName (string): Name of campaign to which the list is associated.
dialingPriority (int): Dialing priority for the list In the campaign.
dialingRatio (int): Dialing ratio for this list compared to other lists associated with the same campaign.
listName (string): Name of list.
priority (int): Dialing priority of a list in a campaign. A list with a lower priority number is dialed first.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignsModifyListsSample)
			return nil
		}
		req := soap.NewRequest("modifyCampaignLists")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("lists", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsModifyInboundCmd = &cobra.Command{
	Use:   "modify-inbound",
	Short: "Updates the attributes of an inbound campaign.",
	Long:  `Updates the attributes of an inbound campaign.

Body file schema (inboundCampaign):
inboundCampaign (generalCampaign): Attributes of an inbound campaign.
  defaultIvrSchedule (ivrScriptSchedule): Configuration of an IVR script.
  maxNumOfLines (int): Maximum number of simultaneous calls.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignsModifyInboundSample)
			return nil
		}
		req := soap.NewRequest("modifyInboundCampaign")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("campaign", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsModifyOutboundCmd = &cobra.Command{
	Use:   "modify-outbound",
	Short: "Updates the attributes of an outbound campaign.",
	Long:  `Updates the attributes of an outbound campaign.

Body file schema (outboundCampaign):
actionOnAnswerMachine (campaignDialingAction): Action to take when the answering machine is detected.
  actionArgument (string): Name of prompt or IVR script to execute when a campaign-related event occurs. It is ignored when action type is DROP_CALL.
  actionType (campaignDialingActionType): Action to take when a specific event occurs.
  maxWaitTime (timer): Maximum waiting time for action on answering machine.
actionOnQueueExpiration (campaignDialingAction): Action to take when the maximum queue time expires, which occurs when no agent is available to take a call.
  actionArgument (string): Name of prompt or IVR script to execute when a campaign-related event occurs. It is ignored when action type is DROP_CALL.
  actionType (campaignDialingActionType): Action to take when a specific event occurs.
  maxWaitTime (timer): Maximum waiting time for action on answering machine.
callAnalysisMode (callAnalysisMode): Types of attempts when a call is answered.
  Enum: NO_ANALYSIS, FAX_ONLY, FAX_AND_ANSWERING_MACHINE
callsAgentRatio (double): For campaigns in the power mode, count of phone numbers dialed for an agent ready for a new call.
dialNumberOnTimeout (boolean): For campaigns in the preview mode, use as follows: True: Dial number when preview time expires. False: Set agent to Not Ready state.
dialingMode (campaignDialingMode): Types of dialing modes.
  Enum: PREDICTIVE, PROGRESSIVE, TCPA, POWER
dialingPriority (int): Method to set the dialing priority of the running outbound campaign by assigning a priority to each campaign. The default for all campaigns is 3; the range is 1 to 99. To enable this feature, see campaignsSettings.
dialingRatio (int): Method to set the dialing priority of the running outbound campaign by using a ratio (1 to 99). The default is 50. To enable this feature, see campaignsSettings.
distributionAlgorithm (distributionAlgorithm): Method used by the ACD to transfer calls to agents.
  Enum: LongestReadyTime, LongestReadyTimeExcludeMC, RoundRobin, MinCallsHandled, MinHandleTime
distributionTimeFrame (distributionTimeFrame): Time intervals used by distributionAlgorithm.
limitPreviewTime (boolean): For campaigns in the preview mode, use as follows: True: Dial contact number after maxPreviewTime. False: Allow agents to preview the contact number for an unlimited time.
maxDroppedCallsPercentage (float): Maximum allowed percentage of dropped calls. Use when monitorDroppedCalls is set to true.
maxPreviewTime (timer): Duration until expiration of the preview time.
maxQueueTime (timer): Maximum time allowed for calls in a queue.
monitorDroppedCalls (boolean): Whether to keep track of the dropped call percentage of the campaign. True: Keep track of the dropped calls for the last 30 days or since the last reset. False: Do not keep track of the dropped calls.
previewDialImmediately (boolean): For outbound campaigns in preview mode, use as follows: True: Automatically dial the number without waiting for an action from the agent. False: Do not dial the number automatically.
useTelemarketingMaxQueTimeEq1 (boolean): Whether to enable maximum queue time for telemarketing in campaigns to one second.
analyzeLevel (int): Voice detection level for an answering machine. The values range from 0 (fast detection) to 11 (accurate detection).
CRMRedialTimeout (timer): Minimum time before redialing a contact record after all numbers for the contact record have been dialed or skipped. The default is 10 minutes.
dnisAsAni (boolean): When transferring calls to third parties, whether to override the default DNIS of the domain by using the contact’s phone number (ANI) as the DNIS (caller ID). True: Override the default DNIS. False: Do not override the default DNIS.
enableListDialingRatios (boolean): Whether to use list dialing ratios, which enable multiple lists to be dialed at specified frequencies. True: Enable dialing ratios. False: Do not enable dialing ratios.
listDialingMode (listDialingMode): Describes the list dialing mode.
  Enum: VERTICAL_DIALING, LIST_PENETRATION, EXTENDED_STRATEGY
noOutOfNumbersAlert (boolean): When an outbound campaign runs out of numbers to dial, whether to turn off notification messages to administrators and supervisors that the campaign is no longer dialing because the lists are complete. True: Turn off notification messages. False: Do not turn off notification messages.
stateDialingRule (campaignStateDialingRule): How dialing rule options are used in the campaign.
timeZoneAssignment (campaignTimeZoneAssignment): How time zone are assigned the campaign.
autoRecord (boolean): Whether to record all calls of the campaign. True: Record all calls. False: Do not record all calls.
callWrapup (campaignCallWrapup): Details for the work time after the call.
  agentNotReady (boolean): Whether to automatically place agents who reach a call timeout in a Not Ready state. True: Set agents to Not Ready state. False: Do not set agents to Not Ready state.
  dispostionName (string): Name of disposition automatically set for the call if the timeout is reached.
  enabled (boolean): Whether to limit the wrap-up time of agents. True: Limit the wrap-up time. False: Do not limit the wrap-up time.
  reasonCodeName (string): Not Ready reason code for agents who are automatically placed in Not Ready state after reaching the timeout.
  timeout (timer): Time limit for agents in wrap-up mode.
ftpHost (string): Host name of the FTP server.
ftpPassword (string): Password of the FTP server.
ftpUser (string): User name for the FTP server.
recordingNameAsSid (boolean): For FTP transfer, whether to use the session ID as the recording name. True: Use the session ID as recording name. False: Do not use the session ID as recording name.
useFtp (boolean): Whether to use FTP to transfer recordings. True: Use FTP to transfer recordings False: Do not use FTP to transfer recordings.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignsModifyOutboundSample)
			return nil
		}
		req := soap.NewRequest("modifyOutboundCampaign")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("campaign", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsRemoveDnisCmd = &cobra.Command{
	Use:   "remove-dnis",
	Short: "Removes a list of DNIS from a campaign. When calls are received at that number after it has been removed from a campa...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("removeDNISFromCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		flagDNISList, _ := cmd.Flags().GetStringSlice("dnislist")
		for _, v := range flagDNISList {
			req.SetParam("DNISList", v)
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsRemoveDispositionsCmd = &cobra.Command{
	Use:   "remove-dispositions",
	Short: "Deleted the dispositions from a campaign.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("removeDispositionsFromCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		flagDispositions, _ := cmd.Flags().GetStringSlice("dispositions")
		for _, v := range flagDispositions {
			req.SetParam("dispositions", v)
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsRemoveListsCmd = &cobra.Command{
	Use:   "remove-lists",
	Short: "Removes dialing lists from an outbound campaign.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("removeListsFromCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		flagLists, _ := cmd.Flags().GetStringSlice("lists")
		for _, v := range flagLists {
			req.SetParam("lists", v)
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsRemoveSkillsCmd = &cobra.Command{
	Use:   "remove-skills",
	Short: "Removes skills from an outbound campaign.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("removeSkillsFromCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		flagSkills, _ := cmd.Flags().GetStringSlice("skills")
		for _, v := range flagSkills {
			req.SetParam("skills", v)
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsRenameCmd = &cobra.Command{
	Use:   "rename",
	Short: "Renames a campaign.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("renameCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		flagCampaignNewName, _ := cmd.Flags().GetString("campaign-new-name")
		req.SetParam("campaignNewName", flagCampaignNewName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsSetDefaultIvrScheduleCmd = &cobra.Command{
	Use:   "set-default-ivr-schedule",
	Short: "Assigns a default IVR script to a campaign.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("setDefaultIVRSchedule")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		flagScriptName, _ := cmd.Flags().GetString("script-name")
		req.SetParam("scriptName", flagScriptName)
		flagIsVisualModeEnabled, _ := cmd.Flags().GetBool("is-visual-mode-enabled")
		if flagIsVisualModeEnabled {
			req.SetParam("isVisualModeEnabled", "true")
		}
		flagIsChatEnabled, _ := cmd.Flags().GetBool("is-chat-enabled")
		if flagIsChatEnabled {
			req.SetParam("isChatEnabled", "true")
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsAsyncUpdateDispositionsCmd = &cobra.Command{
	Use:   "async-update-dispositions",
	Short: "`Version 9.5` Updates campaign dispositions asynchronously. Use this method to update the disposition of a small numb...",
	Long:  `'Version 9.5' Updates campaign dispositions asynchronously. Use this method to update the disposition of a small number of records. The method returns an 'importIdentifier' object that you can use to query the import status and result. To check the status of the update, use the response identifier in the request of 'getDispositionsImportResult'.

Body file schema (dispositionsUpdateSettings):
commonDispositionValue (string): Disposition value when the same disposition is assigned to all records in the list.
dispositionColumnNumber (int): Column number for the disposition value of a record. The column is created when not assigning the same disposition for all records in the list. Column numbers with a range of [1, 256] for the disposition value of a record. The column is created when not assigning the same disposition for all records in the list.
dispositionsUpdateMode (dispositionsUpdateMode): Describes how dispositions are updated.
  UPDATE_ALL (string): Update disposition for all records that match the key.
  UPDATE_IF_SOLE_CRM_MATCH (string): Update disposition if only one record matches the key. Otherwise, request for update is denied.
updateToCommonDisposition (boolean): For all records, whether to use the disposition value specified in commonDispositionValue. True: Use commonDispositionValue. False: Do not use commonDispositionValue.
warnIfNoCrmMatchFound (boolean): Whether to add a warning in the import transaction report when records do not match a CRM record. True: Warn when no CRM match exists. False: Do not warn when no CRM match exists.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignsAsyncUpdateDispositionsSample)
			return nil
		}
		req := soap.NewRequest("asyncUpdateCampaignDispositions")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("dispositionsUpdateSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsForceStopCmd = &cobra.Command{
	Use:   "force-stop",
	Short: "Stops a campaign, which immediately disconnects all active calls.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("forceStopCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsGetStateCmd = &cobra.Command{
	Use:   "get-state",
	Short: "Returns the state of a campaign and track changes in the state of a campaign by using long polling. The method return...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getCampaignState")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		flagWaitUntilChange, _ := cmd.Flags().GetString("wait-until-change")
		req.SetParam("waitUntilChange", flagWaitUntilChange)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsGetStrategiesCmd = &cobra.Command{
	Use:   "get-strategies",
	Short: "Version 4 Returns a list of strategies for the specified campaign.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getCampaignStrategies")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsGetDispositionsImportResultCmd = &cobra.Command{
	Use:   "get-dispositions-import-result",
	Short: "Returns details about the imported dispositions.",
	Long:  `Returns details about the imported dispositions.

Body file schema (importIdentifier):
identifier (string): Identifier used to check on the status and outcome of a data import operation.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignsGetDispositionsImportResultSample)
			return nil
		}
		req := soap.NewRequest("getDispositionsImportResult")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("identifier", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsResetCmd = &cobra.Command{
	Use:   "reset",
	Short: "Resets the campaign to redial every number, except for numbers on the Do-Not-Call list.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("resetCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsResetDispositionsCmd = &cobra.Command{
	Use:   "reset-dispositions",
	Short: "Resets the dispositions of the campaign list records that match the dispositions. Calls that occurred during the date...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("resetCampaignDispositions")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		flagAfter, _ := cmd.Flags().GetString("after")
		req.SetParam("after", flagAfter)
		flagBefore, _ := cmd.Flags().GetString("before")
		req.SetParam("before", flagBefore)
		flagDispositions, _ := cmd.Flags().GetStringSlice("dispositions")
		for _, v := range flagDispositions {
			req.SetParam("dispositions", v)
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsResetListPositionCmd = &cobra.Command{
	Use:   "reset-list-position",
	Short: "Resets to the beginning the dialing lists position of an outbound campaign. By default, the dialer attempts to dial a...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("resetListPosition")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsSetStrategiesCmd = &cobra.Command{
	Use:   "set-strategies",
	Short: "Version 4 Updates the strategies for the specified campaign.",
	Long:  `Version 4 Updates the strategies for the specified campaign.

Body file schema (campaignStrategies):
strategies (campaignStrategy[]): List of all strategies in your domain.
  description (string): Optional* (except when modifying Default Strategy)
  enabled (boolean): No
  filter (campaignStrategyFilter): No
  name (string): Yes
  schedule (campaignStrategyPeriod): Yes*
  startAfterTimeMins (long (xs:long)): No`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignsSetStrategiesSample)
			return nil
		}
		req := soap.NewRequest("setCampaignStrategies")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("campaignStrategies", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsStartCmd = &cobra.Command{
	Use:   "start",
	Short: "Starts a campaign.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("startCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsStopCmd = &cobra.Command{
	Use:   "stop",
	Short: "Stops a campaign.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("stopCampaign")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsUpdateDispositionsCmd = &cobra.Command{
	Use:   "update-dispositions",
	Short: "Updates batches of disposition values in a campaign. Records are passed as a two-dimensional array (collection of str...",
	Long:  `Updates batches of disposition values in a campaign. Records are passed as a two-dimensional array (collection of strings). Sets or resets a disposition for the specified records. Each request can contain up to 50,000 records. To check the status of the update, use the response identifier in the request of getDispositionsImportResult.

Body file schema (dispositionsUpdateSettings):
commonDispositionValue (string): Disposition value when the same disposition is assigned to all records in the list.
dispositionColumnNumber (int): Column number for the disposition value of a record. The column is created when not assigning the same disposition for all records in the list. Column numbers with a range of [1, 256] for the disposition value of a record. The column is created when not assigning the same disposition for all records in the list.
dispositionsUpdateMode (dispositionsUpdateMode): Describes how dispositions are updated.
  UPDATE_ALL (string): Update disposition for all records that match the key.
  UPDATE_IF_SOLE_CRM_MATCH (string): Update disposition if only one record matches the key. Otherwise, request for update is denied.
updateToCommonDisposition (boolean): For all records, whether to use the disposition value specified in commonDispositionValue. True: Use commonDispositionValue. False: Do not use commonDispositionValue.
warnIfNoCrmMatchFound (boolean): Whether to add a warning in the import transaction report when records do not match a CRM record. True: Warn when no CRM match exists. False: Do not warn when no CRM match exists.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignsUpdateDispositionsSample)
			return nil
		}
		req := soap.NewRequest("updateDispositions")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("DispositionsUpdateSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsUpdateDispositionsCsvCmd = &cobra.Command{
	Use:   "update-dispositions-csv",
	Short: "Updates batches of disposition values in a campaign. Records are passed as a string of comma-separated values. The me...",
	Long:  `Updates batches of disposition values in a campaign. Records are passed as a string of comma-separated values. The method returns an importIdentifier that you can use to query import state and import result. To check the status of the update, use the response identifier in the request of getDispositionsImportResult.

Body file schema (dispositionsUpdateSettings):
commonDispositionValue (string): Disposition value when the same disposition is assigned to all records in the list.
dispositionColumnNumber (int): Column number for the disposition value of a record. The column is created when not assigning the same disposition for all records in the list. Column numbers with a range of [1, 256] for the disposition value of a record. The column is created when not assigning the same disposition for all records in the list.
dispositionsUpdateMode (dispositionsUpdateMode): Describes how dispositions are updated.
  UPDATE_ALL (string): Update disposition for all records that match the key.
  UPDATE_IF_SOLE_CRM_MATCH (string): Update disposition if only one record matches the key. Otherwise, request for update is denied.
updateToCommonDisposition (boolean): For all records, whether to use the disposition value specified in commonDispositionValue. True: Use commonDispositionValue. False: Do not use commonDispositionValue.
warnIfNoCrmMatchFound (boolean): Whether to add a warning in the import transaction report when records do not match a CRM record. True: Warn when no CRM match exists. False: Do not warn when no CRM match exists.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignsUpdateDispositionsCsvSample)
			return nil
		}
		req := soap.NewRequest("updateDispositionsCsv")
		flagCampaignName, _ := cmd.Flags().GetString("campaign-name")
		req.SetParam("campaignName", flagCampaignName)
		flagCsvData, _ := cmd.Flags().GetString("csv-data")
		req.SetParam("csvData", flagCsvData)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("DispositionsUpdateSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignsUpdateDispositionsFtpCmd = &cobra.Command{
	Use:   "update-dispositions-ftp",
	Short: "Updates batches of disposition values in a campaign, based on data contained in a file obtained from an FTP server.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("updateDispositionsFtp")
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(CampaignsCmd)
	CampaignsCmd.AddCommand(CampaignsAddDnisCmd)
	CampaignsAddDnisCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsAddDnisCmd.Flags().StringSlice("dnislist", nil, "List of numbers to add to the campaign.")
	CampaignsCmd.AddCommand(CampaignsAddDispositionsCmd)
	CampaignsAddDispositionsCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsAddDispositionsCmd.Flags().Bool("is-skip-preview-disposition", false, "For campaigns running in preview mode, whether the dispositions that are added should be used as ...")
	CampaignsAddDispositionsCmd.Flags().StringSlice("dispositions", nil, "List of dispositions to add to the campaign.")
	CampaignsCmd.AddCommand(CampaignsAddListsCmd)
	CampaignsAddListsCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsAddListsCmd.Flags().String("body-file", "", "JSON file for lists parameter")
	CampaignsAddListsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignsCmd.AddCommand(CampaignsAddSkillsCmd)
	CampaignsAddSkillsCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsAddSkillsCmd.Flags().StringSlice("skills", nil, "List of skills to add to the campaign.")
	CampaignsCmd.AddCommand(CampaignsCreateAutodialCmd)
	CampaignsCreateAutodialCmd.Flags().String("body-file", "", "JSON file for campaign parameter")
	CampaignsCreateAutodialCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignsCmd.AddCommand(CampaignsCreateInboundCmd)
	CampaignsCreateInboundCmd.Flags().String("body-file", "", "JSON file for campaign parameter")
	CampaignsCreateInboundCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignsCmd.AddCommand(CampaignsCreateOutboundCmd)
	CampaignsCreateOutboundCmd.Flags().String("body-file", "", "JSON file for campaign parameter")
	CampaignsCreateOutboundCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignsCmd.AddCommand(CampaignsDeleteCmd)
	CampaignsDeleteCmd.Flags().String("campaign-name", "", "Name of the campaign.")
	CampaignsCmd.AddCommand(CampaignsGetAutodialCmd)
	CampaignsGetAutodialCmd.Flags().String("campaign-name", "", "Name of the campaign.")
	CampaignsCmd.AddCommand(CampaignsGetDnisListCmd)
	CampaignsGetDnisListCmd.Flags().String("campaign-name", "", "Name of the campaign.")
	CampaignsCmd.AddCommand(CampaignsListCmd)
	CampaignsListCmd.Flags().String("campaign-name-pattern", ".*", "Name of the campaign or regular expression that matches several campaign names. For example, for ...")
	CampaignsListCmd.Flags().String("body-file", "", "JSON file for campaignType parameter")
	CampaignsListCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignsCmd.AddCommand(CampaignsGetAllDnisCmd)
	CampaignsGetAllDnisCmd.Flags().Bool("select-unassigned", false, "Whether to return the list of DNIS unassigned to a campaign: True: the list is returned. False: a...")
	CampaignsCmd.AddCommand(CampaignsGetInboundCmd)
	CampaignsGetInboundCmd.Flags().String("campaign-name", "", "Name of the campaign.")
	CampaignsCmd.AddCommand(CampaignsGetListsCmd)
	CampaignsGetListsCmd.Flags().String("campaign-name", "", "Name of the outbound campaign.")
	CampaignsCmd.AddCommand(CampaignsGetOutboundCmd)
	CampaignsGetOutboundCmd.Flags().String("campaign-name", "", "Name of the outbound campaign.")
	CampaignsCmd.AddCommand(CampaignsModifyAutodialCmd)
	CampaignsModifyAutodialCmd.Flags().String("body-file", "", "JSON file for campaign parameter")
	CampaignsModifyAutodialCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignsCmd.AddCommand(CampaignsModifyListsCmd)
	CampaignsModifyListsCmd.Flags().String("campaign-name", "", "Name of the outbound campaign.")
	CampaignsModifyListsCmd.Flags().String("body-file", "", "JSON file for lists parameter")
	CampaignsModifyListsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignsCmd.AddCommand(CampaignsModifyInboundCmd)
	CampaignsModifyInboundCmd.Flags().String("body-file", "", "JSON file for campaign parameter")
	CampaignsModifyInboundCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignsCmd.AddCommand(CampaignsModifyOutboundCmd)
	CampaignsModifyOutboundCmd.Flags().String("body-file", "", "JSON file for campaign parameter")
	CampaignsModifyOutboundCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignsCmd.AddCommand(CampaignsRemoveDnisCmd)
	CampaignsRemoveDnisCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsRemoveDnisCmd.Flags().StringSlice("dnislist", nil, "List of DNIS to remove from this campaign.")
	CampaignsCmd.AddCommand(CampaignsRemoveDispositionsCmd)
	CampaignsRemoveDispositionsCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsRemoveDispositionsCmd.Flags().StringSlice("dispositions", nil, "List of dispositions to remove from this campaign.")
	CampaignsCmd.AddCommand(CampaignsRemoveListsCmd)
	CampaignsRemoveListsCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsRemoveListsCmd.Flags().StringSlice("lists", nil, "List of dialing lists to remove from this campaign.")
	CampaignsCmd.AddCommand(CampaignsRemoveSkillsCmd)
	CampaignsRemoveSkillsCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsRemoveSkillsCmd.Flags().StringSlice("skills", nil, "List of skills to remove from this campaign.")
	CampaignsCmd.AddCommand(CampaignsRenameCmd)
	CampaignsRenameCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsRenameCmd.Flags().String("campaign-new-name", "", "New name of campaign.")
	CampaignsCmd.AddCommand(CampaignsSetDefaultIvrScheduleCmd)
	CampaignsSetDefaultIvrScheduleCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsSetDefaultIvrScheduleCmd.Flags().String("script-name", "", "Name of the script.")
	CampaignsSetDefaultIvrScheduleCmd.Flags().Bool("is-visual-mode-enabled", false, "Whether Visual IVR is enabled in the campaign schedule.")
	CampaignsSetDefaultIvrScheduleCmd.Flags().Bool("is-chat-enabled", false, "Whether chat is enabled in the campaign schedule.")
	CampaignsCmd.AddCommand(CampaignsAsyncUpdateDispositionsCmd)
	CampaignsAsyncUpdateDispositionsCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsAsyncUpdateDispositionsCmd.Flags().String("body-file", "", "JSON file for dispositionsUpdateSettings parameter")
	CampaignsAsyncUpdateDispositionsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignsCmd.AddCommand(CampaignsForceStopCmd)
	CampaignsForceStopCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsCmd.AddCommand(CampaignsGetStateCmd)
	CampaignsGetStateCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsGetStateCmd.Flags().String("wait-until-change", "", "Optional duration in seconds to wait for changes. If omitted, the response is returned immediately.")
	CampaignsCmd.AddCommand(CampaignsGetStrategiesCmd)
	CampaignsGetStrategiesCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsCmd.AddCommand(CampaignsGetDispositionsImportResultCmd)
	CampaignsGetDispositionsImportResultCmd.Flags().String("body-file", "", "JSON file for identifier parameter")
	CampaignsGetDispositionsImportResultCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignsCmd.AddCommand(CampaignsResetCmd)
	CampaignsResetCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsCmd.AddCommand(CampaignsResetDispositionsCmd)
	CampaignsResetDispositionsCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsResetDispositionsCmd.Flags().String("after", "", "Start time of the call interval. The start time is not included in the interval.")
	CampaignsResetDispositionsCmd.Flags().String("before", "", "End time of the call interval. The end time is not included in the interval.")
	CampaignsResetDispositionsCmd.Flags().StringSlice("dispositions", nil, "List of dispositions to reset.")
	CampaignsCmd.AddCommand(CampaignsResetListPositionCmd)
	CampaignsResetListPositionCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsCmd.AddCommand(CampaignsSetStrategiesCmd)
	CampaignsSetStrategiesCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsSetStrategiesCmd.Flags().String("body-file", "", "JSON file for campaignStrategies parameter")
	CampaignsSetStrategiesCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignsCmd.AddCommand(CampaignsStartCmd)
	CampaignsStartCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsCmd.AddCommand(CampaignsStopCmd)
	CampaignsStopCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsCmd.AddCommand(CampaignsUpdateDispositionsCmd)
	CampaignsUpdateDispositionsCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsUpdateDispositionsCmd.Flags().String("body-file", "", "JSON file for DispositionsUpdateSettings parameter")
	CampaignsUpdateDispositionsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignsCmd.AddCommand(CampaignsUpdateDispositionsCsvCmd)
	CampaignsUpdateDispositionsCsvCmd.Flags().String("campaign-name", "", "Name of campaign.")
	CampaignsUpdateDispositionsCsvCmd.Flags().String("csv-data", "", "List of dispositions to be imported in CSV format.")
	CampaignsUpdateDispositionsCsvCmd.Flags().String("body-file", "", "JSON file for DispositionsUpdateSettings parameter")
	CampaignsUpdateDispositionsCsvCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignsCmd.AddCommand(CampaignsUpdateDispositionsFtpCmd)
}
