// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var CampaignProfilesCmd = &cobra.Command{
	Use:   "campaign-profiles",
	Short: "Manage campaign profiles",
}

var CampaignProfilesCreateSample = `{
  "ANI": "example",
  "description": "example",
  "dialingSchedule": {
    "dialASAPSortOrder": "LIFO",
    "dialASAPTimeout": 0,
    "dialASAPTimeoutPeriod": {},
    "dialingOrder": "PrimaryAlt1Alt2",
    "dialingSchedules": [
      {
        "BASIC": "example",
        "ADVANCED": "example"
      }
    ],
    "includeNumbers": [
      "Primary"
    ]
  },
  "dialingTimeout": 0,
  "initialCallPriority": 0,
  "maxCharges": 0,
  "name": "example",
  "numberOfAttempts": 0
}`

var CampaignProfilesModifySample = `{
  "ANI": "example",
  "description": "example",
  "dialingSchedule": {
    "dialASAPSortOrder": "LIFO",
    "dialASAPTimeout": 0,
    "dialASAPTimeoutPeriod": {},
    "dialingOrder": "PrimaryAlt1Alt2",
    "dialingSchedules": [
      {
        "BASIC": "example",
        "ADVANCED": "example"
      }
    ],
    "includeNumbers": [
      "Primary"
    ]
  },
  "dialingTimeout": 0,
  "initialCallPriority": 0,
  "maxCharges": 0,
  "name": "example",
  "numberOfAttempts": 0
}`

var CampaignProfilesModifyCrmCriteriaSample = `{
  "expression": "example",
  "type": "All"
}`

var CampaignProfilesModifyDispositionsSample = `{
  "count": 0,
  "dispositions": [
    "example"
  ]
}`

var CampaignProfilesModifyFilterOrderSample = `{
  "descending": false,
  "fieldname": "example",
  "rank": 0
}`

var CampaignProfilesCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Creates a campaign profile.",
	Long:  `Creates a campaign profile.

Body file schema (campaignProfileInfo):
ANI (string): ANI to send with outbound call.
description (string): Description of the profile.
dialingSchedule (campaignDialingSchedule): Order and time for dialing the numbers in a record.
  dialASAPSortOrder (dialSortOrder): Order for dialing numbers in the ASAP queue.
  dialASAPTimeout (int): Duration before records that are not dialed are removed from the ASAP queue and are treated as normal records.
  dialASAPTimeoutPeriod (timePeriod): Unit that specifies the dial ASAP time-out.
  dialingOrder (campaignDialingOrder): Dialing order when contact records have multiple phone numbers.
  dialingSchedules (campaignNumberSchedule[]): Time ranges used to call each of the three possible number associated with a campaign.
  includeNumbers (campaignDialNumber[]): Whether to call each of the three numbers in the campaign associated with the profile.
dialingTimeout (int): Time to wait before disconnecting an unanswered call and logging it as No Answer. The default is 17 seconds.
initialCallPriority (int): Priority initially assigned to inbound and outbound calls on a scale of 1 to 100. Inbound calls have a default priority of 60. Calls with a higher priority are answered first, regardless of their time in a queue. To force calls from a campaign to be answered before those from other campaigns, increase the priority by 1.
maxCharges (int): Applies to inbound and outbound calls. Maximum dollar amount for long distance charges. The campaign stops automatically when this amount is reached. Zero means no limit.
name (string): Name of campaign profile.
numberOfAttempts (int): For outbound campaigns, number of dialing attempts for phone numbers in a list record, including redials due to disposition settings.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignProfilesCreateSample)
			return nil
		}
		req := soap.NewRequest("createCampaignProfile")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("campaignProfile", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignProfilesDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Deletes a campaign profile.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteCampaignProfile")
		flagProfileName, _ := cmd.Flags().GetString("profile-name")
		req.SetParam("profileName", flagProfileName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignProfilesGetDispositionsCmd = &cobra.Command{
	Use:   "get-dispositions",
	Short: "Returns information about the dispositions of a campaign profile.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getCampaignProfileDispositions")
		flagProfileName, _ := cmd.Flags().GetString("profile-name")
		req.SetParam("profileName", flagProfileName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignProfilesGetFilterCmd = &cobra.Command{
	Use:   "get-filter",
	Short: "Returns information about the filter of a campaign profile.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getCampaignProfileFilter")
		flagProfileName, _ := cmd.Flags().GetString("profile-name")
		req.SetParam("profileName", flagProfileName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignProfilesListCmd = &cobra.Command{
	Use:   "list",
	Short: "Returns information about campaign profiles that match a pattern.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getCampaignProfiles")
		flagNamePattern, _ := cmd.Flags().GetString("name-pattern")
		req.SetParam("namePattern", flagNamePattern)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignProfilesModifyCmd = &cobra.Command{
	Use:   "modify",
	Short: "Updates a campaign profile.",
	Long:  `Updates a campaign profile.

Body file schema (campaignProfileInfo):
ANI (string): ANI to send with outbound call.
description (string): Description of the profile.
dialingSchedule (campaignDialingSchedule): Order and time for dialing the numbers in a record.
  dialASAPSortOrder (dialSortOrder): Order for dialing numbers in the ASAP queue.
  dialASAPTimeout (int): Duration before records that are not dialed are removed from the ASAP queue and are treated as normal records.
  dialASAPTimeoutPeriod (timePeriod): Unit that specifies the dial ASAP time-out.
  dialingOrder (campaignDialingOrder): Dialing order when contact records have multiple phone numbers.
  dialingSchedules (campaignNumberSchedule[]): Time ranges used to call each of the three possible number associated with a campaign.
  includeNumbers (campaignDialNumber[]): Whether to call each of the three numbers in the campaign associated with the profile.
dialingTimeout (int): Time to wait before disconnecting an unanswered call and logging it as No Answer. The default is 17 seconds.
initialCallPriority (int): Priority initially assigned to inbound and outbound calls on a scale of 1 to 100. Inbound calls have a default priority of 60. Calls with a higher priority are answered first, regardless of their time in a queue. To force calls from a campaign to be answered before those from other campaigns, increase the priority by 1.
maxCharges (int): Applies to inbound and outbound calls. Maximum dollar amount for long distance charges. The campaign stops automatically when this amount is reached. Zero means no limit.
name (string): Name of campaign profile.
numberOfAttempts (int): For outbound campaigns, number of dialing attempts for phone numbers in a list record, including redials due to disposition settings.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignProfilesModifySample)
			return nil
		}
		req := soap.NewRequest("modifyCampaignProfile")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("campaignProfile", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignProfilesModifyCrmCriteriaCmd = &cobra.Command{
	Use:   "modify-crm-criteria",
	Short: "Updates the CRM filters of a campaign profile.",
	Long:  `Updates the CRM filters of a campaign profile.

Body file schema (crmCriteriaGrouping):
expression (string): Expression for the group of filters if crmCriteriaGroupingType=Custom. The supported operators are AND, OR, NOT. Example: (1 AND 2 AND 3) OR (4 AND 5 AND 6 AND 7)
type (crmCriteriaGroupingType): Possible types of filters.
  Enum: All, Any, Custom`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignProfilesModifyCrmCriteriaSample)
			return nil
		}
		req := soap.NewRequest("modifyCampaignProfileCrmCriteria")
		flagProfileName, _ := cmd.Flags().GetString("profile-name")
		req.SetParam("profileName", flagProfileName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("grouping", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignProfilesModifyDispositionsCmd = &cobra.Command{
	Use:   "modify-dispositions",
	Short: "Updates the disposition count limits for a campaign. If a campaign with this profile reaches the maximum count for a ...",
	Long:  `Updates the disposition count limits for a campaign. If a campaign with this profile reaches the maximum count for a disposition, the campaign stops automatically.

Body file schema (dispositionCount):
count (int): Limit of the disposition.
dispositions (string[]): List of the dispositions to which this limit applies.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignProfilesModifyDispositionsSample)
			return nil
		}
		req := soap.NewRequest("modifyCampaignProfileDispositions")
		flagProfileName, _ := cmd.Flags().GetString("profile-name")
		req.SetParam("profileName", flagProfileName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("addDispositionCounts", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var CampaignProfilesModifyFilterOrderCmd = &cobra.Command{
	Use:   "modify-filter-order",
	Short: "Updates the criteria by which to dial the records of a campaign profile.",
	Long:  `Updates the criteria by which to dial the records of a campaign profile.

Body file schema (orderByField):
descending (boolean): Whether fields are in descending or ascending order. True: Fields are in descending order. False: Fields are in ascending order.
fieldname (string): Contact field to sort.
rank (int): Sorting priority for the values.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(CampaignProfilesModifyFilterOrderSample)
			return nil
		}
		req := soap.NewRequest("modifyCampaignProfileFilterOrder")
		flagCampaignProfile, _ := cmd.Flags().GetString("campaign-profile")
		req.SetParam("campaignProfile", flagCampaignProfile)
		flagRemoveOrderByField, _ := cmd.Flags().GetStringSlice("remove-order-by-field")
		for _, v := range flagRemoveOrderByField {
			req.SetParam("removeOrderByField", v)
		}
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("addOrderByField", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(CampaignProfilesCmd)
	CampaignProfilesCmd.AddCommand(CampaignProfilesCreateCmd)
	CampaignProfilesCreateCmd.Flags().String("body-file", "", "JSON file for campaignProfile parameter")
	CampaignProfilesCreateCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignProfilesCmd.AddCommand(CampaignProfilesDeleteCmd)
	CampaignProfilesDeleteCmd.Flags().String("profile-name", "", "Name of campaign profile.")
	CampaignProfilesCmd.AddCommand(CampaignProfilesGetDispositionsCmd)
	CampaignProfilesGetDispositionsCmd.Flags().String("profile-name", "", "Name of campaign profile.")
	CampaignProfilesCmd.AddCommand(CampaignProfilesGetFilterCmd)
	CampaignProfilesGetFilterCmd.Flags().String("profile-name", "", "Name of campaign profile.")
	CampaignProfilesCmd.AddCommand(CampaignProfilesListCmd)
	CampaignProfilesListCmd.Flags().String("name-pattern", ".*", "Name of campaign profile or regular expression. If omitted, all profiles are returned.")
	CampaignProfilesCmd.AddCommand(CampaignProfilesModifyCmd)
	CampaignProfilesModifyCmd.Flags().String("body-file", "", "JSON file for campaignProfile parameter")
	CampaignProfilesModifyCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignProfilesCmd.AddCommand(CampaignProfilesModifyCrmCriteriaCmd)
	CampaignProfilesModifyCrmCriteriaCmd.Flags().String("profile-name", "", "Name of campaign profile.")
	CampaignProfilesModifyCrmCriteriaCmd.Flags().String("body-file", "", "JSON file for grouping parameter")
	CampaignProfilesModifyCrmCriteriaCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignProfilesCmd.AddCommand(CampaignProfilesModifyDispositionsCmd)
	CampaignProfilesModifyDispositionsCmd.Flags().String("profile-name", "", "Name of campaign profile.")
	CampaignProfilesModifyDispositionsCmd.Flags().String("body-file", "", "JSON file for addDispositionCounts parameter")
	CampaignProfilesModifyDispositionsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	CampaignProfilesCmd.AddCommand(CampaignProfilesModifyFilterOrderCmd)
	CampaignProfilesModifyFilterOrderCmd.Flags().String("campaign-profile", "", "Name of campaign profile.")
	CampaignProfilesModifyFilterOrderCmd.Flags().StringSlice("remove-order-by-field", nil, "Name of the contact field to remove from the filter order.")
	CampaignProfilesModifyFilterOrderCmd.Flags().String("body-file", "", "JSON file for addOrderByField parameter")
	CampaignProfilesModifyFilterOrderCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
}
