// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var ContactsCmd = &cobra.Command{
	Use:   "contacts",
	Short: "Manage contacts and contact fields",
}

var ContactsCreateFieldSample = `{
  "displayAs": "Short",
  "mapTo": "LastAgent",
  "name": "example",
  "restrictions": [
    {
      "type": "MinValue",
      "value": "example"
    }
  ],
  "system": false,
  "type": "STRING"
}`

var ContactsModifyFieldSample = `{
  "displayAs": "Short",
  "mapTo": "LastAgent",
  "name": "example",
  "restrictions": [
    {
      "type": "MinValue",
      "value": "example"
    }
  ],
  "system": false,
  "type": "STRING"
}`

var ContactsAsyncUpdateSample = `{
  "basicImportSettings": {},
  "crmAddMode": {
    "ADD_NEW": "example",
    "DONT_ADD": "example"
  },
  "crmUpdateMode": "UPDATE_FIRST"
}`

var ContactsDeleteSample = `{
  "crmDeleteMode": "DELETE_ALL"
}`

var ContactsDeleteCsvSample = `{
  "crmDeleteMode": "DELETE_ALL"
}`

var ContactsDeleteFtpSample = `{
  "crmDeleteMode": "DELETE_ALL"
}`

var ContactsGetRecordsSample = `{
  "contactIdField": "example",
  "criteria": [
    {
      "field": "example",
      "value": "example"
    }
  ]
}`

var ContactsImportStatusSample = `{
  "identifier": "example"
}`

var ContactsUpdateSample = `{
  "basicImportSettings": {},
  "crmAddMode": {
    "ADD_NEW": "example",
    "DONT_ADD": "example"
  },
  "crmUpdateMode": "UPDATE_FIRST"
}`

var ContactsUpdateCsvSample = `{
  "basicImportSettings": {},
  "crmAddMode": {
    "ADD_NEW": "example",
    "DONT_ADD": "example"
  },
  "crmUpdateMode": "UPDATE_FIRST"
}`

var ContactsUpdateFtpSample = `{
  "basicImportSettings": {},
  "crmAddMode": {
    "ADD_NEW": "example",
    "DONT_ADD": "example"
  },
  "crmUpdateMode": "UPDATE_FIRST"
}`

var ContactsUpdateCrmRecordSample = `{
  "basicImportSettings": {},
  "crmAddMode": {
    "ADD_NEW": "example",
    "DONT_ADD": "example"
  },
  "crmUpdateMode": "UPDATE_FIRST"
}`

var ContactsCreateFieldCmd = &cobra.Command{
	Use:   "create-field",
	Short: "Creates custom contact fields. When creating contact fields, campaigns must not be running.",
	Long:  `Creates custom contact fields. When creating contact fields, campaigns must not be running.

Body file schema (contactField):
displayAs (contactFieldDisplay): Display options for the data in the Agent desktop.
  Enum: Short, Long, Invisible
mapTo (contactFieldMapping): Map of the system information into the field. The field is updated when a disposition is set.
  Enum: LastAgent, LastDisposition, LastSystemDisposition, LastAgentDisposition, LastDispositionDateTime, LastSystemDispositionDateTime, LastAgentDispositionDateTime, LastAttemptedNumber, LastAttemptedNumberN1N2N3, LastCampaign, AttemptsForLastCampaign, LastList, CreatedDateTime, LastModifiedDateTime
name (string): Name of the contact field.
restrictions (contactFieldRestriction[]): Restrictions imposed on the data that can be stored in this field.
  type (contactFieldRestrictionType): One of the restriction types.
  value (string): Value of the restriction, such as $ if the restriction type is CurrencyType.
system (boolean): Whether this field is set by the system or an agent. True: Field set by system. False: Field set by agent.
type (contactFieldType): Type of data stored in this field.
  Enum: STRING, NUMBER, DATE, TIME, DATE_TIME, CURRENCY, BOOLEAN, PERCENT, EMAIL, URL, PHONE, TIME_PERIOD`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ContactsCreateFieldSample)
			return nil
		}
		req := soap.NewRequest("createContactField")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("field", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ContactsDeleteFieldCmd = &cobra.Command{
	Use:   "delete-field",
	Short: "Deletes a contact field. When deleting contact fields, campaigns must not be running.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteContactField")
		flagFieldName, _ := cmd.Flags().GetString("field-name")
		req.SetParam("fieldName", flagFieldName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ContactsGetFieldsCmd = &cobra.Command{
	Use:   "get-fields",
	Short: "Returns the configuration of contact fields.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getContactFields")
		flagNamePattern, _ := cmd.Flags().GetString("name-pattern")
		req.SetParam("namePattern", flagNamePattern)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ContactsModifyFieldCmd = &cobra.Command{
	Use:   "modify-field",
	Short: "Updates a contact field. When modifying contact fields, campaigns must not be running.",
	Long:  `Updates a contact field. When modifying contact fields, campaigns must not be running.

Body file schema (contactField):
displayAs (contactFieldDisplay): Display options for the data in the Agent desktop.
  Enum: Short, Long, Invisible
mapTo (contactFieldMapping): Map of the system information into the field. The field is updated when a disposition is set.
  Enum: LastAgent, LastDisposition, LastSystemDisposition, LastAgentDisposition, LastDispositionDateTime, LastSystemDispositionDateTime, LastAgentDispositionDateTime, LastAttemptedNumber, LastAttemptedNumberN1N2N3, LastCampaign, AttemptsForLastCampaign, LastList, CreatedDateTime, LastModifiedDateTime
name (string): Name of the contact field.
restrictions (contactFieldRestriction[]): Restrictions imposed on the data that can be stored in this field.
  type (contactFieldRestrictionType): One of the restriction types.
  value (string): Value of the restriction, such as $ if the restriction type is CurrencyType.
system (boolean): Whether this field is set by the system or an agent. True: Field set by system. False: Field set by agent.
type (contactFieldType): Type of data stored in this field.
  Enum: STRING, NUMBER, DATE, TIME, DATE_TIME, CURRENCY, BOOLEAN, PERCENT, EMAIL, URL, PHONE, TIME_PERIOD`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ContactsModifyFieldSample)
			return nil
		}
		req := soap.NewRequest("modifyContactField")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("field", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ContactsAsyncUpdateCmd = &cobra.Command{
	Use:   "async-update",
	Short: "Updates up to 100 records in the contact database. To check the status of the update, use the response identifier in ...",
	Long:  `Updates up to 100 records in the contact database. To check the status of the update, use the response identifier in the request of 'getCrmImportResult'.

Body file schema (crmUpdateSettings):
basicImportSettings (crmUpdateSettings): Detailed information about the settings. See section on basicImportSettings.
  (circular reference to crmUpdateSettings)
crmAddMode (crmAddMode): Describes how to add a contact record.
  ADD_NEW (string): Contact records are created in the contact database and are added to the dialing list.
  DONT_ADD (string): Records are added to the dialing list but no records are created in the contact database.
crmUpdateMode (crmUpdateMode): Specifies how to update an existing contact record.Important: The UPDATE_ALL value of the crmUpdateMode parameter is not supported for the asyncAddrecordsToList and asyncUpdateCrmrecords methods. You cannot use the UPDATE_ALL mode to update all the fields of a contact record at once when using these methods.
  Enum: UPDATE_FIRST, UPDATE_ALL, UPDATE_SOLE_MATCHES, DONT_UPDATE`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ContactsAsyncUpdateSample)
			return nil
		}
		req := soap.NewRequest("asyncUpdateCrmRecords")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("crmUpdateSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ContactsDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Deletes batches from the contact database based on the specified import settings. Records are passed as a two-dimensi...",
	Long:  `Deletes batches from the contact database based on the specified import settings. Records are passed as a two-dimensional string array. To check the status of the update, use the response identifier in the request of 'getCrmImportResult'. Because this batch method affects the performance of the dialer and uses significant database resources, use this method only during off-peak periods. To delete single records while an outbound campaign is running, use 'deleteRecordFromList' instead. To delete up to 100 records, use 'asyncDeleteRecordsFromList'. If you require a larger batch, contact your Five9 representative.

Body file schema (crmDeleteSettings):
crmDeleteMode (crmDeleteMode): Information about the deletion settings.
  Enum: DELETE_ALL, DELETE_SOLE_MATCHES, DELETE_EXCEPT_FIRST`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ContactsDeleteSample)
			return nil
		}
		req := soap.NewRequest("deleteFromContacts")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("crmDeleteSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ContactsDeleteCsvCmd = &cobra.Command{
	Use:   "delete-csv",
	Short: "Deletes batches of records from the contact database based on the specified import settings. Records are passed as a ...",
	Long:  `Deletes batches of records from the contact database based on the specified import settings. Records are passed as a two-dimensional string array. To check the status of the update, use the response identifier in the request of 'getCrmImportResult'. Because this batch method affects the performance of the dialer and uses significant database resources, use this method only during off-peak periods. To delete single records while an outbound campaign is running, use 'deleteRecordFromList' instead. To delete up to 100 records, use 'asyncDeleteRecordsFromList'. If you require a larger batch, contact your Five9 representative.

Body file schema (crmDeleteSettings):
crmDeleteMode (crmDeleteMode): Information about the deletion settings.
  Enum: DELETE_ALL, DELETE_SOLE_MATCHES, DELETE_EXCEPT_FIRST`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ContactsDeleteCsvSample)
			return nil
		}
		req := soap.NewRequest("deleteFromContactsCsv")
		flagCsvData, _ := cmd.Flags().GetString("csv-data")
		req.SetParam("csvData", flagCsvData)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("crmDeleteSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ContactsDeleteFtpCmd = &cobra.Command{
	Use:   "delete-ftp",
	Short: "Deletes batches of records by FTP. For more information about the format of the file obtained from the FTP server, re...",
	Long:  `Deletes batches of records by FTP. For more information about the format of the file obtained from the FTP server, refer to the Administrator’s Guide. Because this batch method affects the performance of the dialer and uses significant database resources, use this method only during off-peak periods. To delete single records while an outbound campaign is running, use 'deleteRecordFromList' instead. To delete up to 100 records, use 'asyncDeleteRecordsFromList'. If you require a larger batch, contact your Five9 representative.

Body file schema (crmDeleteSettings):
crmDeleteMode (crmDeleteMode): Information about the deletion settings.
  Enum: DELETE_ALL, DELETE_SOLE_MATCHES, DELETE_EXCEPT_FIRST`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ContactsDeleteFtpSample)
			return nil
		}
		req := soap.NewRequest("deleteFromContactsFtp")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("DeleteSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ContactsGetRecordsCmd = &cobra.Command{
	Use:   "get-records",
	Short: "Returns one or more records from the contact database.",
	Long:  `Returns one or more records from the contact database.

Body file schema (crmLookupCriteria):
contactIdField (string): Field name of the response that contains the ID of the contact, which is the internal database identifier in the VCC.
criteria (crmFieldCriterion[]): List of contact database criteria.
  field (string): Field in the contact database.
  value (string): Value in the contact database.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ContactsGetRecordsSample)
			return nil
		}
		req := soap.NewRequest("getContactRecords")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("lookupCriteria", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ContactsImportStatusCmd = &cobra.Command{
	Use:   "import-status",
	Short: "Returns the result of the contact records import process.",
	Long:  `Returns the result of the contact records import process.

Body file schema (importIdentifier):
identifier (string): Identifier used to check on the status and outcome of a data import operation.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ContactsImportStatusSample)
			return nil
		}
		req := soap.NewRequest("getCrmImportResult")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("identifier", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ContactsUpdateCmd = &cobra.Command{
	Use:   "update",
	Short: "Updates batches of records in the contact database. Records are passed as a two-dimensional string array. To check th...",
	Long:  `Updates batches of records in the contact database. Records are passed as a two-dimensional string array. To check the status of the update, use the response identifier in the request of 'getCrmImportResult'. In the process of creating and updating records, with multiple files/loads at once, if the same record is being deleted before the list is completed, there is a possibility that the deletion will occur before the update. This can result in the record being recreated with the new updates. Because this batch method affects the performance of the dialer and uses significant database resources, use this method only during off-peak periods. To update single records while an outbound campaign is running, use 'updateCrmRecord' instead. To update up to 100 records, use 'asyncUpdateCrmRecords'.

Body file schema (crmUpdateSettings):
basicImportSettings (crmUpdateSettings): Detailed information about the settings. See section on basicImportSettings.
  (circular reference to crmUpdateSettings)
crmAddMode (crmAddMode): Describes how to add a contact record.
  ADD_NEW (string): Contact records are created in the contact database and are added to the dialing list.
  DONT_ADD (string): Records are added to the dialing list but no records are created in the contact database.
crmUpdateMode (crmUpdateMode): Specifies how to update an existing contact record.Important: The UPDATE_ALL value of the crmUpdateMode parameter is not supported for the asyncAddrecordsToList and asyncUpdateCrmrecords methods. You cannot use the UPDATE_ALL mode to update all the fields of a contact record at once when using these methods.
  Enum: UPDATE_FIRST, UPDATE_ALL, UPDATE_SOLE_MATCHES, DONT_UPDATE`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ContactsUpdateSample)
			return nil
		}
		req := soap.NewRequest("updateContacts")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("crmUpdateSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ContactsUpdateCsvCmd = &cobra.Command{
	Use:   "update-csv",
	Short: "Updates batches of records in CSV format. Records are passed as a two-dimensional string array. To check the status o...",
	Long:  `Updates batches of records in CSV format. Records are passed as a two-dimensional string array. To check the status of the update, use the response identifier in the request of 'getCrmImportResult'. Because this batch method affects the performance of the dialer and uses significant database resources, use this method only during off-peak periods. To update single records while an outbound campaign is running, use 'updateCrmRecord' instead. To update up to 100 records, use 'asyncUpdateCrmRecords'.

Body file schema (crmUpdateSettings):
basicImportSettings (crmUpdateSettings): Detailed information about the settings. See section on basicImportSettings.
  (circular reference to crmUpdateSettings)
crmAddMode (crmAddMode): Describes how to add a contact record.
  ADD_NEW (string): Contact records are created in the contact database and are added to the dialing list.
  DONT_ADD (string): Records are added to the dialing list but no records are created in the contact database.
crmUpdateMode (crmUpdateMode): Specifies how to update an existing contact record.Important: The UPDATE_ALL value of the crmUpdateMode parameter is not supported for the asyncAddrecordsToList and asyncUpdateCrmrecords methods. You cannot use the UPDATE_ALL mode to update all the fields of a contact record at once when using these methods.
  Enum: UPDATE_FIRST, UPDATE_ALL, UPDATE_SOLE_MATCHES, DONT_UPDATE`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ContactsUpdateCsvSample)
			return nil
		}
		req := soap.NewRequest("updateContactsCsv")
		flagCsvData, _ := cmd.Flags().GetString("csv-data")
		req.SetParam("csvData", flagCsvData)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("crmUpdateSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ContactsUpdateFtpCmd = &cobra.Command{
	Use:   "update-ftp",
	Short: "Imports batches of records by using FTP. For information about the format of the file obtained from the FTP server, s...",
	Long:  `Imports batches of records by using FTP. For information about the format of the file obtained from the FTP server, see the Administrator’s Guide. Because this batch method affects the performance of the dialer and uses significant database resources, use this method only during off-peak periods. To update single records while an outbound campaign is running, use 'updateCrmRecord' instead. To update up to 100 records, use 'asyncUpdateCrmRecords'.

Body file schema (crmUpdateSettings):
basicImportSettings (crmUpdateSettings): Detailed information about the settings. See section on basicImportSettings.
  (circular reference to crmUpdateSettings)
crmAddMode (crmAddMode): Describes how to add a contact record.
  ADD_NEW (string): Contact records are created in the contact database and are added to the dialing list.
  DONT_ADD (string): Records are added to the dialing list but no records are created in the contact database.
crmUpdateMode (crmUpdateMode): Specifies how to update an existing contact record.Important: The UPDATE_ALL value of the crmUpdateMode parameter is not supported for the asyncAddrecordsToList and asyncUpdateCrmrecords methods. You cannot use the UPDATE_ALL mode to update all the fields of a contact record at once when using these methods.
  Enum: UPDATE_FIRST, UPDATE_ALL, UPDATE_SOLE_MATCHES, DONT_UPDATE`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ContactsUpdateFtpSample)
			return nil
		}
		req := soap.NewRequest("updateContactsFtp")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("updateSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ContactsUpdateCrmRecordCmd = &cobra.Command{
	Use:   "update-crm-record",
	Short: "Updates single records.",
	Long:  `Updates single records.

Body file schema (crmUpdateSettings):
basicImportSettings (crmUpdateSettings): Detailed information about the settings. See section on basicImportSettings.
  (circular reference to crmUpdateSettings)
crmAddMode (crmAddMode): Describes how to add a contact record.
  ADD_NEW (string): Contact records are created in the contact database and are added to the dialing list.
  DONT_ADD (string): Records are added to the dialing list but no records are created in the contact database.
crmUpdateMode (crmUpdateMode): Specifies how to update an existing contact record.Important: The UPDATE_ALL value of the crmUpdateMode parameter is not supported for the asyncAddrecordsToList and asyncUpdateCrmrecords methods. You cannot use the UPDATE_ALL mode to update all the fields of a contact record at once when using these methods.
  Enum: UPDATE_FIRST, UPDATE_ALL, UPDATE_SOLE_MATCHES, DONT_UPDATE`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ContactsUpdateCrmRecordSample)
			return nil
		}
		req := soap.NewRequest("updateCrmRecord")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("crmUpdateSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(ContactsCmd)
	ContactsCmd.AddCommand(ContactsCreateFieldCmd)
	ContactsCreateFieldCmd.Flags().String("body-file", "", "JSON file for field parameter")
	ContactsCreateFieldCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ContactsCmd.AddCommand(ContactsDeleteFieldCmd)
	ContactsDeleteFieldCmd.Flags().String("field-name", "", "Name of contact field.")
	ContactsCmd.AddCommand(ContactsGetFieldsCmd)
	ContactsGetFieldsCmd.Flags().String("name-pattern", ".*", "Regular expression. If omitted, all objects are returned.")
	ContactsCmd.AddCommand(ContactsModifyFieldCmd)
	ContactsModifyFieldCmd.Flags().String("body-file", "", "JSON file for field parameter")
	ContactsModifyFieldCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ContactsCmd.AddCommand(ContactsAsyncUpdateCmd)
	ContactsAsyncUpdateCmd.Flags().String("body-file", "", "JSON file for crmUpdateSettings parameter")
	ContactsAsyncUpdateCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ContactsCmd.AddCommand(ContactsDeleteCmd)
	ContactsDeleteCmd.Flags().String("body-file", "", "JSON file for crmDeleteSettings parameter")
	ContactsDeleteCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ContactsCmd.AddCommand(ContactsDeleteCsvCmd)
	ContactsDeleteCsvCmd.Flags().String("csv-data", "", "List of CSV-formatted records to delete.")
	ContactsDeleteCsvCmd.Flags().String("body-file", "", "JSON file for crmDeleteSettings parameter")
	ContactsDeleteCsvCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ContactsCmd.AddCommand(ContactsDeleteFtpCmd)
	ContactsDeleteFtpCmd.Flags().String("body-file", "", "JSON file for DeleteSettings parameter")
	ContactsDeleteFtpCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ContactsCmd.AddCommand(ContactsGetRecordsCmd)
	ContactsGetRecordsCmd.Flags().String("body-file", "", "JSON file for lookupCriteria parameter")
	ContactsGetRecordsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ContactsCmd.AddCommand(ContactsImportStatusCmd)
	ContactsImportStatusCmd.Flags().String("body-file", "", "JSON file for identifier parameter")
	ContactsImportStatusCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ContactsCmd.AddCommand(ContactsUpdateCmd)
	ContactsUpdateCmd.Flags().String("body-file", "", "JSON file for crmUpdateSettings parameter")
	ContactsUpdateCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ContactsCmd.AddCommand(ContactsUpdateCsvCmd)
	ContactsUpdateCsvCmd.Flags().String("csv-data", "", "Data in CSV format to be imported to the Contacts database.")
	ContactsUpdateCsvCmd.Flags().String("body-file", "", "JSON file for crmUpdateSettings parameter")
	ContactsUpdateCsvCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ContactsCmd.AddCommand(ContactsUpdateFtpCmd)
	ContactsUpdateFtpCmd.Flags().String("body-file", "", "JSON file for updateSettings parameter")
	ContactsUpdateFtpCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ContactsCmd.AddCommand(ContactsUpdateCrmRecordCmd)
	ContactsUpdateCrmRecordCmd.Flags().String("body-file", "", "JSON file for crmUpdateSettings parameter")
	ContactsUpdateCrmRecordCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
}
