// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var DialingRulesCmd = &cobra.Command{
	Use:   "dialing-rules",
	Short: "Manage dialing rules",
}

var DialingRulesSetSample = `{
  "applyToManualCalls": false,
  "contactText": "example",
  "dateRange": {
    "daysOfWeek": [
      {}
    ],
    "endDate": "2024-01-01T00:00:00",
    "startDate": "2024-01-01T00:00:00"
  },
  "fixedTimeZone": "example",
  "name": "example",
  "state": {},
  "timeRange": {
    "startHour": 0,
    "startMinute": 0,
    "stopHour": 0,
    "stopMinute": 0
  }
}`

var DialingRulesGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Returns details about existing dialing rules.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getDialingRules")
		flagNamePattern, _ := cmd.Flags().GetString("name-pattern")
		req.SetParam("namePattern", flagNamePattern)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var DialingRulesSetCmd = &cobra.Command{
	Use:   "set",
	Short: "Creates, modifies, or deletes dialing rules.",
	Long:  `Creates, modifies, or deletes dialing rules.

Body file schema (dialingRule):
applyToManualCalls (boolean): Whether to restrict manual calls to the dialing rule. True: Restrict manual calls. False: Do not restrict manual calls.
contactText (string): Comma-separated list of the possible entries for a state in the calling list. For example, "Alabama, AL" indicates that the state dialing rule applies to contact records that have either Alabama or AL in the state contact field. If omitted, the name and abbreviation of the state are used by default.
dateRange (dateRange): Date range when dialers do not dial numbers.
  daysOfWeek (dayOfWeek[]): Array of the days of the week.
  endDate (dateTime): Last day of the date range.
  startDate (dateTime): First day of the date range.
fixedTimeZone (string): Time zone used by the dialer to check whether a number can be called. If omitted, the time zone of the dialed number is used by default. For example, US/Pacific is used for PDT time. The names of the time zones are located in the Dialing Rules tab of Administrator Configuration.
name (string): Name of the dialing rule.
state (stateProvince): State for which to apply this rule. If omitted, the rule applies to numbers of any state. If specified, the rule applies to the value of the state contact field.
timeRange (timeRange): Part of the day that applies to the rule. If omitted, the assumption is all day long.
  startHour (int): Beginning hour of the range, for example: 8 for 8:32AM.
  startMinute (int): Beginning minute of the range, for example: 32 for 8:32PM.
  stopHour (int): Ending hour of the range, for example: 17 for 5:00PM.
  stopMinute (int): Ending minute value of the range, for example: 0 for 5:00PM.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(DialingRulesSetSample)
			return nil
		}
		req := soap.NewRequest("setDialingRules")
		flagRemoveRules, _ := cmd.Flags().GetStringSlice("remove-rules")
		for _, v := range flagRemoveRules {
			req.SetParam("removeRules", v)
		}
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("setRules", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(DialingRulesCmd)
	DialingRulesCmd.AddCommand(DialingRulesGetCmd)
	DialingRulesGetCmd.Flags().String("name-pattern", ".*", "Optional regular expression that matches one or more dialing rules. If omitted, all objects are r...")
	DialingRulesCmd.AddCommand(DialingRulesSetCmd)
	DialingRulesSetCmd.Flags().StringSlice("remove-rules", nil, "Names of the dialing rules to delete.")
	DialingRulesSetCmd.Flags().String("body-file", "", "JSON file for setRules parameter")
	DialingRulesSetCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
}
