// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var DispositionsCmd = &cobra.Command{
	Use:   "dispositions",
	Short: "Manage dispositions",
}

var DispositionsCreateSample = `{
  "agentMustCompleteWorksheet": false,
  "agentMustConfirm": false,
  "description": "example",
  "name": "example",
  "resetAttemptsCounter": false,
  "sendEmailNotification": false,
  "sendIMNotification": false,
  "trackAsFirstCallResolution": false,
  "type": "FinalDisp",
  "typeParameters": {
    "allowChangeTimer": false,
    "attempts": 0,
    "timer": "00:00:00",
    "useTimer": false
  }
}`

var DispositionsModifySample = `{
  "agentMustCompleteWorksheet": false,
  "agentMustConfirm": false,
  "description": "example",
  "name": "example",
  "resetAttemptsCounter": false,
  "sendEmailNotification": false,
  "sendIMNotification": false,
  "trackAsFirstCallResolution": false,
  "type": "FinalDisp",
  "typeParameters": {
    "allowChangeTimer": false,
    "attempts": 0,
    "timer": "00:00:00",
    "useTimer": false
  }
}`

var DispositionsCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Creates a disposition.",
	Long:  `Creates a disposition.

Body file schema (disposition):
agentMustCompleteWorksheet (boolean): Whether the agent needs to complete a worksheet before selecting a disposition. True: Worksheet required. False: Worksheet not required.
agentMustConfirm (boolean): Whether the agent is prompted to confirm the selection of the disposition. True: Agent prompted to confirm disposition. False: Agent not prompted to confirm disposition.
description (string): Description of the disposition.
name (string): Name of the disposition.
resetAttemptsCounter (boolean): Whether assigning the disposition resets the number of dialing attempts for this contact. True: Disposition resets the counter to zero. False: Disposition does not reset the counter to zero.
sendEmailNotification (boolean): Whether call details are sent as an email notification when the disposition is used by an agent. True: Send email notification. False: Do not send email notification.
sendIMNotification (boolean): Whether call details are sent as an instant message in the Five9 system when the disposition is used by an agent. True: Send instant message. False: Do not send instant message.
trackAsFirstCallResolution (boolean): Whether the call is included in the first call resolution statistics (customer’s needs addressed in the first call). Used primarily for inbound campaigns. True: Include in statistics. False: Do not include in statistics.
type (customDispositionType): Disposition type.
  Enum: FinalDisp, FinalApplyToCampaigns, AddActiveNumber, AddAndFinalize, AddAllNumbers, DoNotDial, RedialNumber
typeParameters (dispositionTypeParams): Parameters that apply to the disposition type.
  allowChangeTimer (boolean): Whether the agent can change the redial timer for this disposition. True: Agent can change redial timer. False: Agent cannot change redial timer.
  attempts (byte): Number of redial attempts.
  timer (timer): Redial timer.
  useTimer (boolean): Whether this disposition uses a redial timer. True: Use a redial timer. False: Do not use a redial timer.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(DispositionsCreateSample)
			return nil
		}
		req := soap.NewRequest("createDisposition")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("disposition", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var DispositionsGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Returns the attributes of a disposition.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getDisposition")
		flagDispositionName, _ := cmd.Flags().GetString("disposition-name")
		req.SetParam("dispositionName", flagDispositionName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var DispositionsListCmd = &cobra.Command{
	Use:   "list",
	Short: "Returns the attributes of the dispositions that match a name pattern.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getDispositions")
		flagDispositionNamePattern, _ := cmd.Flags().GetString("disposition-name-pattern")
		req.SetParam("dispositionNamePattern", flagDispositionNamePattern)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var DispositionsModifyCmd = &cobra.Command{
	Use:   "modify",
	Short: "Updates the attributes of a disposition.",
	Long:  `Updates the attributes of a disposition.

Body file schema (disposition):
agentMustCompleteWorksheet (boolean): Whether the agent needs to complete a worksheet before selecting a disposition. True: Worksheet required. False: Worksheet not required.
agentMustConfirm (boolean): Whether the agent is prompted to confirm the selection of the disposition. True: Agent prompted to confirm disposition. False: Agent not prompted to confirm disposition.
description (string): Description of the disposition.
name (string): Name of the disposition.
resetAttemptsCounter (boolean): Whether assigning the disposition resets the number of dialing attempts for this contact. True: Disposition resets the counter to zero. False: Disposition does not reset the counter to zero.
sendEmailNotification (boolean): Whether call details are sent as an email notification when the disposition is used by an agent. True: Send email notification. False: Do not send email notification.
sendIMNotification (boolean): Whether call details are sent as an instant message in the Five9 system when the disposition is used by an agent. True: Send instant message. False: Do not send instant message.
trackAsFirstCallResolution (boolean): Whether the call is included in the first call resolution statistics (customer’s needs addressed in the first call). Used primarily for inbound campaigns. True: Include in statistics. False: Do not include in statistics.
type (customDispositionType): Disposition type.
  Enum: FinalDisp, FinalApplyToCampaigns, AddActiveNumber, AddAndFinalize, AddAllNumbers, DoNotDial, RedialNumber
typeParameters (dispositionTypeParams): Parameters that apply to the disposition type.
  allowChangeTimer (boolean): Whether the agent can change the redial timer for this disposition. True: Agent can change redial timer. False: Agent cannot change redial timer.
  attempts (byte): Number of redial attempts.
  timer (timer): Redial timer.
  useTimer (boolean): Whether this disposition uses a redial timer. True: Use a redial timer. False: Do not use a redial timer.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(DispositionsModifySample)
			return nil
		}
		req := soap.NewRequest("modifyDisposition")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("disposition", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var DispositionsRemoveCmd = &cobra.Command{
	Use:   "remove",
	Short: "Deletes a disposition from the configuration.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("removeDisposition")
		flagDispositionName, _ := cmd.Flags().GetString("disposition-name")
		req.SetParam("dispositionName", flagDispositionName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var DispositionsRenameCmd = &cobra.Command{
	Use:   "rename",
	Short: "Updates a disposition.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("renameDisposition")
		flagDispositionName, _ := cmd.Flags().GetString("disposition-name")
		req.SetParam("dispositionName", flagDispositionName)
		flagDispositionNewName, _ := cmd.Flags().GetString("disposition-new-name")
		req.SetParam("dispositionNewName", flagDispositionNewName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(DispositionsCmd)
	DispositionsCmd.AddCommand(DispositionsCreateCmd)
	DispositionsCreateCmd.Flags().String("body-file", "", "JSON file for disposition parameter")
	DispositionsCreateCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	DispositionsCmd.AddCommand(DispositionsGetCmd)
	DispositionsGetCmd.Flags().String("disposition-name", "", "Name of disposition.")
	DispositionsCmd.AddCommand(DispositionsListCmd)
	DispositionsListCmd.Flags().String("disposition-name-pattern", ".*", "Name pattern to be compared to the disposition names in the domain.")
	DispositionsCmd.AddCommand(DispositionsModifyCmd)
	DispositionsModifyCmd.Flags().String("body-file", "", "JSON file for disposition parameter")
	DispositionsModifyCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	DispositionsCmd.AddCommand(DispositionsRemoveCmd)
	DispositionsRemoveCmd.Flags().String("disposition-name", "", "Name of the disposition.")
	DispositionsCmd.AddCommand(DispositionsRenameCmd)
	DispositionsRenameCmd.Flags().String("disposition-name", "", "Name of the disposition.")
	DispositionsRenameCmd.Flags().String("disposition-new-name", "", "New name of the disposition.")
}
