// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var DomainLimitsCmd = &cobra.Command{
	Use:   "domain-limits",
	Short: "View domain limits",
}

var DomainLimitsGetCallCountersCmd = &cobra.Command{
	Use:   "get-call-counters",
	Short: "Returns your domain’s request limits. No limit is set for this request. However, Five9 recommends that you do not use...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getCallCountersState")
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(DomainLimitsCmd)
	DomainLimitsCmd.AddCommand(DomainLimitsGetCallCountersCmd)
}
