// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var IvrScriptsCmd = &cobra.Command{
	Use:   "ivr-scripts",
	Short: "Manage IVR scripts",
}

var IvrScriptsModifySample = `"description"`

var IvrScriptsSetIconsSample = `{
  "largeIcon": {},
  "mediumIcon": {},
  "smallIcon": {}
}`

var IvrScriptsCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Creates an IVR script. To add details, use modifyIVRScript.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("createIVRScript")
		flagName, _ := cmd.Flags().GetString("name")
		req.SetParam("name", flagName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var IvrScriptsDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Deletes an IVR script.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteIVRScript")
		flagName, _ := cmd.Flags().GetString("name")
		req.SetParam("name", flagName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var IvrScriptsListCmd = &cobra.Command{
	Use:   "list",
	Short: "Returns information about IVR scripts.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getIVRScripts")
		flagNamePattern, _ := cmd.Flags().GetString("name-pattern")
		req.SetParam("namePattern", flagNamePattern)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var IvrScriptsGetIconsCmd = &cobra.Command{
	Use:   "get-icons",
	Short: "Version 10 Gets the icon graphics data for an IVR script.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getIvrIcons")
		flagIvrScriptName, _ := cmd.Flags().GetString("ivr-script-name")
		req.SetParam("ivrScriptName", flagIvrScriptName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var IvrScriptsGetOwnershipCmd = &cobra.Command{
	Use:   "get-ownership",
	Short: "Version 10 Gets the ownership information for an IVR script.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getIvrScriptOwnership")
		flagIvrScriptName, _ := cmd.Flags().GetString("ivr-script-name")
		req.SetParam("ivrScriptName", flagIvrScriptName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var IvrScriptsModifyCmd = &cobra.Command{
	Use:   "modify",
	Short: "Updates an IVR script.",
	Long:  `Updates an IVR script.

Body file schema (ivrScriptDef):
Enum: description, name, xmlDefinition`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(IvrScriptsModifySample)
			return nil
		}
		req := soap.NewRequest("modifyIVRScript")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("scriptDef", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var IvrScriptsRemoveIconsCmd = &cobra.Command{
	Use:   "remove-icons",
	Short: "Version 10 Removes the icon graphics data from an IVR script.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("removeIvrIcons")
		flagIvrScriptName, _ := cmd.Flags().GetString("ivr-script-name")
		req.SetParam("ivrScriptName", flagIvrScriptName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var IvrScriptsRemoveOwnershipCmd = &cobra.Command{
	Use:   "remove-ownership",
	Short: "Version 10 Removes the ownership from an IVR script.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("removeIvrScriptOwnership")
		flagIvrScriptName, _ := cmd.Flags().GetString("ivr-script-name")
		req.SetParam("ivrScriptName", flagIvrScriptName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var IvrScriptsSetIconsCmd = &cobra.Command{
	Use:   "set-icons",
	Short: "Version 10 Sets the icon graphics data for an IVR script.",
	Long:  `Version 10 Sets the icon graphics data for an IVR script.

Body file schema (ivrIcons):
largeIcon (base64Binary): Large icon binary data.
mediumIcon (base64Binary): Medium icon binary data.
smallIcon (base64Binary): Small icon binary data.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(IvrScriptsSetIconsSample)
			return nil
		}
		req := soap.NewRequest("setIvrIcons")
		flagIvrScriptName, _ := cmd.Flags().GetString("ivr-script-name")
		req.SetParam("ivrScriptName", flagIvrScriptName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("ivrIcons", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var IvrScriptsSetOwnershipCmd = &cobra.Command{
	Use:   "set-ownership",
	Short: "Version 10 Sets the ownership information for an IVR script.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("setIvrScriptOwnership")
		flagIvrScriptName, _ := cmd.Flags().GetString("ivr-script-name")
		req.SetParam("ivrScriptName", flagIvrScriptName)
		flagOthersCanCopy, _ := cmd.Flags().GetBool("others-can-copy")
		if flagOthersCanCopy {
			req.SetParam("othersCanCopy", "true")
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(IvrScriptsCmd)
	IvrScriptsCmd.AddCommand(IvrScriptsCreateCmd)
	IvrScriptsCreateCmd.Flags().String("name", "", "Name of script.")
	IvrScriptsCmd.AddCommand(IvrScriptsDeleteCmd)
	IvrScriptsDeleteCmd.Flags().String("name", "", "Name of script.")
	IvrScriptsCmd.AddCommand(IvrScriptsListCmd)
	IvrScriptsListCmd.Flags().String("name-pattern", ".*", "Regular expression for the script names. If omitted, all objects are returned.")
	IvrScriptsCmd.AddCommand(IvrScriptsGetIconsCmd)
	IvrScriptsGetIconsCmd.Flags().String("ivr-script-name", "", "Name of script.")
	IvrScriptsCmd.AddCommand(IvrScriptsGetOwnershipCmd)
	IvrScriptsGetOwnershipCmd.Flags().String("ivr-script-name", "", "Name of script.")
	IvrScriptsCmd.AddCommand(IvrScriptsModifyCmd)
	IvrScriptsModifyCmd.Flags().String("body-file", "", "JSON file for scriptDef parameter")
	IvrScriptsModifyCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	IvrScriptsCmd.AddCommand(IvrScriptsRemoveIconsCmd)
	IvrScriptsRemoveIconsCmd.Flags().String("ivr-script-name", "", "Name of script.")
	IvrScriptsCmd.AddCommand(IvrScriptsRemoveOwnershipCmd)
	IvrScriptsRemoveOwnershipCmd.Flags().String("ivr-script-name", "", "Name of script.")
	IvrScriptsCmd.AddCommand(IvrScriptsSetIconsCmd)
	IvrScriptsSetIconsCmd.Flags().String("ivr-script-name", "", "Name of script.")
	IvrScriptsSetIconsCmd.Flags().String("body-file", "", "JSON file for ivrIcons parameter")
	IvrScriptsSetIconsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	IvrScriptsCmd.AddCommand(IvrScriptsSetOwnershipCmd)
	IvrScriptsSetOwnershipCmd.Flags().String("ivr-script-name", "", "Name of script.")
	IvrScriptsSetOwnershipCmd.Flags().Bool("others-can-copy", false, "Whether other users can copy the script.")
}
