// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var ListsCmd = &cobra.Command{
	Use:   "lists",
	Short: "Manage contact lists",
}

var ListsAddRecordSample = `{
  "callNowColumnNumber": 0,
  "callNowMode": "NONE",
  "callTime": 0,
  "callTimeColumnNumber": 0,
  "cleanListBeforeUpdate": false,
  "crmAddMode": {
    "ADD_NEW": "example",
    "DONT_ADD": "example"
  },
  "crmUpdateMode": "UPDATE_FIRST",
  "listAddMode": "ADD_FIRST"
}`

var ListsAddRecordSimpleSample = `{
  "callAsap": false,
  "countryCode": "example",
  "fieldsMapping": [
    {
      "columnNumber": 0,
      "fieldName": "example",
      "key": false
    }
  ],
  "timeToCall": 0,
  "updateCRM": false
}`

var ListsAddRecordsCsvSample = `{
  "callNowColumnNumber": 0,
  "callNowMode": "NONE",
  "callTime": 0,
  "callTimeColumnNumber": 0,
  "cleanListBeforeUpdate": false,
  "crmAddMode": {
    "ADD_NEW": "example",
    "DONT_ADD": "example"
  },
  "crmUpdateMode": "UPDATE_FIRST",
  "listAddMode": "ADD_FIRST"
}`

var ListsAddRecordsFtpSample = `{
  "callNowColumnNumber": 0,
  "callNowMode": "NONE",
  "callTime": 0,
  "callTimeColumnNumber": 0,
  "cleanListBeforeUpdate": false,
  "crmAddMode": {
    "ADD_NEW": "example",
    "DONT_ADD": "example"
  },
  "crmUpdateMode": "UPDATE_FIRST",
  "listAddMode": "ADD_FIRST"
}`

var ListsAsyncAddRecordsSample = `{
  "callNowColumnNumber": 0,
  "callNowMode": "NONE",
  "callTime": 0,
  "callTimeColumnNumber": 0,
  "cleanListBeforeUpdate": false,
  "crmAddMode": {
    "ADD_NEW": "example",
    "DONT_ADD": "example"
  },
  "crmUpdateMode": "UPDATE_FIRST",
  "listAddMode": "ADD_FIRST"
}`

var ListsAsyncDeleteRecordsSample = `{
  "listDeleteMode": "DELETE_ALL"
}`

var ListsDeleteRecordsSample = `{
  "listDeleteMode": "DELETE_ALL"
}`

var ListsDeleteRecordsCsvSample = `{
  "listDeleteMode": "DELETE_ALL"
}`

var ListsDeleteRecordsFtpSample = `{
  "listDeleteMode": "DELETE_ALL"
}`

var ListsDeleteRecordSample = `{
  "listDeleteMode": "DELETE_ALL"
}`

var ListsImportStatusSample = `{
  "identifier": "example"
}`

var ListsIsImportingSample = `{
  "identifier": "example"
}`

var ListsAddNumbersToDncCmd = &cobra.Command{
	Use:   "add-numbers-to-dnc",
	Short: "Adds phone numbers to your domain’s do-not-call (DNC) list. Because these lists are typically very large, you can imp...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("addNumbersToDnc")
		flagNumbers, _ := cmd.Flags().GetStringSlice("numbers")
		for _, v := range flagNumbers {
			req.SetParam("numbers", v)
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsAddRecordCmd = &cobra.Command{
	Use:   "add-record",
	Short: "Adds a record to a list. If a corresponding record does not already exist in the contact database, a new record is ad...",
	Long:  `Adds a record to a list. If a corresponding record does not already exist in the contact database, a new record is added. Otherwise, the existing record is updated based on the options settings. To import large numbers of records, use 'addToList' or 'addToListCsv'.

Body file schema (listUpdateSettings):
callNowColumnNumber (int): Column number, starting with 1. If a record should be dialed immediately, the content of the column is 1, T, Y, and Yes. This column is not included in the fieldsMapping parameter and is not imported in the contact database. If callNowMode is also specified, only records that have a true value and apply to callNowMode are called immediately. If you do not want to add a column for each imported record, use callNowMode singly.
callNowMode (callNowMode): Whether records are dialed immediately. If callNowColumnNumber is also specified, callNowMode applies to all records with a true value in the specified column. If callNowColumnNumber is omitted, the callNowMode applies to all records imported by the request.
  Enum: NONE, NEW_CRM_ONLY, NEW_LIST_ONLY, ANY
callTime (long): When to dial the records (Epoch time in milliseconds); applies to all records in the request, except for those with a value in the timeToCallColumn; does not apply to the addToList method, which is used to process batch record transactions. The call time value is applied only if the campaign exists when the record is added to the list assigned to that campaign. However, if a campaign is created or associated with a list after the record is added to the list, calls may be dialed sooner than the specified value, depending on the size of the list, the position of the record in the list, and the other parameters assigned to the list in the campaign.
callTimeColumnNumber (int): Column that contains the times (Epoch time) to call individual records. If a record contains a valid time, this time is used instead of the callTime parameter. Does not apply to the addToList method, which is used to process batch record transactions.
cleanListBeforeUpdate (boolean): Whether all records in the list should be removed before adding new records. True: Remove records before adding new ones. False: Do not remove records before adding new ones.
crmAddMode (crmAddMode): Whether contact records should be added when a new record is inserted into a dialing list.
  ADD_NEW (string): Contact records are created in the contact database and are added to the dialing list.
  DONT_ADD (string): Records are added to the dialing list but no records are created in the contact database.
crmUpdateMode (crmUpdateMode): Whether contact records should be updated when a record is added to a dialing list.
  Enum: UPDATE_FIRST, UPDATE_ALL, UPDATE_SOLE_MATCHES, DONT_UPDATE
listAddMode (listAddMode): Describes how to update the list.
  Enum: ADD_FIRST, ADD_ALL, ADD_IF_SOLE_CRM_MATCH`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ListsAddRecordSample)
			return nil
		}
		req := soap.NewRequest("addRecordToList")
		flagListName, _ := cmd.Flags().GetString("list-name")
		req.SetParam("listName", flagListName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("listUpdateSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsAddRecordSimpleCmd = &cobra.Command{
	Use:   "add-record-simple",
	Short: "To import large numbers of records, use `addToList` or `addToListCsv`. Because `addRecordToListSimple` does not have ...",
	Long:  `To import large numbers of records, use 'addToList' or 'addToListCsv'. Because 'addRecordToListSimple' does not have a duplicate records flag, if the list record has more than two matches, the behavior is as follows: - No contact field data is updated. - No record is added to the list. - Users receive this fault: More than one record matches specified criteria. This behavior is equivalent to this: - 'crmUpdateMode = UPDATE_SOLE_MATCHES' - 'listAddMode = ADD_IF_SOLE_CRM_MATCH'

Body file schema (listUpdateSimpleSettings):
callAsap (boolean): Whether to call the contact as soon as possible.
countryCode (string): Two-letter codes defined in ISO 3166-1.
fieldsMapping (fieldEntry[]): Mapping of the column number to the field name in the contact database. Column numbers start at 0 whereas in listUpdateSettings, column numbers start at 1.
  columnNumber (int): Column numbers with a range of [1,256]. Column number in a CSV file or importData array that contains data for the associated contact field.
  fieldName (string): Name of the contact field associated with the column number.
  key (boolean): Whether the key is used to find the record in the contact database. When a record needs to be updated, the key is used to find the record to update in the contact database. For example, the key can be first_name, first_name+last_name, Number1, or a combination. When a record is added, the value of the key determines if the record already exists. If so, the values in crmAddMode, crmUpdateMode, and listAddMode determine how to handle matching records. True: Use the key. False: Do not use the key.
timeToCall (long): When to dial the records (Epoch time in milliseconds).
updateCRM (boolean): Whether to update the contact field data of an existing record: True: Changes to the value of a contact field are saved. False: Changes to the value of a contact field are not saved, but new records are inserted.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ListsAddRecordSimpleSample)
			return nil
		}
		req := soap.NewRequest("addRecordToListSimple")
		flagListName, _ := cmd.Flags().GetString("list-name")
		req.SetParam("listName", flagListName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("listUpdateSimpleSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsAddRecordsCmd = &cobra.Command{
	Use:   "add-records",
	Short: "Imports batches of list records into a list. Depending on the settings, importing records may affect the contact data...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("addToList")
		flagListName, _ := cmd.Flags().GetString("list-name")
		req.SetParam("listName", flagListName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("listUpdateSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsAddRecordsCsvCmd = &cobra.Command{
	Use:   "add-records-csv",
	Short: "Imports batches of records into a list. Depending on the import settings, contact records may be affected. Records ar...",
	Long:  `Imports batches of records into a list. Depending on the import settings, contact records may be affected. Records are passed as a string of comma-separated values. To check the status of the update, use the response identifier in the request of 'getListImportResult'. Because this batch method affects the performance of the dialer and uses significant database resources, use this method only during off-peak periods. To insert single records while an outbound campaign is running, use 'addRecordToListSimple' instead. To insert up to 100 records, use 'asyncAddRecordsToList'.

Body file schema (listUpdateSettings):
callNowColumnNumber (int): Column number, starting with 1. If a record should be dialed immediately, the content of the column is 1, T, Y, and Yes. This column is not included in the fieldsMapping parameter and is not imported in the contact database. If callNowMode is also specified, only records that have a true value and apply to callNowMode are called immediately. If you do not want to add a column for each imported record, use callNowMode singly.
callNowMode (callNowMode): Whether records are dialed immediately. If callNowColumnNumber is also specified, callNowMode applies to all records with a true value in the specified column. If callNowColumnNumber is omitted, the callNowMode applies to all records imported by the request.
  Enum: NONE, NEW_CRM_ONLY, NEW_LIST_ONLY, ANY
callTime (long): When to dial the records (Epoch time in milliseconds); applies to all records in the request, except for those with a value in the timeToCallColumn; does not apply to the addToList method, which is used to process batch record transactions. The call time value is applied only if the campaign exists when the record is added to the list assigned to that campaign. However, if a campaign is created or associated with a list after the record is added to the list, calls may be dialed sooner than the specified value, depending on the size of the list, the position of the record in the list, and the other parameters assigned to the list in the campaign.
callTimeColumnNumber (int): Column that contains the times (Epoch time) to call individual records. If a record contains a valid time, this time is used instead of the callTime parameter. Does not apply to the addToList method, which is used to process batch record transactions.
cleanListBeforeUpdate (boolean): Whether all records in the list should be removed before adding new records. True: Remove records before adding new ones. False: Do not remove records before adding new ones.
crmAddMode (crmAddMode): Whether contact records should be added when a new record is inserted into a dialing list.
  ADD_NEW (string): Contact records are created in the contact database and are added to the dialing list.
  DONT_ADD (string): Records are added to the dialing list but no records are created in the contact database.
crmUpdateMode (crmUpdateMode): Whether contact records should be updated when a record is added to a dialing list.
  Enum: UPDATE_FIRST, UPDATE_ALL, UPDATE_SOLE_MATCHES, DONT_UPDATE
listAddMode (listAddMode): Describes how to update the list.
  Enum: ADD_FIRST, ADD_ALL, ADD_IF_SOLE_CRM_MATCH`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ListsAddRecordsCsvSample)
			return nil
		}
		req := soap.NewRequest("addToListCsv")
		flagListName, _ := cmd.Flags().GetString("list-name")
		req.SetParam("listName", flagListName)
		flagCsvData, _ := cmd.Flags().GetString("csv-data")
		req.SetParam("csvData", flagCsvData)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("listUpdateSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsAddRecordsFtpCmd = &cobra.Command{
	Use:   "add-records-ftp",
	Short: "Imports by FTP a batch of list records. Depending on the settings, importing records may affect the contact database ...",
	Long:  `Imports by FTP a batch of list records. Depending on the settings, importing records may affect the contact database records. Records are passed as a string of comma-separated values. The method returns an identifier object that you can use to query the import status and result. For more information about the format of the file obtained from the FTP server, refer to the Administrator’s Guide. Because this batch method affects the performance of the dialer and uses significant database resources, use this method only during off-peak periods. To insert single records while an outbound campaign is running, use 'addRecordToListSimple' instead. To insert up to 100 records, use 'asyncAddRecordsToList'.

Body file schema (listUpdateSettings):
callNowColumnNumber (int): Column number, starting with 1. If a record should be dialed immediately, the content of the column is 1, T, Y, and Yes. This column is not included in the fieldsMapping parameter and is not imported in the contact database. If callNowMode is also specified, only records that have a true value and apply to callNowMode are called immediately. If you do not want to add a column for each imported record, use callNowMode singly.
callNowMode (callNowMode): Whether records are dialed immediately. If callNowColumnNumber is also specified, callNowMode applies to all records with a true value in the specified column. If callNowColumnNumber is omitted, the callNowMode applies to all records imported by the request.
  Enum: NONE, NEW_CRM_ONLY, NEW_LIST_ONLY, ANY
callTime (long): When to dial the records (Epoch time in milliseconds); applies to all records in the request, except for those with a value in the timeToCallColumn; does not apply to the addToList method, which is used to process batch record transactions. The call time value is applied only if the campaign exists when the record is added to the list assigned to that campaign. However, if a campaign is created or associated with a list after the record is added to the list, calls may be dialed sooner than the specified value, depending on the size of the list, the position of the record in the list, and the other parameters assigned to the list in the campaign.
callTimeColumnNumber (int): Column that contains the times (Epoch time) to call individual records. If a record contains a valid time, this time is used instead of the callTime parameter. Does not apply to the addToList method, which is used to process batch record transactions.
cleanListBeforeUpdate (boolean): Whether all records in the list should be removed before adding new records. True: Remove records before adding new ones. False: Do not remove records before adding new ones.
crmAddMode (crmAddMode): Whether contact records should be added when a new record is inserted into a dialing list.
  ADD_NEW (string): Contact records are created in the contact database and are added to the dialing list.
  DONT_ADD (string): Records are added to the dialing list but no records are created in the contact database.
crmUpdateMode (crmUpdateMode): Whether contact records should be updated when a record is added to a dialing list.
  Enum: UPDATE_FIRST, UPDATE_ALL, UPDATE_SOLE_MATCHES, DONT_UPDATE
listAddMode (listAddMode): Describes how to update the list.
  Enum: ADD_FIRST, ADD_ALL, ADD_IF_SOLE_CRM_MATCH`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ListsAddRecordsFtpSample)
			return nil
		}
		req := soap.NewRequest("addToListFtp")
		flagListName, _ := cmd.Flags().GetString("list-name")
		req.SetParam("listName", flagListName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("updateSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsAsyncAddRecordsCmd = &cobra.Command{
	Use:   "async-add-records",
	Short: "Adds up to 100 records to a list. If the records do not exist in the contact database, they are added. Otherwise, the...",
	Long:  `Adds up to 100 records to a list. If the records do not exist in the contact database, they are added. Otherwise, the existing records are updated based on the list update settings. To check the status of the update, use the response identifier in the request of getListImportResult. To insert a large number of records, use 'addToList' or 'addToListCsv'.

Body file schema (listUpdateSettings):
callNowColumnNumber (int): Column number, starting with 1. If a record should be dialed immediately, the content of the column is 1, T, Y, and Yes. This column is not included in the fieldsMapping parameter and is not imported in the contact database. If callNowMode is also specified, only records that have a true value and apply to callNowMode are called immediately. If you do not want to add a column for each imported record, use callNowMode singly.
callNowMode (callNowMode): Whether records are dialed immediately. If callNowColumnNumber is also specified, callNowMode applies to all records with a true value in the specified column. If callNowColumnNumber is omitted, the callNowMode applies to all records imported by the request.
  Enum: NONE, NEW_CRM_ONLY, NEW_LIST_ONLY, ANY
callTime (long): When to dial the records (Epoch time in milliseconds); applies to all records in the request, except for those with a value in the timeToCallColumn; does not apply to the addToList method, which is used to process batch record transactions. The call time value is applied only if the campaign exists when the record is added to the list assigned to that campaign. However, if a campaign is created or associated with a list after the record is added to the list, calls may be dialed sooner than the specified value, depending on the size of the list, the position of the record in the list, and the other parameters assigned to the list in the campaign.
callTimeColumnNumber (int): Column that contains the times (Epoch time) to call individual records. If a record contains a valid time, this time is used instead of the callTime parameter. Does not apply to the addToList method, which is used to process batch record transactions.
cleanListBeforeUpdate (boolean): Whether all records in the list should be removed before adding new records. True: Remove records before adding new ones. False: Do not remove records before adding new ones.
crmAddMode (crmAddMode): Whether contact records should be added when a new record is inserted into a dialing list.
  ADD_NEW (string): Contact records are created in the contact database and are added to the dialing list.
  DONT_ADD (string): Records are added to the dialing list but no records are created in the contact database.
crmUpdateMode (crmUpdateMode): Whether contact records should be updated when a record is added to a dialing list.
  Enum: UPDATE_FIRST, UPDATE_ALL, UPDATE_SOLE_MATCHES, DONT_UPDATE
listAddMode (listAddMode): Describes how to update the list.
  Enum: ADD_FIRST, ADD_ALL, ADD_IF_SOLE_CRM_MATCH`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ListsAsyncAddRecordsSample)
			return nil
		}
		req := soap.NewRequest("asyncAddRecordsToList")
		flagListName, _ := cmd.Flags().GetString("list-name")
		req.SetParam("listName", flagListName)
		flagResetDispositionsInCampaignsImportData, _ := cmd.Flags().GetStringSlice("reset-dispositions-in-campaigns-import-data")
		for _, v := range flagResetDispositionsInCampaignsImportData {
			req.SetParam("resetDispositionsInCampaignsImportData", v)
		}
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("listUpdateSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsAsyncDeleteRecordsCmd = &cobra.Command{
	Use:   "async-delete-records",
	Short: "Deletes multiple records from a list. Use one of the deleteFromContacts methods to delete a contact. To check the sta...",
	Long:  `Deletes multiple records from a list. Use one of the deleteFromContacts methods to delete a contact. To check the status of the update, use the response identifier in the request of 'getListImportResult'. Because this method affects the performance of the dialer, use this method only during off-peak periods. To delete a large number of records, use 'deleteFromList' or 'deleteFromListCsv' instead.

Body file schema (listDeleteSettings):
listDeleteMode (listDeleteMode): Describes how to delete dialing list and contact records.
  Enum: DELETE_ALL, DELETE_IF_SOLE_CRM_MATCH, DELETE_EXCEPT_FIRST`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ListsAsyncDeleteRecordsSample)
			return nil
		}
		req := soap.NewRequest("asyncDeleteRecordsFromList")
		flagListName, _ := cmd.Flags().GetString("list-name")
		req.SetParam("listName", flagListName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("listDeleteSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsCheckDncCmd = &cobra.Command{
	Use:   "check-dnc",
	Short: "Checks whether phone numbers are part of a DNC list. The response contains the numbers found in the DNC list.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("checkDncForNumbers")
		flagNumbers, _ := cmd.Flags().GetStringSlice("numbers")
		for _, v := range flagNumbers {
			req.SetParam("numbers", v)
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Creates a dialing list.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("createList")
		flagListName, _ := cmd.Flags().GetString("list-name")
		req.SetParam("listName", flagListName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsDeleteAllCmd = &cobra.Command{
	Use:   "delete-all",
	Short: "Deletes all records from a list. To check the status of the update, use the response identifier in the request of `ge...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteAllFromList")
		flagListName, _ := cmd.Flags().GetString("list-name")
		req.SetParam("listName", flagListName)
		flagReportEmail, _ := cmd.Flags().GetString("report-email")
		req.SetParam("reportEmail", flagReportEmail)
		flagCallbackUrl, _ := cmd.Flags().GetString("callback-url")
		req.SetParam("callbackUrl", flagCallbackUrl)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("callbackFormat", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsDeleteRecordsCmd = &cobra.Command{
	Use:   "delete-records",
	Short: "Deletes batches of records from a list. To check the status of the update, use the response identifier in the request...",
	Long:  `Deletes batches of records from a list. To check the status of the update, use the response identifier in the request of 'getListImportResult'. Because this batch method affects the performance of the dialer and uses significant database resources, use this method only during off-peak periods. To delete single records while an outbound campaign is running, use 'deleteRecordFromList' instead. To delete up to 100 records, use 'asyncDeleteRecordsFromList'. If you require a larger batch, contact your Five9 representative.

Body file schema (listDeleteSettings):
listDeleteMode (listDeleteMode): Describes how to delete dialing list and contact records.
  Enum: DELETE_ALL, DELETE_IF_SOLE_CRM_MATCH, DELETE_EXCEPT_FIRST`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ListsDeleteRecordsSample)
			return nil
		}
		req := soap.NewRequest("deleteFromList")
		flagListName, _ := cmd.Flags().GetString("list-name")
		req.SetParam("listName", flagListName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("listDeleteSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsDeleteRecordsCsvCmd = &cobra.Command{
	Use:   "delete-records-csv",
	Short: "Deletes batches of records from a list. Records are passed as a string of comma-separated values. To check the status...",
	Long:  `Deletes batches of records from a list. Records are passed as a string of comma-separated values. To check the status of the update, use the response identifier in the request of 'getListImportResult'. Because this batch method affects the performance of the dialer and uses significant database resources, use this method only during off-peak periods. To delete single records while an outbound campaign is running, use 'deleteRecordFromList' instead. To delete up to 100 records, use 'asyncDeleteRecordsFromList'. If you require a larger batch, contact your Five9 representative.

Body file schema (listDeleteSettings):
listDeleteMode (listDeleteMode): Describes how to delete dialing list and contact records.
  Enum: DELETE_ALL, DELETE_IF_SOLE_CRM_MATCH, DELETE_EXCEPT_FIRST`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ListsDeleteRecordsCsvSample)
			return nil
		}
		req := soap.NewRequest("deleteFromListCsv")
		flagListName, _ := cmd.Flags().GetString("list-name")
		req.SetParam("listName", flagListName)
		flagCsvData, _ := cmd.Flags().GetString("csv-data")
		req.SetParam("csvData", flagCsvData)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("listDeleteSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsDeleteRecordsFtpCmd = &cobra.Command{
	Use:   "delete-records-ftp",
	Short: "Removes batches of records from a list by FTP. For more information about the format of the file obtained from the FT...",
	Long:  `Removes batches of records from a list by FTP. For more information about the format of the file obtained from the FTP server, refer to the Administrator’s Guide. Because this batch method affects the performance of the dialer and uses significant database resources, use this method only during off-peak periods. To delete single records while an outbound campaign is running, use 'deleteRecordFromList' instead. To delete up to 100 records, use 'asyncDeleteRecordsFromList'. If you require a larger batch, contact your Five9 representative.

Body file schema (listDeleteSettings):
listDeleteMode (listDeleteMode): Describes how to delete dialing list and contact records.
  Enum: DELETE_ALL, DELETE_IF_SOLE_CRM_MATCH, DELETE_EXCEPT_FIRST`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ListsDeleteRecordsFtpSample)
			return nil
		}
		req := soap.NewRequest("deleteFromListFtp")
		flagListName, _ := cmd.Flags().GetString("list-name")
		req.SetParam("listName", flagListName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("deleteSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Deletes a list from the Five9  configuration. Although the list is deleted, the contact records remain in the Contact...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteList")
		flagListName, _ := cmd.Flags().GetString("list-name")
		req.SetParam("listName", flagListName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsDeleteRecordCmd = &cobra.Command{
	Use:   "delete-record",
	Short: "Deletes a record from a list. Use one of the deleteFromContacts methods to delete a contact. Because this method affe...",
	Long:  `Deletes a record from a list. Use one of the deleteFromContacts methods to delete a contact. Because this method affects the performance of the dialer, use this method only during off-peak periods. To delete a large number of records, use 'deleteFromList' or 'deleteFromListCsv' instead.

Body file schema (listDeleteSettings):
listDeleteMode (listDeleteMode): Describes how to delete dialing list and contact records.
  Enum: DELETE_ALL, DELETE_IF_SOLE_CRM_MATCH, DELETE_EXCEPT_FIRST`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ListsDeleteRecordSample)
			return nil
		}
		req := soap.NewRequest("deleteRecordFromList")
		flagListName, _ := cmd.Flags().GetString("list-name")
		req.SetParam("listName", flagListName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("listDeleteSettings", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsImportStatusCmd = &cobra.Command{
	Use:   "import-status",
	Short: "Returns the detailed outcome of a list import. The import is identified by the identifier object returned in the list...",
	Long:  `Returns the detailed outcome of a list import. The import is identified by the identifier object returned in the list import response.

Body file schema (importIdentifier):
identifier (string): Identifier used to check on the status and outcome of a data import operation.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ListsImportStatusSample)
			return nil
		}
		req := soap.NewRequest("getListImportResult")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("identifier", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsListInfoCmd = &cobra.Command{
	Use:   "list-info",
	Short: "Returns the names and sizes of all the dialing lists in a domain. The request contains the specified list name starts...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getListsInfo")
		flagListNamePattern, _ := cmd.Flags().GetString("list-name-pattern")
		req.SetParam("listNamePattern", flagListNamePattern)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsIsImportingCmd = &cobra.Command{
	Use:   "is-importing",
	Short: "Checks whether data is being imported by using the importIdentifier object returned in the list import response. To t...",
	Long:  `Checks whether data is being imported by using the importIdentifier object returned in the list import response. To track changes in the import process, use the 'waitTime' parameter (long-polling technique). The method returns the new state when it is changed or the current state after the specified 'waitTime'.

Body file schema (importIdentifier):
identifier (string): Identifier used to check on the status and outcome of a data import operation.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ListsIsImportingSample)
			return nil
		}
		req := soap.NewRequest("isImportRunning")
		flagWaitTime, _ := cmd.Flags().GetString("wait-time")
		req.SetParam("waitTime", flagWaitTime)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("identifier", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ListsRemoveNumbersFromDncCmd = &cobra.Command{
	Use:   "remove-numbers-from-dnc",
	Short: "Checks whether phone numbers are part of a DNC list. The response contains the numbers found in the DNC list. For ins...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("removeNumbersFromDnc")
		flagNumbers, _ := cmd.Flags().GetStringSlice("numbers")
		for _, v := range flagNumbers {
			req.SetParam("numbers", v)
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(ListsCmd)
	ListsCmd.AddCommand(ListsAddNumbersToDncCmd)
	ListsAddNumbersToDncCmd.Flags().StringSlice("numbers", nil, "List of numbers to add to the list.")
	ListsCmd.AddCommand(ListsAddRecordCmd)
	ListsAddRecordCmd.Flags().String("list-name", "", "Name of list.")
	ListsAddRecordCmd.Flags().String("body-file", "", "JSON file for listUpdateSettings parameter")
	ListsAddRecordCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ListsCmd.AddCommand(ListsAddRecordSimpleCmd)
	ListsAddRecordSimpleCmd.Flags().String("list-name", "", "Name of list.")
	ListsAddRecordSimpleCmd.Flags().String("body-file", "", "JSON file for listUpdateSimpleSettings parameter")
	ListsAddRecordSimpleCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ListsCmd.AddCommand(ListsAddRecordsCmd)
	ListsAddRecordsCmd.Flags().String("list-name", "", "Yes")
	ListsAddRecordsCmd.Flags().String("body-file", "", "JSON file for listUpdateSettings parameter")
	ListsAddRecordsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ListsCmd.AddCommand(ListsAddRecordsCsvCmd)
	ListsAddRecordsCsvCmd.Flags().String("list-name", "", "Name of list.")
	ListsAddRecordsCsvCmd.Flags().String("csv-data", "", "Data to import. Fields are separated by commas; records are separated by new lines.")
	ListsAddRecordsCsvCmd.Flags().String("body-file", "", "JSON file for listUpdateSettings parameter")
	ListsAddRecordsCsvCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ListsCmd.AddCommand(ListsAddRecordsFtpCmd)
	ListsAddRecordsFtpCmd.Flags().String("list-name", "", "Name of list.")
	ListsAddRecordsFtpCmd.Flags().String("body-file", "", "JSON file for updateSettings parameter")
	ListsAddRecordsFtpCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ListsCmd.AddCommand(ListsAsyncAddRecordsCmd)
	ListsAsyncAddRecordsCmd.Flags().String("list-name", "", "Name of list.")
	ListsAsyncAddRecordsCmd.Flags().StringSlice("reset-dispositions-in-campaigns-import-data", nil, "Optional list of campaign names in which to reset the dispositions.")
	ListsAsyncAddRecordsCmd.Flags().String("body-file", "", "JSON file for listUpdateSettings parameter")
	ListsAsyncAddRecordsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ListsCmd.AddCommand(ListsAsyncDeleteRecordsCmd)
	ListsAsyncDeleteRecordsCmd.Flags().String("list-name", "", "Name of list.")
	ListsAsyncDeleteRecordsCmd.Flags().String("body-file", "", "JSON file for listDeleteSettings parameter")
	ListsAsyncDeleteRecordsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ListsCmd.AddCommand(ListsCheckDncCmd)
	ListsCheckDncCmd.Flags().StringSlice("numbers", nil, "List of numbers to search in the DNC list. You may include up to 50000 phone numbers in a request.")
	ListsCmd.AddCommand(ListsCreateCmd)
	ListsCreateCmd.Flags().String("list-name", "", "Name of list.")
	ListsCmd.AddCommand(ListsDeleteAllCmd)
	ListsDeleteAllCmd.Flags().String("list-name", "", "Name of list.")
	ListsDeleteAllCmd.Flags().String("report-email", "", "Email address for the deletion report.")
	ListsDeleteAllCmd.Flags().String("callback-url", "", "URL for the HTTP callback.")
	ListsDeleteAllCmd.Flags().String("body-file", "", "JSON file for callbackFormat parameter")
	ListsDeleteAllCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ListsCmd.AddCommand(ListsDeleteRecordsCmd)
	ListsDeleteRecordsCmd.Flags().String("list-name", "", "Name of list.")
	ListsDeleteRecordsCmd.Flags().String("body-file", "", "JSON file for listDeleteSettings parameter")
	ListsDeleteRecordsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ListsCmd.AddCommand(ListsDeleteRecordsCsvCmd)
	ListsDeleteRecordsCsvCmd.Flags().String("list-name", "", "Name of list.")
	ListsDeleteRecordsCsvCmd.Flags().String("csv-data", "", "Records to remove from the list in CSV format.")
	ListsDeleteRecordsCsvCmd.Flags().String("body-file", "", "JSON file for listDeleteSettings parameter")
	ListsDeleteRecordsCsvCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ListsCmd.AddCommand(ListsDeleteRecordsFtpCmd)
	ListsDeleteRecordsFtpCmd.Flags().String("list-name", "", "Name of list.")
	ListsDeleteRecordsFtpCmd.Flags().String("body-file", "", "JSON file for deleteSettings parameter")
	ListsDeleteRecordsFtpCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ListsCmd.AddCommand(ListsDeleteCmd)
	ListsDeleteCmd.Flags().String("list-name", "", "Name of list.")
	ListsCmd.AddCommand(ListsDeleteRecordCmd)
	ListsDeleteRecordCmd.Flags().String("list-name", "", "Name of list.")
	ListsDeleteRecordCmd.Flags().String("body-file", "", "JSON file for listDeleteSettings parameter")
	ListsDeleteRecordCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ListsCmd.AddCommand(ListsImportStatusCmd)
	ListsImportStatusCmd.Flags().String("body-file", "", "JSON file for identifier parameter")
	ListsImportStatusCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ListsCmd.AddCommand(ListsListInfoCmd)
	ListsListInfoCmd.Flags().String("list-name-pattern", ".*", "Pattern that is matched to the list names in the user’s domain.")
	ListsCmd.AddCommand(ListsIsImportingCmd)
	ListsIsImportingCmd.Flags().String("wait-time", "", "Optional number of seconds to wait for changes. If not specified, This method contains the result...")
	ListsIsImportingCmd.Flags().String("body-file", "", "JSON file for identifier parameter")
	ListsIsImportingCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ListsCmd.AddCommand(ListsRemoveNumbersFromDncCmd)
	ListsRemoveNumbersFromDncCmd.Flags().StringSlice("numbers", nil, "List of numbers to remove from the DNC list.")
}
