// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var LocalesCmd = &cobra.Command{
	Use:   "locales",
	Short: "Manage locales and languages",
}

var LocalesUpdateTranslationsSample = `{
  "comment": "example",
  "objectField": {
    "i18NObjectField": "example"
  },
  "objectId": 0,
  "objectType": {
    "i18NObjectType": "example"
  },
  "value": "example"
}`

var LocalesListAvailableCmd = &cobra.Command{
	Use:   "list-available",
	Short: "`Version 9.5` Returns the list of locales for the domain.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getAvailableLocales")
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var LocalesGetTranslationsCmd = &cobra.Command{
	Use:   "get-translations",
	Short: "`Version 9.5` Returns configuration translations for the locale.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getConfigurationTranslations")
		flagLocaleName, _ := cmd.Flags().GetString("locale-name")
		req.SetParam("localeName", flagLocaleName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var LocalesGetCmd = &cobra.Command{
	Use:   "get",
	Short: "`Version 9.5` Returns the name of the locale.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getLocale")
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var LocalesSetCmd = &cobra.Command{
	Use:   "set",
	Short: "`Version 9.5` Sets the name of the locale.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("setLocale")
		flagLocaleName, _ := cmd.Flags().GetString("locale-name")
		req.SetParam("localeName", flagLocaleName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var LocalesUpdateTranslationsCmd = &cobra.Command{
	Use:   "update-translations",
	Short: "`Version 9.5` Updates the configuration translations for the locale.",
	Long:  `'Version 9.5' Updates the configuration translations for the locale.

Body file schema (adminConfigTranslation):
comment (string): Comment about the configuration.
objectField (i18NObjectField): Object field to be translated.
  i18NObjectField (string): Possible values: NAME DESCRIPTION
objectId (long): Object ID.
objectType (i18NObjectType): Object type to be translated.
  i18NObjectType (string): Possible values: CAMPAIGN CONNECTOR CONTACT_FIELD DISPOSITION FIELD_VIEW: Contact field views. REASON_CODE
value (string): Object value.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(LocalesUpdateTranslationsSample)
			return nil
		}
		req := soap.NewRequest("updateConfigurationTranslations")
		flagLocaleName, _ := cmd.Flags().GetString("locale-name")
		req.SetParam("localeName", flagLocaleName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("diffTranslations", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(LocalesCmd)
	LocalesCmd.AddCommand(LocalesListAvailableCmd)
	LocalesCmd.AddCommand(LocalesGetTranslationsCmd)
	LocalesGetTranslationsCmd.Flags().String("locale-name", "", "Name of the locale.")
	LocalesCmd.AddCommand(LocalesGetCmd)
	LocalesCmd.AddCommand(LocalesSetCmd)
	LocalesSetCmd.Flags().String("locale-name", "", "Name of the locale.")
	LocalesCmd.AddCommand(LocalesUpdateTranslationsCmd)
	LocalesUpdateTranslationsCmd.Flags().String("locale-name", "", "Name of the locale.")
	LocalesUpdateTranslationsCmd.Flags().String("body-file", "", "JSON file for diffTranslations parameter")
	LocalesUpdateTranslationsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
}
