// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var PromptsCmd = &cobra.Command{
	Use:   "prompts",
	Short: "Manage audio prompts",
}

var PromptsAddTtsSample = `{
  "description": "example",
  "languages": [
    "example"
  ],
  "name": "example",
  "type": {
    "TTSGenerated": "example",
    "PreRecorded": "example"
  }
}`

var PromptsAddWavSample = `{
  "description": "example",
  "languages": [
    "example"
  ],
  "name": "example",
  "type": {
    "TTSGenerated": "example",
    "PreRecorded": "example"
  }
}`

var PromptsAddWavInlineSample = `{
  "description": "example",
  "languages": [
    "example"
  ],
  "name": "example",
  "type": {
    "TTSGenerated": "example",
    "PreRecorded": "example"
  }
}`

var PromptsModifyTtsSample = `{
  "description": "example",
  "languages": [
    "example"
  ],
  "name": "example",
  "type": {
    "TTSGenerated": "example",
    "PreRecorded": "example"
  }
}`

var PromptsModifyWavSample = `{
  "description": "example",
  "languages": [
    "example"
  ],
  "name": "example",
  "type": {
    "TTSGenerated": "example",
    "PreRecorded": "example"
  }
}`

var PromptsModifyWavInlineSample = `{
  "description": "example",
  "languages": [
    "example"
  ],
  "name": "example",
  "type": {
    "TTSGenerated": "example",
    "PreRecorded": "example"
  }
}`

var PromptsAddTtsCmd = &cobra.Command{
	Use:   "add-tts",
	Short: "Creates a prompt and to generate an audio file with text and text-to-speech settings.",
	Long:  `Creates a prompt and to generate an audio file with text and text-to-speech settings.

Body file schema (promptInfo):
description (string): Description of the prompt.
languages (string[]): List of languages for getPrompt() or one language for the methods that modify prompts This field is ignored for the methods that add prompts. If you try to create or modify a prompt in more than one language in the same request, an exception occurs. For several languages, use several requests.
name (string): Name of the prompt.
type (promptType): Type of prompt.
  TTSGenerated (string): Audio file generated with Five9 text-to-speech.
  PreRecorded (string): Audio file recorded with third-party tool.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(PromptsAddTtsSample)
			return nil
		}
		req := soap.NewRequest("addPromptTTS")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("prompt", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var PromptsAddWavCmd = &cobra.Command{
	Use:   "add-wav",
	Short: "Creates a prompt and to upload a WAV audio file. For more information about the supported WAV formats, refer to the *...",
	Long:  `Creates a prompt and to upload a WAV audio file. For more information about the supported WAV formats, refer to the *Five9 Administrator’s Guide*.

Body file schema (promptInfo):
description (string): Description of the prompt.
languages (string[]): List of languages for getPrompt() or one language for the methods that modify prompts This field is ignored for the methods that add prompts. If you try to create or modify a prompt in more than one language in the same request, an exception occurs. For several languages, use several requests.
name (string): Name of the prompt.
type (promptType): Type of prompt.
  TTSGenerated (string): Audio file generated with Five9 text-to-speech.
  PreRecorded (string): Audio file recorded with third-party tool.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(PromptsAddWavSample)
			return nil
		}
		req := soap.NewRequest("addPromptWav")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("prompt", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var PromptsAddWavInlineCmd = &cobra.Command{
	Use:   "add-wav-inline",
	Short: "Creates a prompt and uploads an audio file in base-64 format.",
	Long:  `Creates a prompt and uploads an audio file in base-64 format.

Body file schema (promptInfo):
description (string): Description of the prompt.
languages (string[]): List of languages for getPrompt() or one language for the methods that modify prompts This field is ignored for the methods that add prompts. If you try to create or modify a prompt in more than one language in the same request, an exception occurs. For several languages, use several requests.
name (string): Name of the prompt.
type (promptType): Type of prompt.
  TTSGenerated (string): Audio file generated with Five9 text-to-speech.
  PreRecorded (string): Audio file recorded with third-party tool.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(PromptsAddWavInlineSample)
			return nil
		}
		req := soap.NewRequest("addPromptWavInline")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("prompt", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var PromptsDeleteLanguageCmd = &cobra.Command{
	Use:   "delete-language",
	Short: "`Version 9.5` Deletes a prompt in the specified language. You cannot overwrite an existing prompt. If you try to modi...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteLanguagePrompt")
		flagPromptName, _ := cmd.Flags().GetString("prompt-name")
		req.SetParam("promptName", flagPromptName)
		flagLanguage, _ := cmd.Flags().GetString("language")
		req.SetParam("language", flagLanguage)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var PromptsDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Deletes a prompt.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deletePrompt")
		flagPromptName, _ := cmd.Flags().GetString("prompt-name")
		req.SetParam("promptName", flagPromptName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var PromptsGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Returns the attributes of a prompt.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getPrompt")
		flagPromptName, _ := cmd.Flags().GetString("prompt-name")
		req.SetParam("promptName", flagPromptName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var PromptsListCmd = &cobra.Command{
	Use:   "list",
	Short: "`Version 9.5` Returns a list of prompts.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getPrompts")
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var PromptsModifyTtsCmd = &cobra.Command{
	Use:   "modify-tts",
	Short: "Updates the text-to-speech settings and the text of a prompt.",
	Long:  `Updates the text-to-speech settings and the text of a prompt.

Body file schema (promptInfo):
description (string): Description of the prompt.
languages (string[]): List of languages for getPrompt() or one language for the methods that modify prompts This field is ignored for the methods that add prompts. If you try to create or modify a prompt in more than one language in the same request, an exception occurs. For several languages, use several requests.
name (string): Name of the prompt.
type (promptType): Type of prompt.
  TTSGenerated (string): Audio file generated with Five9 text-to-speech.
  PreRecorded (string): Audio file recorded with third-party tool.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(PromptsModifyTtsSample)
			return nil
		}
		req := soap.NewRequest("modifyPromptTTS")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("prompt", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var PromptsModifyWavCmd = &cobra.Command{
	Use:   "modify-wav",
	Short: "Updates the settings and the audio file of a prompt.",
	Long:  `Updates the settings and the audio file of a prompt.

Body file schema (promptInfo):
description (string): Description of the prompt.
languages (string[]): List of languages for getPrompt() or one language for the methods that modify prompts This field is ignored for the methods that add prompts. If you try to create or modify a prompt in more than one language in the same request, an exception occurs. For several languages, use several requests.
name (string): Name of the prompt.
type (promptType): Type of prompt.
  TTSGenerated (string): Audio file generated with Five9 text-to-speech.
  PreRecorded (string): Audio file recorded with third-party tool.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(PromptsModifyWavSample)
			return nil
		}
		req := soap.NewRequest("modifyPromptWav")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("prompt", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var PromptsModifyWavInlineCmd = &cobra.Command{
	Use:   "modify-wav-inline",
	Short: "Updates the settings and the audio file of a prompt.",
	Long:  `Updates the settings and the audio file of a prompt.

Body file schema (promptInfo):
description (string): Description of the prompt.
languages (string[]): List of languages for getPrompt() or one language for the methods that modify prompts This field is ignored for the methods that add prompts. If you try to create or modify a prompt in more than one language in the same request, an exception occurs. For several languages, use several requests.
name (string): Name of the prompt.
type (promptType): Type of prompt.
  TTSGenerated (string): Audio file generated with Five9 text-to-speech.
  PreRecorded (string): Audio file recorded with third-party tool.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(PromptsModifyWavInlineSample)
			return nil
		}
		req := soap.NewRequest("modifyPromptWavInline")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("prompt", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(PromptsCmd)
	PromptsCmd.AddCommand(PromptsAddTtsCmd)
	PromptsAddTtsCmd.Flags().String("body-file", "", "JSON file for prompt parameter")
	PromptsAddTtsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	PromptsCmd.AddCommand(PromptsAddWavCmd)
	PromptsAddWavCmd.Flags().String("body-file", "", "JSON file for prompt parameter")
	PromptsAddWavCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	PromptsCmd.AddCommand(PromptsAddWavInlineCmd)
	PromptsAddWavInlineCmd.Flags().String("body-file", "", "JSON file for prompt parameter")
	PromptsAddWavInlineCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	PromptsCmd.AddCommand(PromptsDeleteLanguageCmd)
	PromptsDeleteLanguageCmd.Flags().String("prompt-name", "", "Name of the prompt.")
	PromptsDeleteLanguageCmd.Flags().String("language", "", "Language of the prompt.")
	PromptsCmd.AddCommand(PromptsDeleteCmd)
	PromptsDeleteCmd.Flags().String("prompt-name", "", "Name of prompt.")
	PromptsCmd.AddCommand(PromptsGetCmd)
	PromptsGetCmd.Flags().String("prompt-name", "", "Name of prompt.")
	PromptsCmd.AddCommand(PromptsListCmd)
	PromptsCmd.AddCommand(PromptsModifyTtsCmd)
	PromptsModifyTtsCmd.Flags().String("body-file", "", "JSON file for prompt parameter")
	PromptsModifyTtsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	PromptsCmd.AddCommand(PromptsModifyWavCmd)
	PromptsModifyWavCmd.Flags().String("body-file", "", "JSON file for prompt parameter")
	PromptsModifyWavCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	PromptsCmd.AddCommand(PromptsModifyWavInlineCmd)
	PromptsModifyWavInlineCmd.Flags().String("body-file", "", "JSON file for prompt parameter")
	PromptsModifyWavInlineCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
}
