// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var ReasonCodesCmd = &cobra.Command{
	Use:   "reason-codes",
	Short: "Manage reason codes",
}

var ReasonCodesCreateSample = `{
  "enabled": false,
  "name": "example",
  "paidTime": false,
  "shortcut": {},
  "type": {
    "NotReady": "example",
    "Logout": "example"
  }
}`

var ReasonCodesDeleteByTypeSample = `{
  "NotReady": "example",
  "Logout": "example"
}`

var ReasonCodesGetByTypeSample = `{
  "NotReady": "example",
  "Logout": "example"
}`

var ReasonCodesModifySample = `{
  "enabled": false,
  "name": "example",
  "paidTime": false,
  "shortcut": {},
  "type": {
    "NotReady": "example",
    "Logout": "example"
  }
}`

var ReasonCodesCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Creates a reason code. The response contains an exception if a reason code with the same name already exists or if th...",
	Long:  `Creates a reason code. The response contains an exception if a reason code with the same name already exists or if the maximum number of reason codes has been reached.

Body file schema (reasonCode):
enabled (boolean): Whether a reason code is enabled. True: Reason code is enabled. False: Reason code is not enabled.
name (string): Name of the reason code.
paidTime (boolean): Whether the agent is paid for the time away. True: Agent is paid. False: Agent is not paid.
shortcut (unsignedShort): Character used as a keyboard shortcut by the agent going away.
type (reasonCodeType): Situation for which reason code is set.
  NotReady (string): Ready state changed to not ready.
  Logout (string): Agent logs out.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ReasonCodesCreateSample)
			return nil
		}
		req := soap.NewRequest("createReasonCode")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("reasonCode", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ReasonCodesDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "No longer used. Instead, use `deleteReasonCodeByType`.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteReasonCode")
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ReasonCodesDeleteByTypeCmd = &cobra.Command{
	Use:   "delete-by-type",
	Short: "Deletes a reason code.",
	Long:  `Deletes a reason code.

Body file schema (reasonCodeType):
NotReady (string): Ready state changed to not ready.
Logout (string): Agent logs out.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ReasonCodesDeleteByTypeSample)
			return nil
		}
		req := soap.NewRequest("deleteReasonCodeByType")
		flagReasonCodeName, _ := cmd.Flags().GetString("reason-code-name")
		req.SetParam("reasonCodeName", flagReasonCodeName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("type", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ReasonCodesGetCmd = &cobra.Command{
	Use:   "get",
	Short: "No longer used. Instead, use `getReasonCodeByType`.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getReasonCode")
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ReasonCodesGetByTypeCmd = &cobra.Command{
	Use:   "get-by-type",
	Short: "Returns the details of a reason code.",
	Long:  `Returns the details of a reason code.

Body file schema (reasonCodeType):
NotReady (string): Ready state changed to not ready.
Logout (string): Agent logs out.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ReasonCodesGetByTypeSample)
			return nil
		}
		req := soap.NewRequest("getReasonCodeByType")
		flagReasonCodeName, _ := cmd.Flags().GetString("reason-code-name")
		req.SetParam("reasonCodeName", flagReasonCodeName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("type", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ReasonCodesModifyCmd = &cobra.Command{
	Use:   "modify",
	Short: "Updates a reason code.",
	Long:  `Updates a reason code.

Body file schema (reasonCode):
enabled (boolean): Whether a reason code is enabled. True: Reason code is enabled. False: Reason code is not enabled.
name (string): Name of the reason code.
paidTime (boolean): Whether the agent is paid for the time away. True: Agent is paid. False: Agent is not paid.
shortcut (unsignedShort): Character used as a keyboard shortcut by the agent going away.
type (reasonCodeType): Situation for which reason code is set.
  NotReady (string): Ready state changed to not ready.
  Logout (string): Agent logs out.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ReasonCodesModifySample)
			return nil
		}
		req := soap.NewRequest("modifyReasonCode")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("reasonCode", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(ReasonCodesCmd)
	ReasonCodesCmd.AddCommand(ReasonCodesCreateCmd)
	ReasonCodesCreateCmd.Flags().String("body-file", "", "JSON file for reasonCode parameter")
	ReasonCodesCreateCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ReasonCodesCmd.AddCommand(ReasonCodesDeleteCmd)
	ReasonCodesCmd.AddCommand(ReasonCodesDeleteByTypeCmd)
	ReasonCodesDeleteByTypeCmd.Flags().String("reason-code-name", "", "Name of reason code.")
	ReasonCodesDeleteByTypeCmd.Flags().String("body-file", "", "JSON file for type parameter")
	ReasonCodesDeleteByTypeCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ReasonCodesCmd.AddCommand(ReasonCodesGetCmd)
	ReasonCodesCmd.AddCommand(ReasonCodesGetByTypeCmd)
	ReasonCodesGetByTypeCmd.Flags().String("reason-code-name", "", "Name of reason code.")
	ReasonCodesGetByTypeCmd.Flags().String("body-file", "", "JSON file for type parameter")
	ReasonCodesGetByTypeCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	ReasonCodesCmd.AddCommand(ReasonCodesModifyCmd)
	ReasonCodesModifyCmd.Flags().String("body-file", "", "JSON file for reasonCode parameter")
	ReasonCodesModifyCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
}
