// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var ReportsCmd = &cobra.Command{
	Use:   "reports",
	Short: "Run and retrieve reports",
}

var ReportsRunSample = `{
  "reportObjects": [
    {
      "objectNames": [
        "example"
      ],
      "objectType": "AgentGroup"
    }
  ],
  "time": {
    "end": "2024-01-01T00:00:00",
    "start": "2024-01-01T00:00:00"
  }
}`

var ReportsGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Returns the data from a report generated by runReport. For best results, Five9 recommends using the getReportResultCs...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getReportResult")
		flagIdentifier, _ := cmd.Flags().GetString("identifier")
		req.SetParam("identifier", flagIdentifier)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ReportsGetCsvCmd = &cobra.Command{
	Use:   "get-csv",
	Short: "Returns the data from a report generated by runReport. The result of the report is in CSV format. The CSV output will...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getReportResultCsv")
		flagIdentifier, _ := cmd.Flags().GetString("identifier")
		req.SetParam("identifier", flagIdentifier)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ReportsStatusCmd = &cobra.Command{
	Use:   "status",
	Short: "Checks whether a report is running and tracks changes in the status of a report. The method returns the response as s...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("isReportRunning")
		flagIdentifier, _ := cmd.Flags().GetString("identifier")
		req.SetParam("identifier", flagIdentifier)
		flagTimeout, _ := cmd.Flags().GetString("timeout")
		req.SetParam("timeout", flagTimeout)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var ReportsRunCmd = &cobra.Command{
	Use:   "run",
	Short: "Use this method to generate a report. Because the time to generate a report varies, you need to follow up with `isRep...",
	Long:  `Use this method to generate a report. Because the time to generate a report varies, you need to follow up with 'isReportRunning' until it returns false. If you omit this step, the report that you retrieve may not contain all the data that you expect. When the report is completely generated, retrieve the data with 'getReportResult' or 'getReportResultCsv'. To reduce network traffic when calling runReport, Five9 recommends that you limit the criteria to a smaller time period to reduce the data returned. For example, to obtain data for a year, split the time period into months or weeks to return smaller data amounts instead of requesting one large report for an entire year.

Body file schema (customReportCriteria):
reportObjects (reportObjectList[]): List of objects by which to filter the report.
  objectNames (string[]): Names of the objects.
  objectType (wsObjectType): Possible filters that you can use in reports.
time (reportTimeCriteria): Start and end of reporting time.
  end (dateTime): End of the reporting period.
  start (dateTime): Start of the reporting period with the time zone. Example: 2013-04-23T21:00:00.000-07:00.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(ReportsRunSample)
			return nil
		}
		req := soap.NewRequest("runReport")
		flagFolderName, _ := cmd.Flags().GetString("folder-name")
		req.SetParam("folderName", flagFolderName)
		flagReportName, _ := cmd.Flags().GetString("report-name")
		req.SetParam("reportName", flagReportName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("criteria", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(ReportsCmd)
	ReportsCmd.AddCommand(ReportsGetCmd)
	ReportsGetCmd.Flags().String("identifier", "", "Unique identifier returned by runReport.")
	ReportsCmd.AddCommand(ReportsGetCsvCmd)
	ReportsGetCsvCmd.Flags().String("identifier", "", "Unique identifier returned by runReport.")
	ReportsCmd.AddCommand(ReportsStatusCmd)
	ReportsStatusCmd.Flags().String("identifier", "", "Unique identifier returned by runReport.")
	ReportsStatusCmd.Flags().String("timeout", "", "Required time in seconds to wait for changes before returning the current state. If set to 0, thi...")
	ReportsCmd.AddCommand(ReportsRunCmd)
	ReportsRunCmd.Flags().String("folder-name", "", "Report category, such as Call Log Reports. For more information, see the Dashboards and Reports U...")
	ReportsRunCmd.Flags().String("report-name", "", "Name of the report, such as Call Log.")
	ReportsRunCmd.Flags().String("body-file", "", "JSON file for criteria parameter")
	ReportsRunCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
}
