// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var SessionCmd = &cobra.Command{
	Use:   "session",
	Short: "Manage API sessions",
}

var SessionCloseCmd = &cobra.Command{
	Use:   "close",
	Short: "Closes the administrator’s session. The administrator can then log in to the VCC Administrator application.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("closeSession")
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(SessionCmd)
	SessionCmd.AddCommand(SessionCloseCmd)
}
