// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var SkillsCmd = &cobra.Command{
	Use:   "skills",
	Short: "Manage skills",
}

var SkillsCreateSample = `{
  "skill": {
    "description": "example",
    "id": 0,
    "messageOfTheDay": "example",
    "name": "example",
    "routeVoiceMails": false
  },
  "users": [
    {
      "id": 0,
      "userSkill.level": 0,
      "skillName": "example",
      "userName": "example"
    }
  ]
}`

var SkillsModifySample = `{
  "description": "example",
  "id": 0,
  "messageOfTheDay": "example",
  "name": "example",
  "routeVoiceMails": false
}`

var SkillsAddAudioFileCmd = &cobra.Command{
	Use:   "add-audio-file",
	Short: "`Version 9.5` Add audio files for the skill.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("addSkillAudioFile")
		flagSkillName, _ := cmd.Flags().GetString("skill-name")
		req.SetParam("skillName", flagSkillName)
		flagPromptName, _ := cmd.Flags().GetString("prompt-name")
		req.SetParam("promptName", flagPromptName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var SkillsCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Creates a skill. An exception is thrown if the skill already exists, if the limit number of skills is reached, or if ...",
	Long:  `Creates a skill. An exception is thrown if the skill already exists, if the limit number of skills is reached, or if skill attributes are invalid.

Body file schema (skillInfo):
skill (skill): Skill description.
  description (string): Skill description.
  id (long): Skill ID.
  messageOfTheDay (string): Message of the day for the skill.
  name (string): Skill name.
  routeVoiceMails (boolean): Whether to route voicemail messages to the skill. True: Route voicemail messages to skill. False: Do not route voicemail messages to skill.
users (userSkill[]): Users who possess the skill.
  id (long): Queue ID.
  userSkill.level (int): Priority of agent to receive calls sent to this queue. Level 1 is the highest priority; level 10 is the lowest. Higher level receive calls first. When agents are assigned to several queues, each queue may have a different priority.
  skillName (string): Queue name.
  userName (string): User name assigned the queue.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(SkillsCreateSample)
			return nil
		}
		req := soap.NewRequest("createSkill")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("skillInfo", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var SkillsDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Deletes a skill.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteSkill")
		flagSkillName, _ := cmd.Flags().GetString("skill-name")
		req.SetParam("skillName", flagSkillName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var SkillsGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Returns skill information: skill name, skill description, message of the day, and whether skill voicemail messages ar...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getSkill")
		flagSkillName, _ := cmd.Flags().GetString("skill-name")
		req.SetParam("skillName", flagSkillName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var SkillsGetAudioFilesCmd = &cobra.Command{
	Use:   "get-audio-files",
	Short: "`Version 9.5` Gets a list of skill audio files.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getSkillAudioFiles")
		flagSkillName, _ := cmd.Flags().GetString("skill-name")
		req.SetParam("skillName", flagSkillName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var SkillsGetInfoCmd = &cobra.Command{
	Use:   "get-info",
	Short: "Returns detailed skill information about a skill.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getSkillInfo")
		flagSkillName, _ := cmd.Flags().GetString("skill-name")
		req.SetParam("skillName", flagSkillName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var SkillsGetVoicemailGreetingCmd = &cobra.Command{
	Use:   "get-voicemail-greeting",
	Short: "Returns the attributes of a prompt.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getSkillVoicemailGreeting")
		flagSkillName, _ := cmd.Flags().GetString("skill-name")
		req.SetParam("skillName", flagSkillName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var SkillsListCmd = &cobra.Command{
	Use:   "list",
	Short: "Returns information about each skill name that matches a pattern.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getSkills")
		flagSkillNamePattern, _ := cmd.Flags().GetString("skill-name-pattern")
		req.SetParam("skillNamePattern", flagSkillNamePattern)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var SkillsListInfoCmd = &cobra.Command{
	Use:   "list-info",
	Short: "Returns a list of users that possess the skill that matches a skill name pattern.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getSkillsInfo")
		flagSkillNamePattern, _ := cmd.Flags().GetString("skill-name-pattern")
		req.SetParam("skillNamePattern", flagSkillNamePattern)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var SkillsModifyCmd = &cobra.Command{
	Use:   "modify",
	Short: "Modifies an existing skill. An exception is thrown if the skill already exists or if the skill attributes are invalid.",
	Long:  `Modifies an existing skill. An exception is thrown if the skill already exists or if the skill attributes are invalid.

Body file schema (skill):
description (string): Skill description.
id (long): Skill ID.
messageOfTheDay (string): Message of the day for the skill.
name (string): Skill name.
routeVoiceMails (boolean): Whether to route voicemail messages to the skill. True: Route voicemail messages to skill. False: Do not route voicemail messages to skill.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(SkillsModifySample)
			return nil
		}
		req := soap.NewRequest("modifySkill")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("skill", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var SkillsRemoveAudioFileCmd = &cobra.Command{
	Use:   "remove-audio-file",
	Short: "`Version 9.5` Deletes a skill audio file.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("removeSkillAudioFile")
		flagSkillName, _ := cmd.Flags().GetString("skill-name")
		req.SetParam("skillName", flagSkillName)
		flagPromptName, _ := cmd.Flags().GetString("prompt-name")
		req.SetParam("promptName", flagPromptName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var SkillsSetVoicemailGreetingCmd = &cobra.Command{
	Use:   "set-voicemail-greeting",
	Short: "Uploads the audio file in WAV format provided by the Web Services user and associates it with a skill to be played wh...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("setSkillVoicemailGreeting")
		flagSkillName, _ := cmd.Flags().GetString("skill-name")
		req.SetParam("skillName", flagSkillName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("wavFile", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(SkillsCmd)
	SkillsCmd.AddCommand(SkillsAddAudioFileCmd)
	SkillsAddAudioFileCmd.Flags().String("skill-name", "", "Skill name.")
	SkillsAddAudioFileCmd.Flags().String("prompt-name", "", "Prompt name.")
	SkillsCmd.AddCommand(SkillsCreateCmd)
	SkillsCreateCmd.Flags().String("body-file", "", "JSON file for skillInfo parameter")
	SkillsCreateCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	SkillsCmd.AddCommand(SkillsDeleteCmd)
	SkillsDeleteCmd.Flags().String("skill-name", "", "Name of skill to be deleted.")
	SkillsCmd.AddCommand(SkillsGetCmd)
	SkillsGetCmd.Flags().String("skill-name", "", "Name of skill.")
	SkillsCmd.AddCommand(SkillsGetAudioFilesCmd)
	SkillsGetAudioFilesCmd.Flags().String("skill-name", "", "Name of skill.")
	SkillsCmd.AddCommand(SkillsGetInfoCmd)
	SkillsGetInfoCmd.Flags().String("skill-name", "", "Name of skill.")
	SkillsCmd.AddCommand(SkillsGetVoicemailGreetingCmd)
	SkillsGetVoicemailGreetingCmd.Flags().String("skill-name", "", "Name of skill with the specified voicemail greeting.")
	SkillsCmd.AddCommand(SkillsListCmd)
	SkillsListCmd.Flags().String("skill-name-pattern", ".*", "Pattern of skill name. The skill name pattern is a regular expression. If omitted or equal to an ...")
	SkillsCmd.AddCommand(SkillsListInfoCmd)
	SkillsListInfoCmd.Flags().String("skill-name-pattern", ".*", "Pattern of skill name. The skill name pattern is a regular expression. If omitted or equal to an ...")
	SkillsCmd.AddCommand(SkillsModifyCmd)
	SkillsModifyCmd.Flags().String("body-file", "", "JSON file for skill parameter")
	SkillsModifyCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	SkillsCmd.AddCommand(SkillsRemoveAudioFileCmd)
	SkillsRemoveAudioFileCmd.Flags().String("skill-name", "", "Skill name.")
	SkillsRemoveAudioFileCmd.Flags().String("prompt-name", "", "Prompt name.")
	SkillsCmd.AddCommand(SkillsSetVoicemailGreetingCmd)
	SkillsSetVoicemailGreetingCmd.Flags().String("skill-name", "", "New prompt attributes.")
	SkillsSetVoicemailGreetingCmd.Flags().String("body-file", "", "JSON file for wavFile parameter")
	SkillsSetVoicemailGreetingCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
}
