// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var SpeedDialCmd = &cobra.Command{
	Use:   "speed-dial",
	Short: "Manage speed dial numbers",
}

var SpeedDialCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Version 10.2 Adds a speed dial number.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("createSpeedDialNumber")
		flagCode, _ := cmd.Flags().GetString("code")
		req.SetParam("code", flagCode)
		flagDescription, _ := cmd.Flags().GetString("description")
		req.SetParam("description", flagDescription)
		flagNumber, _ := cmd.Flags().GetString("number")
		req.SetParam("number", flagNumber)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var SpeedDialListCmd = &cobra.Command{
	Use:   "list",
	Short: "Version 10.2 Returns a list of speed dial numbers.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getSpeedDialNumbers")
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var SpeedDialRemoveCmd = &cobra.Command{
	Use:   "remove",
	Short: "Version 10.2 Removes a speed dial number.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("removeSpeedDialNumber")
		flagCode, _ := cmd.Flags().GetString("code")
		req.SetParam("code", flagCode)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(SpeedDialCmd)
	SpeedDialCmd.AddCommand(SpeedDialCreateCmd)
	SpeedDialCreateCmd.Flags().String("code", "", "Code assigned to the telephone number to speed dial.")
	SpeedDialCreateCmd.Flags().String("description", "", "Description for the number.")
	SpeedDialCreateCmd.Flags().String("number", "", "Telephone number to dial.")
	SpeedDialCmd.AddCommand(SpeedDialListCmd)
	SpeedDialCmd.AddCommand(SpeedDialRemoveCmd)
	SpeedDialRemoveCmd.Flags().String("code", "", "Code assigned to the number to speed dial.")
}
