// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var UserProfilesCmd = &cobra.Command{
	Use:   "user-profiles",
	Short: "Manage user profiles",
}

var UserProfilesCreateSample = `{
  "description": "example",
  "IEXScheduled": false,
  "locale": "example",
  "mediaTypeConfig": {
    "mediaTypes": [
      {
        "enabled": false,
        "intlligentRouting": false,
        "maxAlowed": 0,
        "type": {
          "mediaType": "example"
        }
      }
    ]
  },
  "name": "example",
  "roles": {
    "admin": {
      "permissions": [
        {
          "type": {},
          "value": false
        }
      ]
    },
    "agent": {
      "alwaysRecorded": false,
      "attachVmToEmail": false,
      "permissions": [
        {
          "type": {},
          "value": false
        }
      ],
      "sendEmailOnVm": false
    },
    "reporting": {
      "permissions": [
        {
          "type": {},
          "value": false
        }
      ]
    },
    "supervisor": {
      "permissions": [
        {
          "type": {},
          "value": false
        }
      ]
    }
  },
  "skills": [
    "example"
  ],
  "users": [
    "example"
  ]
}`

var UserProfilesModifySample = `{
  "description": "example",
  "IEXScheduled": false,
  "locale": "example",
  "mediaTypeConfig": {
    "mediaTypes": [
      {
        "enabled": false,
        "intlligentRouting": false,
        "maxAlowed": 0,
        "type": {
          "mediaType": "example"
        }
      }
    ]
  },
  "name": "example",
  "roles": {
    "admin": {
      "permissions": [
        {
          "type": {},
          "value": false
        }
      ]
    },
    "agent": {
      "alwaysRecorded": false,
      "attachVmToEmail": false,
      "permissions": [
        {
          "type": {},
          "value": false
        }
      ],
      "sendEmailOnVm": false
    },
    "reporting": {
      "permissions": [
        {
          "type": {},
          "value": false
        }
      ]
    },
    "supervisor": {
      "permissions": [
        {
          "type": {},
          "value": false
        }
      ]
    }
  },
  "skills": [
    "example"
  ],
  "users": [
    "example"
  ]
}`

var UserProfilesCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Creates a user profile with a set of users, roles, skills, and layout.",
	Long:  `Creates a user profile with a set of users, roles, skills, and layout.

Body file schema (userProfile):
description (string): Description of the profile.
IEXScheduled (boolean): Do not use.
locale (string): User’s locale.
mediaTypeConfig (mediaTypeConfig): Information about the user’s media types.
  mediaTypes (mediaTypeItem[]): List of media type items.
name (string): Name of the profile.
roles (userRoles): User roles assigned to the profile.
  admin (adminRole): Administrator role permissions.
  agent (agentRole): Agent role permissions.
  reporting (reportingRole): Reporting role permissions.
  supervisor (supervisorRole): Supervisor role permissions.
skills (string[]): Skills assigned to the profile.
users (string[]): List of agents using the profile.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(UserProfilesCreateSample)
			return nil
		}
		req := soap.NewRequest("createUserProfile")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("userProfile", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UserProfilesDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Deletes a user profile.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteUserProfile")
		flagUserProfileName, _ := cmd.Flags().GetString("user-profile-name")
		req.SetParam("userProfileName", flagUserProfileName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UserProfilesGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Returns information (users, roles, and skills) about a user profile. To obtain information about several user profile...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getUserProfile")
		flagUserProfileName, _ := cmd.Flags().GetString("user-profile-name")
		req.SetParam("userProfileName", flagUserProfileName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UserProfilesListCmd = &cobra.Command{
	Use:   "list",
	Short: "Returns a list of user profiles whose names match a string pattern.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getUserProfiles")
		flagUserProfileNamePatern, _ := cmd.Flags().GetString("user-profile-name-patern")
		req.SetParam("userProfileNamePatern", flagUserProfileNamePatern)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UserProfilesModifyCmd = &cobra.Command{
	Use:   "modify",
	Short: "Updates a user profile.",
	Long:  `Updates a user profile.

Body file schema (userProfile):
description (string): Description of the profile.
IEXScheduled (boolean): Do not use.
locale (string): User’s locale.
mediaTypeConfig (mediaTypeConfig): Information about the user’s media types.
  mediaTypes (mediaTypeItem[]): List of media type items.
name (string): Name of the profile.
roles (userRoles): User roles assigned to the profile.
  admin (adminRole): Administrator role permissions.
  agent (agentRole): Agent role permissions.
  reporting (reportingRole): Reporting role permissions.
  supervisor (supervisorRole): Supervisor role permissions.
skills (string[]): Skills assigned to the profile.
users (string[]): List of agents using the profile.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(UserProfilesModifySample)
			return nil
		}
		req := soap.NewRequest("modifyUserProfile")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("userProfile", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UserProfilesModifySkillsCmd = &cobra.Command{
	Use:   "modify-skills",
	Short: "Updates the skills of a user profile.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("modifyUserProfileSkills")
		flagUserProfileName, _ := cmd.Flags().GetString("user-profile-name")
		req.SetParam("userProfileName", flagUserProfileName)
		flagAddSkills, _ := cmd.Flags().GetStringSlice("add-skills")
		for _, v := range flagAddSkills {
			req.SetParam("addSkills", v)
		}
		flagRemoveSkills, _ := cmd.Flags().GetStringSlice("remove-skills")
		for _, v := range flagRemoveSkills {
			req.SetParam("removeSkills", v)
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UserProfilesModifyUserListCmd = &cobra.Command{
	Use:   "modify-user-list",
	Short: "Updates the users of a user profile.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("modifyUserProfileUserList")
		flagUserProfileName, _ := cmd.Flags().GetString("user-profile-name")
		req.SetParam("userProfileName", flagUserProfileName)
		flagAddUsers, _ := cmd.Flags().GetStringSlice("add-users")
		for _, v := range flagAddUsers {
			req.SetParam("addUsers", v)
		}
		flagRemoveUsers, _ := cmd.Flags().GetStringSlice("remove-users")
		for _, v := range flagRemoveUsers {
			req.SetParam("removeUsers", v)
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(UserProfilesCmd)
	UserProfilesCmd.AddCommand(UserProfilesCreateCmd)
	UserProfilesCreateCmd.Flags().String("body-file", "", "JSON file for userProfile parameter")
	UserProfilesCreateCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	UserProfilesCmd.AddCommand(UserProfilesDeleteCmd)
	UserProfilesDeleteCmd.Flags().String("user-profile-name", "", "Name of profile.")
	UserProfilesCmd.AddCommand(UserProfilesGetCmd)
	UserProfilesGetCmd.Flags().String("user-profile-name", "", "Name of profile.")
	UserProfilesCmd.AddCommand(UserProfilesListCmd)
	UserProfilesListCmd.Flags().String("user-profile-name-patern", "", "Name of the profile or regular expression. For all user profiles, omit the parameter or use this ...")
	UserProfilesCmd.AddCommand(UserProfilesModifyCmd)
	UserProfilesModifyCmd.Flags().String("body-file", "", "JSON file for userProfile parameter")
	UserProfilesModifyCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	UserProfilesCmd.AddCommand(UserProfilesModifySkillsCmd)
	UserProfilesModifySkillsCmd.Flags().String("user-profile-name", "", "Name of profile.")
	UserProfilesModifySkillsCmd.Flags().StringSlice("add-skills", nil, "List of skills to add.")
	UserProfilesModifySkillsCmd.Flags().StringSlice("remove-skills", nil, "List of skills to remove.")
	UserProfilesCmd.AddCommand(UserProfilesModifyUserListCmd)
	UserProfilesModifyUserListCmd.Flags().String("user-profile-name", "", "Name of profile.")
	UserProfilesModifyUserListCmd.Flags().StringSlice("add-users", nil, "List of users to add.")
	UserProfilesModifyUserListCmd.Flags().StringSlice("remove-users", nil, "List of users to remove.")
}
