// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var UsersCmd = &cobra.Command{
	Use:   "users",
	Short: "Manage users",
}

var UsersCreateSample = `{
  "agentGroups": [
    "example"
  ],
  "cannedReports": [
    {
      "index": 0,
      "name": "example"
    }
  ],
  "generalInfo": {
    "active": false,
    "canChangePassword": false,
    "EMail": "example",
    "extension": 0,
    "federationId": "example",
    "firstName": "example",
    "fullName": "example",
    "IEXScheduled": false,
    "id": 0,
    "lastName": "example",
    "locale": "example",
    "mediaTypeConfig": {
      "mediaTypes": [
        {
          "enabled": false,
          "intlligentRouting": false,
          "maxAlowed": 0,
          "type": {}
        }
      ]
    },
    "mustChangePassword": false,
    "osLogin": "example",
    "password": "example",
    "phoneNumber": "example",
    "startDate": "2024-01-01T00:00:00",
    "unifiedCommunicationId": "example",
    "userName": "example",
    "userProfileName": "example"
  },
  "roles": {
    "admin": {
      "permissions": [
        {
          "type": {},
          "value": false
        }
      ]
    },
    "agent": {
      "alwaysRecorded": false,
      "attachVmToEmail": false,
      "permissions": [
        {
          "type": {},
          "value": false
        }
      ],
      "sendEmailOnVm": false
    },
    "reporting": {
      "permissions": [
        {
          "type": {},
          "value": false
        }
      ]
    },
    "supervisor": {
      "permissions": [
        {
          "type": {},
          "value": false
        }
      ]
    }
  },
  "skills": [
    {
      "id": 0,
      "userSkill.level": 0,
      "skillName": "example",
      "userName": "example"
    }
  ]
}`

var UsersModifySample = `{
  "active": false,
  "canChangePassword": false,
  "EMail": "example",
  "extension": 0,
  "federationId": "example",
  "firstName": "example",
  "fullName": "example",
  "IEXScheduled": false,
  "id": 0,
  "lastName": "example",
  "locale": "example",
  "mediaTypeConfig": {
    "mediaTypes": [
      {
        "enabled": false,
        "intlligentRouting": false,
        "maxAlowed": 0,
        "type": {
          "mediaType": "example"
        }
      }
    ]
  },
  "mustChangePassword": false,
  "osLogin": "example",
  "password": "example",
  "phoneNumber": "example",
  "startDate": "2024-01-01T00:00:00",
  "unifiedCommunicationId": "example",
  "userName": "example",
  "userProfileName": "example"
}`

var UsersModifyCannedReportsSample = `{
  "index": 0,
  "name": "example"
}`

var UsersSkillAddSample = `{
  "id": 0,
  "userSkill.level": 0,
  "skillName": "example",
  "userName": "example"
}`

var UsersSkillModifySample = `{
  "id": 0,
  "userSkill.level": 0,
  "skillName": "example",
  "userName": "example"
}`

var UsersSkillRemoveSample = `{
  "id": 0,
  "userSkill.level": 0,
  "skillName": "example",
  "userName": "example"
}`

var UsersCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Creates a user. An exception is thrown if the user already exists, if the limit number of users is reached, if user a...",
	Long:  `Creates a user. An exception is thrown if the user already exists, if the limit number of users is reached, if user attributes are invalid, and if an API only user is modified on the domain where the feature is enabled.

Body file schema (userInfo):
agentGroups (string[]): Agent groups to which the user belongs.
cannedReports (cannedReport[]): Reports associated with the user.
  index (int): Order number of the report.
  name (string): Name of the report.
generalInfo (userGeneralInfo): General information about the user, such as name and email address.
  active (boolean): Whether the user account is enabled. True: Account enabled. False: Account disabled.
  canChangePassword (boolean): Whether the user can change the password. True: User can change password. False: User cannot change password.
  EMail (string): User’s email address.
  extension (int): User’s phone extension.
  federationId (string): Federation ID.
  firstName (string): First name of the user.
  fullName (string): First and last name.
  IEXScheduled (boolean): Do not use.
  id (long): User ID.
  lastName (string): User’s last name.
  locale (string): User’s locale.
  mediaTypeConfig (mediaTypeConfig): Information about the user’s media types.
  mustChangePassword (boolean): Whether the user is required to change the password when logging in for the first time. True: User required to change password. False: User not required to change password.
  osLogin (string): Do not use.
  password (string): Password.
  phoneNumber (string): Phone number of the unified communication user.
  startDate (dateTime): Date that the user started using the Five9 system. This value is used in reporting.
  unifiedCommunicationId (string): Unified communication ID, for example, a Skype for Business ID such as syoung@qa59.local.com.
  userName (string): User name.
  userProfileName (string): Profile assigned to the user.
roles (userRoles): Roles assigned to the user.
  admin (adminRole): Administrator role permissions.
  agent (agentRole): Agent role permissions.
  reporting (reportingRole): Reporting role permissions.
  supervisor (supervisorRole): Supervisor role permissions.
skills (userSkill[]): List of user skills.
  id (long): Queue ID.
  userSkill.level (int): Priority of agent to receive calls sent to this queue. Level 1 is the highest priority; level 10 is the lowest. Higher level receive calls first. When agents are assigned to several queues, each queue may have a different priority.
  skillName (string): Queue name.
  userName (string): User name assigned the queue.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(UsersCreateSample)
			return nil
		}
		req := soap.NewRequest("createUser")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("userInfo", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UsersDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Deletes the specified user. An exception is thrown if the user does not exist. When you delete a user, all associated...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteUser")
		flagUserName, _ := cmd.Flags().GetString("user-name")
		req.SetParam("userName", flagUserName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UsersGetGeneralInfoCmd = &cobra.Command{
	Use:   "get-general-info",
	Short: "No longer used. Use `getUsersGeneralInfo` instead.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getUserGeneralInfo")
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UsersGetCmd = &cobra.Command{
	Use:   "get",
	Short: "No longer used. Use `getUsersInfo` instead.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getUserInfo")
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UsersGetVoicemailGreetingCmd = &cobra.Command{
	Use:   "get-voicemail-greeting",
	Short: "Returns the user’s voicemail greeting.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getUserVoicemailGreeting")
		flagUserName, _ := cmd.Flags().GetString("user-name")
		req.SetParam("userName", flagUserName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UsersListCmd = &cobra.Command{
	Use:   "list",
	Short: "Returns general information about each user name that matches a pattern.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getUsersGeneralInfo")
		flagUserNamePattern, _ := cmd.Flags().GetString("user-name-pattern")
		req.SetParam("userNamePattern", flagUserNamePattern)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UsersListInfoCmd = &cobra.Command{
	Use:   "list-info",
	Short: "Returns information about roles and skills of each user name that matches a pattern.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getUsersInfo")
		flagUserNamePattern, _ := cmd.Flags().GetString("user-name-pattern")
		req.SetParam("userNamePattern", flagUserNamePattern)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UsersModifyCmd = &cobra.Command{
	Use:   "modify",
	Short: "Modifies the user’s attributes. An exception is thrown if the user already exists, if the limit number of users is re...",
	Long:  `Modifies the user’s attributes. An exception is thrown if the user already exists, if the limit number of users is reached, or if user attributes are invalid.

Body file schema (userGeneralInfo):
active (boolean): Whether the user account is enabled. True: Account enabled. False: Account disabled.
canChangePassword (boolean): Whether the user can change the password. True: User can change password. False: User cannot change password.
EMail (string): User’s email address.
extension (int): User’s phone extension.
federationId (string): Federation ID.
firstName (string): First name of the user.
fullName (string): First and last name.
IEXScheduled (boolean): Do not use.
id (long): User ID.
lastName (string): User’s last name.
locale (string): User’s locale.
mediaTypeConfig (mediaTypeConfig): Information about the user’s media types.
  mediaTypes (mediaTypeItem[]): List of media type items.
mustChangePassword (boolean): Whether the user is required to change the password when logging in for the first time. True: User required to change password. False: User not required to change password.
osLogin (string): Do not use.
password (string): Password.
phoneNumber (string): Phone number of the unified communication user.
startDate (dateTime): Date that the user started using the Five9 system. This value is used in reporting.
unifiedCommunicationId (string): Unified communication ID, for example, a Skype for Business ID such as syoung@qa59.local.com.
userName (string): User name.
userProfileName (string): Profile assigned to the user.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(UsersModifySample)
			return nil
		}
		req := soap.NewRequest("modifyUser")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("userGeneralInfo", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UsersModifyCannedReportsCmd = &cobra.Command{
	Use:   "modify-canned-reports",
	Short: "Updates the list of canned reports associated with a specific user. To get a list of the user’s current canned report...",
	Long:  `Updates the list of canned reports associated with a specific user. To get a list of the user’s current canned reports, use 'getUsersInfo'.

Body file schema (cannedReport):
index (int): Order number of the report.
name (string): Name of the report.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(UsersModifyCannedReportsSample)
			return nil
		}
		req := soap.NewRequest("modifyUserCannedReports")
		flagUserName, _ := cmd.Flags().GetString("user-name")
		req.SetParam("userName", flagUserName)
		flagCannedReportsToRemove, _ := cmd.Flags().GetStringSlice("canned-reports-to-remove")
		for _, v := range flagCannedReportsToRemove {
			req.SetParam("cannedReportsToRemove", v)
		}
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("cannedReportsToAdd", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UsersSetVoicemailGreetingCmd = &cobra.Command{
	Use:   "set-voicemail-greeting",
	Short: "Uploads the audio file in WAV format provided by the Web Services user and to play the file when the user is not avai...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("setUserVoicemailGreeting")
		flagUserName, _ := cmd.Flags().GetString("user-name")
		req.SetParam("userName", flagUserName)
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("wavFile", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UsersSkillAddCmd = &cobra.Command{
	Use:   "skill-add",
	Short: "Adds a skill to a user. To prevent the `userSkillAdd` method from overloading the system, Five9 recommends that you s...",
	Long:  `Adds a skill to a user. To prevent the 'userSkillAdd' method from overloading the system, Five9 recommends that you set a sleep parameter of  at least 3 seconds between each request. Because this method affects the performance of the dialer and uses significant database resources, use this method only during off-peak periods.

Body file schema (userSkill):
id (long): Queue ID.
userSkill.level (int): Priority of agent to receive calls sent to this queue. Level 1 is the highest priority; level 10 is the lowest. Higher level receive calls first. When agents are assigned to several queues, each queue may have a different priority.
skillName (string): Queue name.
userName (string): User name assigned the queue.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(UsersSkillAddSample)
			return nil
		}
		req := soap.NewRequest("userSkillAdd")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("userSkill", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UsersSkillModifyCmd = &cobra.Command{
	Use:   "skill-modify",
	Short: "Modifies a skill. To prevent the `userSkillModify` method from overloading the system, Five9 recommends that you set ...",
	Long:  `Modifies a skill. To prevent the 'userSkillModify' method from overloading the system, Five9 recommends that you set a sleep parameter of  at least 3 seconds between each request. Because this method affects the performance of the dialer and uses significant database resources, use this method only during off-peak periods.

Body file schema (userSkill):
id (long): Queue ID.
userSkill.level (int): Priority of agent to receive calls sent to this queue. Level 1 is the highest priority; level 10 is the lowest. Higher level receive calls first. When agents are assigned to several queues, each queue may have a different priority.
skillName (string): Queue name.
userName (string): User name assigned the queue.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(UsersSkillModifySample)
			return nil
		}
		req := soap.NewRequest("userSkillModify")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("userSkill", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var UsersSkillRemoveCmd = &cobra.Command{
	Use:   "skill-remove",
	Short: "Deletes a skill. To prevent the `userSkillRemove` method from overloading the system, Five9 recommends that you set a...",
	Long:  `Deletes a skill. To prevent the 'userSkillRemove' method from overloading the system, Five9 recommends that you set a sleep parameter of  at least 3 seconds between each request. Because this method affects the performance of the dialer and uses significant database resources, use this method only during off-peak periods.

Body file schema (userSkill):
id (long): Queue ID.
userSkill.level (int): Priority of agent to receive calls sent to this queue. Level 1 is the highest priority; level 10 is the lowest. Higher level receive calls first. When agents are assigned to several queues, each queue may have a different priority.
skillName (string): Queue name.
userName (string): User name assigned the queue.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(UsersSkillRemoveSample)
			return nil
		}
		req := soap.NewRequest("userSkillRemove")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("userSkill", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(UsersCmd)
	UsersCmd.AddCommand(UsersCreateCmd)
	UsersCreateCmd.Flags().String("body-file", "", "JSON file for userInfo parameter")
	UsersCreateCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	UsersCmd.AddCommand(UsersDeleteCmd)
	UsersDeleteCmd.Flags().String("user-name", "", "Name of user to be deleted.")
	UsersCmd.AddCommand(UsersGetGeneralInfoCmd)
	UsersCmd.AddCommand(UsersGetCmd)
	UsersCmd.AddCommand(UsersGetVoicemailGreetingCmd)
	UsersGetVoicemailGreetingCmd.Flags().String("user-name", "", "Name of user who has the specified voicemail greeting.")
	UsersCmd.AddCommand(UsersListCmd)
	UsersListCmd.Flags().String("user-name-pattern", ".*", "Regular expression that describes the user name pattern. If omitted or equal to an empty string, ...")
	UsersCmd.AddCommand(UsersListInfoCmd)
	UsersListInfoCmd.Flags().String("user-name-pattern", ".*", "Regular expression that describes the user name pattern. If omitted or equal to an empty string, ...")
	UsersCmd.AddCommand(UsersModifyCmd)
	UsersModifyCmd.Flags().String("body-file", "", "JSON file for userGeneralInfo parameter")
	UsersModifyCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	UsersCmd.AddCommand(UsersModifyCannedReportsCmd)
	UsersModifyCannedReportsCmd.Flags().String("user-name", "", "Name of user.")
	UsersModifyCannedReportsCmd.Flags().StringSlice("canned-reports-to-remove", nil, "Names of reports to disassociate from user.")
	UsersModifyCannedReportsCmd.Flags().String("body-file", "", "JSON file for cannedReportsToAdd parameter")
	UsersModifyCannedReportsCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	UsersCmd.AddCommand(UsersSetVoicemailGreetingCmd)
	UsersSetVoicemailGreetingCmd.Flags().String("user-name", "", "Name of user.")
	UsersSetVoicemailGreetingCmd.Flags().String("body-file", "", "JSON file for wavFile parameter")
	UsersSetVoicemailGreetingCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	UsersCmd.AddCommand(UsersSkillAddCmd)
	UsersSkillAddCmd.Flags().String("body-file", "", "JSON file for userSkill parameter")
	UsersSkillAddCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	UsersCmd.AddCommand(UsersSkillModifyCmd)
	UsersSkillModifyCmd.Flags().String("body-file", "", "JSON file for userSkill parameter")
	UsersSkillModifyCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	UsersCmd.AddCommand(UsersSkillRemoveCmd)
	UsersSkillRemoveCmd.Flags().String("body-file", "", "JSON file for userSkill parameter")
	UsersSkillRemoveCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
}
