// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var VccCmd = &cobra.Command{
	Use:   "vcc",
	Short: "VCC configuration",
}

var VccModifyConfigSample = `{
  "agentProductivity": {
    "longACWTime": 0,
    "longCallDuration": 0,
    "longHoldDuration": 0,
    "longParkDuration": 0,
    "shortACWTime": 0,
    "shortCallDuration": 0
  },
  "campaignsSettings": {
    "gracefulAgentStateTransitionDelay": 0,
    "gracefulAgentStateTransitionModeEnabled": false,
    "priorityEnabled": false,
    "ratioEnabled": false
  },
  "emailProperties": {
    "emailAddress": "example",
    "maxAttachmentSize": 0,
    "newUserNotification": false
  },
  "extensionSettings": {
    "maximalExtensionLength": 0,
    "minimalExtensionLength": 0,
    "minimalGeneratedExtension": "example"
  },
  "keyPerfomanceIndicators": {},
  "miscOptions": {
    "defaultCampaign": "example",
    "enableReasonCodes": false,
    "internalCallTimeout": 0,
    "maySelectCampaign": false,
    "maySelectNone": false,
    "showDialAttempts": false,
    "voicemailTimeout": 0
  },
  "passwordPolicies": {
    "adminLoginAttempts": 0,
    "enforcePasswordHistory": 0,
    "loginAttempts": 0,
    "minCapitalCharacters": 0,
    "minNumberCharacters": 0,
    "minPasswordLength": 0,
    "minSpecialCharacters": 0,
    "passwordExpires": 0
  },
  "recordingsServer": "hostName",
  "reportsServer": "hostName",
  "saleforceEmailAccount": {
    "consumerKey": "example",
    "consumerSecret": "example",
    "enabled": false,
    "password": "example",
    "securityToken": "example",
    "userName": "example"
  },
  "stateDialingRule": "REGION",
  "timeZoneAssignment": "PHONE_NUMBER",
  "transcriptsServer": "hostName"
}`

var VccGetApiVersionsCmd = &cobra.Command{
	Use:   "get-api-versions",
	Short: "`Version 9.5` Returns the newest and oldest production versions of the API available to the user so that the client c...",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getApiVersions")
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var VccGetConfigCmd = &cobra.Command{
	Use:   "get-config",
	Short: "Returns the global settings.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getVCCConfiguration")
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var VccModifyConfigCmd = &cobra.Command{
	Use:   "modify-config",
	Short: "Updates the global settings of your Virtual Call Center.",
	Long:  `Updates the global settings of your Virtual Call Center.

Body file schema (vccConfiguration):
agentProductivity (agentProductivity): Minimum and maximum call durations used in reports to identify possible agent productivity exceptions.
  longACWTime (int): Number of seconds spent performing work after a call. The time is reported if is longer than this setting.
  longCallDuration (int): Number of seconds spent on a call. The time is reported if is longer than this setting.
  longHoldDuration (int): Number of seconds for a call placed on hold. The time is reported if is longer than this setting.
  longParkDuration (int): Number of seconds for a call waiting in a queue. The time is reported if is longer than this setting.
  shortACWTime (int): Number of seconds spent performing work after a call. The time is reported if is shorter than this setting.
  shortCallDuration (int): Number of seconds spent on a call. The time is reported if it is shorter than this setting.
campaignsSettings (campaignsSettings): Global campaign settings.
  gracefulAgentStateTransitionDelay (int): Domain setting: Number of seconds between the agents’ action and the effective change of the agents’ state to Not Ready.
  gracefulAgentStateTransitionModeEnabled (boolean): Domain setting: Whether to enable Graceful Agent State Transition.
  priorityEnabled (boolean): Whether absolute priority is enabled. You may enable priority, ratio, both, or neither.
  ratioEnabled (boolean): Whether priority by ratio is enabled. You may enable priority, ratio, both, or neither.
emailProperties (emailNotifications): Email notification settings.
  emailAddress (string): Email address to receive error messages. This address is used for bounced email messages and as the Reply-To address.
  maxAttachmentSize (int): Maximum MB for a voicemail attachment. If a voicemail attachment exceeds the specified size, the email notification is sent without the attachment.
  newUserNotification (boolean): Whether to send the login credentials to the newly created email address of a user. True: Send the login credentials. False: Do not send the login credentials.
extensionSettings (extensionSettings): Domain extension settings that apply to users.
  maximalExtensionLength (int): Maximum number of digits in the user’s extension.
  minimalExtensionLength (int): Minimum number of digits in the user’s extension.
  minimalGeneratedExtension (string): Minimal extension number generated for a new user.
keyPerfomanceIndicators (keyPerfomanceIndicators Note spelling.): Service Level setting used in reporting and statistics.
miscOptions (miscVccOptions): Other options for configuration.
  defaultCampaign (string): Name of the campaign selected by default when agents start manual calls to external numbers.
  enableReasonCodes (boolean): Whether agents can choose reason codes when selecting Not Ready and Logout. True: Agents can choose reason codes. False: Agents cannot choose reason codes.
  internalCallTimeout (int): Number of seconds to wait for a call to be answered by another agent. The default value is 20 seconds.
  maySelectCampaign (boolean): In the softphone menu, whether agents can select a campaign other than the default. True: Agents can select another campaign. False: Agents cannot select another campaign.
  maySelectNone (boolean): Whether agents can make manual calls not associated with a campaign. True: Agents can make manual calls. False: Agents cannot make manual calls.
  showDialAttempts (boolean): Whether agents can see call attempts automatically assigned a disposition by the dialer in the Contact Sessions panel. True: Agents can see call attempts. False: Agents cannot see call attempts.
  voicemailTimeout (int): Number of seconds for an agent to wait before accepting a transferred skill group voicemail. If the agent does not accept the voicemail message within the set time, the voicemail message is transferred to the next agent in the skill group.
passwordPolicies (passwordPolicies): Settings for password management.
  adminLoginAttempts (int): Number of allowed login attempts for administrators.
  enforcePasswordHistory (int): Number of passwords remembered by the system.
  loginAttempts (int): Number of allowed login attempts for agents.
  minCapitalCharacters (int): Minimum required number of capital letters.
  minNumberCharacters (int): Minimum required number of alphabetical characters in the password.
  minPasswordLength (int): Minimum length of a password.
  minSpecialCharacters (int): Minimum required number of special characters
  passwordExpires (int): Number of days before the expiration of the password
recordingsServer (remoteHostLoginSettings): FTP server settings for recordings.
  Enum: hostName, password, UserName
reportsServer (remoteHostLoginSettings): FTP server settings for reports.
  Enum: hostName, password, UserName
saleforceEmailAccount (sForceEmailAccount): Attributes of a Salesforce email account.
  consumerKey (string): Salesforce object that is automatically generated when you save a remote access definition.
  consumerSecret (string): Salesforce object that is automatically generated when you save a remote access definition.
  enabled (boolean): Whether the Salesforce email integration is enabled. True: Email integration is enabled. False: Email integration is not enabled.
  password (string): User’s password generated by Salesforce.
  securityToken (string): Security token that you provide to your agents in addition to the password generated by Salesforce if your agents’ IP address is not in the trusted IP range configured in Salesforce for your organization.
  userName (string): User’s name generated by Salesforce.
stateDialingRule (stateDialingRule): Information about the methods for finding the dialing rules that apply to the contact.
  Enum: REGION, REGION_THEN_PHONE_NUMBER, REGION_THEN_POSTCODE
timeZoneAssignment (timeZoneAssignment): Information about the methods for finding the contact’s time zone.
  Enum: PHONE_NUMBER, POSTCODE_THEN_PHONE_NUMBER, REGION_THEN_PHONE_NUMBER
transcriptsServer (remoteHostLoginSettings): FTP server settings for exporting recordings or reports to a remote server.
  Enum: hostName, password, UserName`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(VccModifyConfigSample)
			return nil
		}
		req := soap.NewRequest("modifyVCCConfiguration")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("configuration", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(VccCmd)
	VccCmd.AddCommand(VccGetApiVersionsCmd)
	VccCmd.AddCommand(VccGetConfigCmd)
	VccCmd.AddCommand(VccModifyConfigCmd)
	VccModifyConfigCmd.Flags().String("body-file", "", "JSON file for configuration parameter")
	VccModifyConfigCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
}
