// Code generated by codegen/generate_cli.py — DO NOT EDIT.
//
// To regenerate: python3 codegen/generate_cli.py

package cmd

import (
	"fmt"

	"github.com/Cloverhound/five9-cli/internal/output"
	"github.com/Cloverhound/five9-cli/internal/soap"
	"github.com/spf13/cobra"
)

var WebConnectorsCmd = &cobra.Command{
	Use:   "web-connectors",
	Short: "Manage web connectors",
}

var WebConnectorsCreateSample = `{
  "addWorksheet": false,
  "agentApplication": {
    "EmbeddedBrowser": "example",
    "ExternalBrowser": "example"
  },
  "clearTriggerDispositions": false,
  "constants": [
    {
      "key": "example",
      "value": "example"
    }
  ],
  "ctiWebServices": {
    "CurrentBrowserWindow": "example",
    "NewBrowserWindow": "example"
  },
  "description": "example",
  "executeInBrowser": false,
  "name": "example",
  "postConstants": [
    {
      "key": "example",
      "value": "example"
    }
  ],
  "postMethod": false,
  "postVariables": [
    {
      "key": "example",
      "value": "example"
    }
  ],
  "startPageText": "example",
  "trigger": "OnCallAccepted",
  "triggerDispositions": [
    "example"
  ],
  "url": "example",
  "variables": [
    {
      "key": "example",
      "value": "example"
    }
  ]
}`

var WebConnectorsModifySample = `{
  "addWorksheet": false,
  "agentApplication": {
    "EmbeddedBrowser": "example",
    "ExternalBrowser": "example"
  },
  "clearTriggerDispositions": false,
  "constants": [
    {
      "key": "example",
      "value": "example"
    }
  ],
  "ctiWebServices": {
    "CurrentBrowserWindow": "example",
    "NewBrowserWindow": "example"
  },
  "description": "example",
  "executeInBrowser": false,
  "name": "example",
  "postConstants": [
    {
      "key": "example",
      "value": "example"
    }
  ],
  "postMethod": false,
  "postVariables": [
    {
      "key": "example",
      "value": "example"
    }
  ],
  "startPageText": "example",
  "trigger": "OnCallAccepted",
  "triggerDispositions": [
    "example"
  ],
  "url": "example",
  "variables": [
    {
      "key": "example",
      "value": "example"
    }
  ]
}`

var WebConnectorsCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Creates a web connector.",
	Long:  `Creates a web connector.

Body file schema (webConnector):
addWorksheet (boolean): Applies only to POST requests. Whether to pass worksheet answers as parameters. True: Pass worksheet answers as parameters. False: Do not pass worksheet answers as parameters.
agentApplication (webConnectorAgentAppType): If executeInBrowser=true, this parameter specifies whether to open the URL in an external or an embedded browser.
  EmbeddedBrowser (string): Embedded browser window.
  ExternalBrowser (string): External browser window.
clearTriggerDispositions (boolean): When modifying an existing connector, whether to clear the existing triggers. True: Clear existing triggers. False: Do not clear existing triggers.
constants (keyValuePair[]): List of parameters passed with constant values.
  key (string): Name used to identify the pair.
  value (string): Value that corresponds to the name.
ctiWebServices (webConnectorCTIWebServicesType): In the Internet Explorer toolbar, whether to open the HTTP request in the current or a new browser window.
  CurrentBrowserWindow (string): Current browser window.
  NewBrowserWindow (string): New browser window.
description (string): Purpose of the connector.
executeInBrowser (boolean): When enabling the agent to view or enter data, whether to open the URL in an embedded or external browser window. True: External — open a browser window. False: Embedded — do not open a browser window, which is the desired action when using the On Call disposition triggers.
name (string): Name of the connector.
postConstants (keyValuePair[]): When using the POST method, constant parameters to pass in the URL.
  key (string): Name used to identify the pair.
  value (string): Value that corresponds to the name.
postMethod (boolean): Whether the HTTP request type is POST or GET. True: HTTP POST. False: HTTP GET.
postVariables (keyValuePair[]): When using the POST method, variable parameters to pass in the URL.
  key (string): Name used to identify the pair.
  value (string): Value that corresponds to the name.
startPageText (string): When using the POST method, enables the administrator to enter text to be displayed in the browser (or agent Browser tab) while waiting for the completion of the connector.
trigger (webConnectorTriggerType): Available trigger during a call when the request is sent.
  Enum: OnCallAccepted, OnCallDisconnected, ManuallyStarted, ManuallyStartedAllowDuringPreviews, OnPreview, OnContactSelection, OnWarmTransferInitiation, OnCallDispositioned, OnChatArrival, OnChatTransfer, OnChatTermination, OnChatClose, OnEmailArrival, OnEmailTransfer, OnEmailClose
triggerDispositions (string[]): When the trigger is OnCallDispositioned, specifies the trigger dispositions.
url (string): URL of the external Web site.
variables (keyValuePair[]): When using the POST method, connectors can include worksheet data as parameter values. The variable placeholder values are surrounded by @ signs. For example, the parameter ANI has the value @Call.ANI@
  key (string): Name used to identify the pair.
  value (string): Value that corresponds to the name.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(WebConnectorsCreateSample)
			return nil
		}
		req := soap.NewRequest("createWebConnector")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("connector", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var WebConnectorsDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Deletes a web connector.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("deleteWebConnector")
		flagName, _ := cmd.Flags().GetString("name")
		req.SetParam("name", flagName)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var WebConnectorsListCmd = &cobra.Command{
	Use:   "list",
	Short: "Returns the configuration of Web connectors.",
	RunE: func(cmd *cobra.Command, args []string) error {
		req := soap.NewRequest("getWebConnectors")
		flagNamePattern, _ := cmd.Flags().GetString("name-pattern")
		req.SetParam("namePattern", flagNamePattern)
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

var WebConnectorsModifyCmd = &cobra.Command{
	Use:   "modify",
	Short: "Updates a Web connector.",
	Long:  `Updates a Web connector.

Body file schema (webConnector):
addWorksheet (boolean): Applies only to POST requests. Whether to pass worksheet answers as parameters. True: Pass worksheet answers as parameters. False: Do not pass worksheet answers as parameters.
agentApplication (webConnectorAgentAppType): If executeInBrowser=true, this parameter specifies whether to open the URL in an external or an embedded browser.
  EmbeddedBrowser (string): Embedded browser window.
  ExternalBrowser (string): External browser window.
clearTriggerDispositions (boolean): When modifying an existing connector, whether to clear the existing triggers. True: Clear existing triggers. False: Do not clear existing triggers.
constants (keyValuePair[]): List of parameters passed with constant values.
  key (string): Name used to identify the pair.
  value (string): Value that corresponds to the name.
ctiWebServices (webConnectorCTIWebServicesType): In the Internet Explorer toolbar, whether to open the HTTP request in the current or a new browser window.
  CurrentBrowserWindow (string): Current browser window.
  NewBrowserWindow (string): New browser window.
description (string): Purpose of the connector.
executeInBrowser (boolean): When enabling the agent to view or enter data, whether to open the URL in an embedded or external browser window. True: External — open a browser window. False: Embedded — do not open a browser window, which is the desired action when using the On Call disposition triggers.
name (string): Name of the connector.
postConstants (keyValuePair[]): When using the POST method, constant parameters to pass in the URL.
  key (string): Name used to identify the pair.
  value (string): Value that corresponds to the name.
postMethod (boolean): Whether the HTTP request type is POST or GET. True: HTTP POST. False: HTTP GET.
postVariables (keyValuePair[]): When using the POST method, variable parameters to pass in the URL.
  key (string): Name used to identify the pair.
  value (string): Value that corresponds to the name.
startPageText (string): When using the POST method, enables the administrator to enter text to be displayed in the browser (or agent Browser tab) while waiting for the completion of the connector.
trigger (webConnectorTriggerType): Available trigger during a call when the request is sent.
  Enum: OnCallAccepted, OnCallDisconnected, ManuallyStarted, ManuallyStartedAllowDuringPreviews, OnPreview, OnContactSelection, OnWarmTransferInitiation, OnCallDispositioned, OnChatArrival, OnChatTransfer, OnChatTermination, OnChatClose, OnEmailArrival, OnEmailTransfer, OnEmailClose
triggerDispositions (string[]): When the trigger is OnCallDispositioned, specifies the trigger dispositions.
url (string): URL of the external Web site.
variables (keyValuePair[]): When using the POST method, connectors can include worksheet data as parameter values. The variable placeholder values are surrounded by @ signs. For example, the parameter ANI has the value @Call.ANI@
  key (string): Name used to identify the pair.
  value (string): Value that corresponds to the name.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		sample, _ := cmd.Flags().GetBool("sample")
		if sample {
			fmt.Println(WebConnectorsModifySample)
			return nil
		}
		req := soap.NewRequest("modifyWebConnector")
		bodyFile, _ := cmd.Flags().GetString("body-file")
		if bodyFile != "" {
			if err := req.SetBodyFile("connector", bodyFile); err != nil {
				return err
			}
		}
		data, err := soap.Do(req)
		if err != nil {
			return err
		}
		return output.Print(data)
	},
}

func init() {
	rootCmd.AddCommand(WebConnectorsCmd)
	WebConnectorsCmd.AddCommand(WebConnectorsCreateCmd)
	WebConnectorsCreateCmd.Flags().String("body-file", "", "JSON file for connector parameter")
	WebConnectorsCreateCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
	WebConnectorsCmd.AddCommand(WebConnectorsDeleteCmd)
	WebConnectorsDeleteCmd.Flags().String("name", "", "Name of Web connector.")
	WebConnectorsCmd.AddCommand(WebConnectorsListCmd)
	WebConnectorsListCmd.Flags().String("name-pattern", ".*", "Regular expression. If omitted, all objects are returned.")
	WebConnectorsCmd.AddCommand(WebConnectorsModifyCmd)
	WebConnectorsModifyCmd.Flags().String("body-file", "", "JSON file for connector parameter")
	WebConnectorsModifyCmd.Flags().Bool("sample", false, "Print sample JSON body and exit")
}
